import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
const $=id=>document.getElementById(id),stage=$('stage'),scene=new THREE.Scene();scene.background=new THREE.Color('#101820');
const camera=new THREE.PerspectiveCamera(40,1,.01,100);camera.position.set(5,3.7,6);
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(stage.clientWidth,stage.clientHeight);stage.prepend(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,1,.4);controls.enableDamping=true;
scene.add(new THREE.HemisphereLight(0xd9efff,0x34434b,3));const light=new THREE.DirectionalLight(0xffffff,4);light.position.set(3,6,4);scene.add(light);
scene.add(new THREE.GridHelper(10,20,0x4a6572,0x263640));
const loader=new GLTFLoader(),neutral=new THREE.MeshStandardMaterial({color:0xa2adb5,roughness:.7});let model,serial=0,kick=0,mixer,clips=[],family='';
function pose(){if(!model)return;const fixed=['Relay','Heptapod A6'].includes(family);model.getObjectByName('YAW').rotation.y=fixed?0:THREE.MathUtils.degToRad(+$('yaw').value);model.getObjectByName('PITCH').rotation.x=fixed?0:-THREE.MathUtils.degToRad(+$('pitch').value);model.traverse(o=>{if(o.isMesh)o.material=$('clay').checked?neutral:o.userData.original});}
function mobility(){if(!mixer)return;mixer.stopAllAction();const mode=$('mode').value;if(mode==='idle')return;const clip=clips.find(c=>c.name===(mode==='walk'?'Walk':'Anchor'));if(!clip)return;const action=mixer.clipAction(clip);action.reset();action.setLoop(mode==='walk'?THREE.LoopRepeat:THREE.LoopOnce,mode==='walk'?Infinity:1);action.clampWhenFinished=true;action.play();}
async function load(){const ticket=++serial,f=$('family').value,t=$('tier').value,url=`assets/${f.toLowerCase().replaceAll(' ','_')}_t${t}.glb`;$('download').href=url;$('status').textContent='Loading…';try{const gltf=await loader.loadAsync(url);if(ticket!==serial){dispose(gltf.scene);return;}if(model){mixer?.stopAllAction();mixer?.uncacheRoot(model);scene.remove(model);dispose(model);}model=gltf.scene;family=f;clips=gltf.animations;mixer=clips.length?new THREE.AnimationMixer(model):null;model.traverse(o=>{if(o.isMesh)o.userData.original=o.material});scene.add(model);kick=0;$('pitch').value=f==='Howitzer'?25:f==='Mortar'?68:0;$('yaw').value=0;pose();for(const id of ['yaw','pitch','recoil'])$(id).disabled=['Relay','Heptapod A6'].includes(f);$('pitch').min=f==='Mortar'?45:f==='Howitzer'?0:-10;$('mobility').hidden=f!=='Heptapod A6';$('mode').value='idle';$('status').textContent=`${f} / Tier ${t} · ${f==='Relay'?'Fixed structure':f==='Heptapod A6'?'Six legs · Triple joints · Vertical launch':'Articulated turret'}`;}catch(e){$('status').textContent='Preview failed. Serve this folder over HTTP and check internet access for Three.js.';console.error(e);}}
function dispose(root){const materials=new Set();root.traverse(o=>{if(o.isMesh){o.geometry.dispose();materials.add(o.userData.original||o.material)}});materials.forEach(m=>{if(m!==neutral)m.dispose()});}
for(const id of ['family','tier'])$(id).addEventListener('change',load);for(const id of ['yaw','pitch','clay'])$(id).addEventListener('input',pose);$('recoil').onclick=()=>kick=.15;$('mode').onchange=mobility;
new ResizeObserver(()=>{camera.aspect=stage.clientWidth/stage.clientHeight;camera.updateProjectionMatrix();renderer.setSize(stage.clientWidth,stage.clientHeight)}).observe(stage);
const clock=new THREE.Clock();renderer.setAnimationLoop(()=>{const dt=Math.min(clock.getDelta(),.05);kick=Math.max(0,kick-dt*.35);if(model)model.getObjectByName('RECOIL').position.z=-kick;mixer?.update(dt);controls.update();renderer.render(scene,camera)});load();
