import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
const $=id=>document.getElementById(id), base=new URL('../assets/ammunition/',import.meta.url);
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0x24343d);renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.5;$('stage').append(renderer.domElement);
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(40,1,.001,1000),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;
const pmrem=new THREE.PMREMGenerator(renderer),env=new RoomEnvironment();scene.environment=pmrem.fromScene(env).texture;env.dispose();pmrem.dispose();scene.add(new THREE.HemisphereLight(0xd7efff,0x574932,2));const light=new THREE.DirectionalLight(0xffedc8,3);light.position.set(4,8,5);scene.add(light);
let content=new THREE.Group();scene.add(content);const loader=new GLTFLoader(),cache=new Map();let families=[],filtered=[],serial=0,currentBounds=new THREE.Box3();
function options(id,items,value){$(id).replaceChildren(...items.map(([v,t])=>new Option(t,v)));if(items.some(([v])=>v===value))$(id).value=value;}
const formNames={round:'Complete round',projectile:'Flight projectile',case:'Empty case'};
function chosen(){return families.find(f=>f.id===$('family').value);}
function variant(f){return f.variants.find(v=>v.tier===$('tier').value&&v.form===$('form').value)||f.variants.find(v=>v.tier===$('tier').value)||f.variants[0];}
function setForms(){const f=chosen();if(!f)return;const legacy=f.shape==='legacy',old=$('tier').value;options('tier',legacy?[['legacy','Original / motion-lab mesh']]:[['game','Game / reduced mesh'],['display','Display / detailed']],old);$('tier').disabled=legacy;options('form',[...new Set(f.variants.map(v=>v.form))].map(v=>[v,formNames[v]]),$('form').value);}
function filter(){filtered=families.filter(f=>($('category').value==='all'||f.category===$('category').value)&&($('companion').value==='all'||f.companions.includes($('companion').value)));options('family',filtered.map(f=>[f.id,f.name]),$('family').value);setForms();show();}
async function model(v){const assetURL=new URL(v.file,base);assetURL.searchParams.set('v',v.bytes);const url=assetURL.href;if(!cache.has(url))cache.set(url,loader.loadAsync(url));return (await cache.get(url)).scene.clone(true);}
function fit(){if(currentBounds.isEmpty())return;const size=currentBounds.getSize(new THREE.Vector3()),center=currentBounds.getCenter(new THREE.Vector3()),radius=size.length()/2;controls.target.copy(center);const distance=radius/Math.sin(THREE.MathUtils.degToRad(camera.fov/2))/Math.min(1,camera.aspect)*1.15;camera.position.copy(center).add(new THREE.Vector3(.32,.18,1).normalize().multiplyScalar(distance));camera.near=Math.max(.00001,radius/1000);camera.far=Math.max(100,radius*100);camera.updateProjectionMatrix();controls.update();}
async function show(){const token=++serial,f=chosen();$('status').textContent='Loading…';$('legend').replaceChildren();content.traverse(o=>{if(o.isMesh)for(const m of [].concat(o.material))m.dispose();});scene.remove(content);content=new THREE.Group();scene.add(content);
if(!f){$('title').textContent='No matching ammunition';$('status').textContent='Choose another category or equipment filter.';$('stats').textContent='';$('download').removeAttribute('href');return;}
const v=variant(f),line=$('view').value!=='single',normalized=$('view').value==='lineup';$('download').href=new URL(v.file,base);$('title').textContent=line?(normalized?'Equal display height / sizes normalized':'Relative physical size / shared scale'):f.name;
$('stats').innerHTML=`<strong>${v.triangles.toLocaleString()} triangles · ${v.draw_calls} draw calls</strong><br>${formNames[v.form]} / ${v.tier}<br>${v.length_m.toFixed(3)} m length · ${(v.bytes/1024).toFixed(1)} KB<br>Finish: ${f.finish} · Tip: ${f.tip_color}<br>Companions: ${f.companions.join(', ')}<br>Export: +Z forward · ${v.pivot}`;
try{const selection=line?filtered:[f],models=await Promise.all(selection.map(e=>model(variant(e))));if(token!==serial)return;let x=0;const maxLength=Math.max(...selection.map(e=>variant(e).length_m));models.forEach((obj,i)=>{const holder=new THREE.Group();holder.add(obj);holder.rotation.x=-Math.PI/2;holder.updateMatrixWorld(true);let box=new THREE.Box3().setFromObject(holder),s=box.getSize(new THREE.Vector3());if(normalized)holder.scale.setScalar(1/s.y);holder.updateMatrixWorld(true);box.setFromObject(holder);s=box.getSize(new THREE.Vector3());holder.position.set(x-box.min.x,-box.min.y,-(box.min.z+box.max.z)/2);x+=s.x+(normalized?.17:maxLength*.045);holder.traverse(o=>{if(o.isMesh){o.material=Array.isArray(o.material)?o.material.map(m=>m.clone()):o.material.clone();for(const m of [].concat(o.material))m.wireframe=$('wire').checked;}});content.add(holder);if(line){const label=document.createElement('span');label.textContent=`${i+1}. ${selection[i].name}`;$('legend').append(label);}});currentBounds.setFromObject(content);fit();$('status').textContent=line?`${selection.length} families · left to right · ${normalized?'individual scales differ':'export proportions preserved; smallest rounds may be tiny'}`:'Orbit to inspect · Model shown upright; export travels along +Z';}catch(err){if(token===serial)$('status').textContent=`Unable to load model: ${err.message}`;}}
new ResizeObserver(()=>{const w=$('stage').clientWidth,h=$('stage').clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();}).observe($('stage'));
$('category').onchange=filter;$('companion').onchange=filter;$('family').onchange=()=>{setForms();show();};for(const id of ['tier','form','view'])$(id).onchange=show;$('reset').onclick=fit;$('wire').onchange=()=>content.traverse(o=>{if(o.isMesh)for(const m of [].concat(o.material))m.wireframe=$('wire').checked;});
renderer.setAnimationLoop(()=>{controls.update();renderer.render(scene,camera);});
try{const response=await fetch(new URL('manifest.json',base),{cache:'no-cache'});if(!response.ok)throw Error(response.status);families=(await response.json()).families;options('category',[['all','All ammunition'],...[...new Set(families.map(f=>f.category))].map(c=>[c,c])]);options('companion',[['all','All equipment'],...[...new Set(families.flatMap(f=>f.companions))].map(c=>[c,c==='mork'?'MÖRK':c.replaceAll('_',' ').replace(/^./,v=>v.toUpperCase())])],new URLSearchParams(location.search).get('companion'));filter();}catch(err){$('status').textContent=`Unable to load collection: ${err.message}`;}
