import * as T from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
const $=id=>document.getElementById(id),stage=$('stage'),aside=document.querySelector('aside');
document.querySelector('h1').textContent='MÖRK / Armored transport';
aside.innerHTML=`<div class="details"><label for="containerDetail">Model detail</label><select id="containerDetail"><option value="low">Low poly / game-ready</option><option value="standard">Original detail</option></select><label for="containerView">Container add-ons</label><select id="containerView"><option value="empty">Empty container</option><option value="loaded">Container + MÖRK inside</option><option value="diorama" selected>01 / 02 / 03 deployment diorama</option></select><label for="motion">Animation</label><select id="motion"></select><div class="buttons"><button id="playMotion">Play</button><button id="restartMotion">Restart</button></div><label for="motionTime">Timeline <output id="timeReadout">0.0 s</output></label><input id="motionTime" type="range" min="0" max="1" step=".001" value="0"><label for="motionSpeed">Playback speed</label><select id="motionSpeed"><option value=".5">½ speed</option><option value="1" selected>Normal</option></select><div class="toggles"><label><input id="roofCutaway" type="checkbox"> Hide roof / inspect fit</label><label><input id="wire" type="checkbox"> Wireframe</label></div><div class="buttons"><button id="frontView">Front</button><button id="frameView">Perspective</button></div><p id="containerStats"></p><p id="containerDescription" class="help"></p><a id="containerDownload" class="download" download>Download displayed 3D scene</a><a class="download secondary" href="../source/blender/mork-containers.blend" download>Editable Blender source</a><a class="download secondary" href="../assets/hover-tank/containers/mork-containers.zip" download>Download all container add-ons</a><p class="help">Drag to orbit · Scroll to zoom<br>6.6 × 14.2 m clear interior.<br>Tank stowed with cannon forward.<br>01 sealed · 02 parked · 03 deploying.</p><a href="../assets/hover-tank/containers/README.md">Integration notes</a><p class="help">Models by jelaludo</p></div>`;
stage.innerHTML='<div class="badge">MÖRK / TRANSPORT ADD-ONS</div><div id="caption"><strong id="status">Loading containers…</strong><p>Metres · +Y up · +Z forward</p></div>';
const scene=new T.Scene();scene.background=new T.Color('#101b22');
const camera=new T.PerspectiveCamera(40,1,.05,220),renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;stage.prepend(renderer.domElement);
const orbit=new OrbitControls(camera,renderer.domElement);orbit.enableDamping=true;orbit.maxPolarAngle=Math.PI*.49;
scene.add(new T.HemisphereLight(0xd8ecff,0x556050,2.6));const key=new T.DirectionalLight(0xffebcd,3.5);key.position.set(-14,28,24);key.castShadow=true;key.shadow.mapSize.set(2048,2048);Object.assign(key.shadow.camera,{left:-30,right:30,top:30,bottom:-30,near:.1,far:100});key.shadow.normalBias=.035;scene.add(key);const fill=new T.DirectionalLight(0x9ecde4,1.8);fill.position.set(12,9,-12);scene.add(fill);const cargoFill=new T.DirectionalLight(0xd6e8ee,1.6);cargoFill.position.set(0,3,25);cargoFill.target.position.set(0,2,0);scene.add(cargoFill,cargoFill.target);
const floor=new T.Mesh(new T.PlaneGeometry(150,150),new T.MeshStandardMaterial({color:0x24353b,roughness:.93}));floor.rotation.x=-Math.PI/2;floor.position.y=-.021;floor.receiveShadow=true;scene.add(floor);
let root,mixer,action,entry,clips=[],playing=false,serial=0,catalog=[];
function frame(front=false){const diorama=$('containerView').value==='diorama';orbit.target.set(0,1.8,diorama?4:1);camera.position.copy(orbit.target).add(new T.Vector3(...(front?(diorama?[0,12,52]:[0,4.5,26]):(diorama?[31,27,42]:[17,13,24]))).multiplyScalar(Math.max(1,1.12/camera.aspect)));orbit.update();}
function appearance(){root?.traverse(o=>{if(o.name.startsWith('ROOF_'))o.visible=!$('roofCutaway').checked;if(o.isMesh)for(const m of [o.material].flat())m.wireframe=$('wire').checked;});}
function time(){const duration=action?.getClip().duration||0;$('motionTime').value=duration?action.time/duration:0;$('timeReadout').textContent=`${(action?.time||0).toFixed(1)} / ${duration.toFixed(1)} s`;}
function choose(play=true){mixer.stopAllAction();action=null;const clip=clips.find(c=>c.name===$('motion').value);if(clip){action=mixer.clipAction(clip);action.reset().setLoop(T.LoopOnce,1);action.clampWhenFinished=true;action.play();mixer.update(0);}playing=play&&!!action;$('playMotion').textContent=playing?'Pause':'Play';time();}
function dispose(){if(!root)return;mixer.stopAllAction();mixer.uncacheRoot(root);scene.remove(root);const gs=new Set(),ms=new Set();root.traverse(o=>{if(o.isMesh){gs.add(o.geometry);for(const m of [o.material].flat())ms.add(m);}});gs.forEach(g=>g.dispose());ms.forEach(m=>m.dispose());}
async function load(){const ticket=++serial;$('status').textContent='Loading containers…';entry=catalog.find(e=>e.scene_mode===$('containerView').value&&e.detail===$('containerDetail').value);try{const g=await new GLTFLoader().loadAsync('../assets/hover-tank/containers/'+entry.file+'?v=floor-low-2');if(ticket!==serial)return;dispose();root=g.scene;clips=g.animations;root.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}});scene.add(root);const bays=[];root.traverse(o=>{if(o.userData.role==='tank_container')bays.push(o);});for(const bay of bays){const light=new T.PointLight(0xdde9de,75,15,2);light.position.set(0,3.3,1);bay.add(light);}mixer=new T.AnimationMixer(root);mixer.addEventListener('finished',()=>{playing=false;$('playMotion').textContent='Play';});$('motion').replaceChildren(...clips.map(c=>new Option(c.name.replaceAll('_',' '),c.name)));$('motion').value=entry.id.endsWith('diorama')?'Tank_Roll_Out':'Doors_Close';choose(false);if(action&&entry.preview_time_s){action.time=entry.preview_time_s;mixer.update(0);time();}appearance();frame();$('containerStats').textContent=entry.triangles.toLocaleString()+' triangles · '+entry.draw_calls+' material batches';$('containerDescription').textContent=entry.description;$('containerDownload').href='../assets/hover-tank/containers/'+entry.file;document.querySelector('a[href*="mork-containers.blend"],a[href*="mork-containers-low.blend"]').href='../source/blender/mork-containers'+(entry.detail==='low'?'-low':'')+'.blend';$('status').textContent=entry.name;window.containerLab={root,mixer,clips,entry};}catch(e){$('status').textContent='Could not load container: '+e.message;console.error(e);}}
$('containerView').onchange=$('containerDetail').onchange=load;$('motion').onchange=()=>choose();$('playMotion').onclick=()=>{if(action?.time>=action?.getClip().duration)choose();else{playing=!playing;$('playMotion').textContent=playing?'Pause':'Play';}};$('restartMotion').onclick=()=>choose();$('motionTime').oninput=()=>{playing=false;$('playMotion').textContent='Play';if(action){action.paused=false;action.time=+$('motionTime').value*action.getClip().duration;mixer.update(0);time();}};$('roofCutaway').onchange=$('wire').onchange=appearance;$('frontView').onclick=()=>frame(true);$('frameView').onclick=()=>frame();
new ResizeObserver(()=>{camera.aspect=stage.clientWidth/stage.clientHeight;camera.updateProjectionMatrix();renderer.setSize(stage.clientWidth,stage.clientHeight);if(root)frame();}).observe(stage);
const clock=new T.Clock();renderer.setAnimationLoop(()=>{const dt=Math.min(clock.getDelta(),.05);if(mixer&&playing){mixer.update(dt*+$('motionSpeed').value);time();}orbit.update();renderer.render(scene,camera);});
try{catalog=(await Promise.all(['manifest-low.json','manifest.json'].map(async file=>{const r=await fetch('../assets/hover-tank/containers/'+file+'?v=floor-low-2');if(!r.ok)throw Error('Manifest unavailable');return (await r.json()).assets;}))).flat();const requested=new URLSearchParams(location.search).get('scene');if(['empty','loaded','diorama'].includes(requested))$('containerView').value=requested;await load();}catch(e){$('status').textContent=e.message;}
