import * as T from 'three';import {PartCallouts} from './callouts.js?v=turret2';import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
const $=id=>document.getElementById(id),stage=$('stage'),scene=new T.Scene();scene.background=new T.Color('#101b22');
const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;stage.prepend(renderer.domElement);
const camera=new T.PerspectiveCamera(40,1,.03,200),orbit=new OrbitControls(camera,renderer.domElement);orbit.enableDamping=true;orbit.maxPolarAngle=Math.PI*.49;
scene.add(new T.HemisphereLight(0xbad9ea,0x344947,2));const key=new T.DirectionalLight(0xffedcc,3.2);key.position.set(-6,12,8);key.castShadow=true;key.shadow.mapSize.set(2048,2048);Object.assign(key.shadow.camera,{left:-12,right:12,top:12,bottom:-12,near:.1,far:40});key.shadow.normalBias=.025;scene.add(key);
const fill=new T.DirectionalLight(0x72d5ed,1.5);fill.position.set(8,5,-7);scene.add(fill);
const ground=new T.Mesh(new T.PlaneGeometry(100,100),new T.MeshStandardMaterial({color:0x20333b,roughness:.95}));ground.rotation.x=-Math.PI/2;ground.position.y=-.014;ground.receiveShadow=true;scene.add(ground);const grid=new T.GridHelper(50,50,0x526971,0x2b424b);grid.position.y=-.009;scene.add(grid);
const spill=[-2.15,2.15].map(x=>{const l=new T.PointLight(0x00bfff,0,5,2);l.position.set(x,.45,0);scene.add(l);return l});
const callouts=new PartCallouts(stage,camera);
const loader=new GLTFLoader(),neutral=new T.MeshStandardMaterial({color:0x9ba9aa,roughness:.7});let catalog=[],current,serial=0,powered=false,transition=null,shot=null,shells=27,elapsed=0,flashes=[];
function dispose(item){if(!item)return;item.mixer.stopAllAction();item.mixer.uncacheRoot(item.group);scene.remove(item.group);const gs=new Set(),ms=new Set();item.group.traverse(o=>{if(o.geometry)gs.add(o.geometry);for(const m of [o.userData.original||o.material].flat())if(m&&m!==neutral)ms.add(m)});gs.forEach(g=>g.dispose());ms.forEach(m=>m.dispose())}
function view(mode='perspective'){orbit.target.set(0,1.3,0);camera.position.set(...(mode==='rear'?[0,7,-11]:mode==='front'?[0,3.4,16]:[12,7.5,14]));orbit.update()}
function appearance(){neutral.wireframe=$('wire').checked;current?.group.traverse(o=>{if(o.userData.original){for(const material of [].concat(o.userData.original))material.wireframe=$('wire').checked;o.material=$('clay').checked?neutral:o.userData.original}})}
function indicators(){if(!current)return;const colors=[0x080c10,0xff4538,0xffb52e,0x35eaff];for(let i=0;i<9;i++){const n=current.group.getObjectByName('AMMO_PORT_LIGHT_'+String(i).padStart(2,'0'));const remaining=Math.max(0,Math.min(3,shells-i*3));if(n){n.userData.remaining_shells=remaining;n.traverse(o=>{if(!o.isMesh)return;if(!o.userData.ammoMaterial){o.userData.original=o.userData.original.clone();o.userData.ammoMaterial=true;}const m=o.userData.original;m.color.setHex(colors[remaining]);m.emissive.setHex(remaining?colors[remaining]:0);m.emissiveIntensity=remaining?2:0;o.material=$('clay').checked?neutral:m;});}}$('ammo').textContent=shells+' / 27'}
function buttons(){const active=current?.entry.functional;$('power').disabled=!active||!!transition;$('power').textContent=transition?(transition.on?'Lifting…':'Settling…'):(powered?'Power off':'Power on');$('fire').disabled=!active||!powered||!!transition||!!shot||shells<=0;$('plasmaFire').disabled=!active||!powered||!!transition;$('reload').disabled=!active;for(const id of ['yaw','elevation','plasmaL','plasmaR','sweep'])$(id).disabled=!active||!powered||!!transition;}
function pose(){if(!current)return;const r=current.refs;r.hover.position.set(0,powered?.55:0,0);r.body.position.set(0,0,0);r.body.rotation.set(0,0,0);for(const n of r.emitters)n.scale.setScalar(powered?1:.001)}
function action(name){const clip=current.gltf.animations.find(c=>c.name===name);if(!clip)return null;const a=current.mixer.clipAction(clip);a.reset().setLoop(T.LoopOnce,1);a.clampWhenFinished=true;a.play();return {a,duration:clip.duration,time:0}}
function power(){if(!current?.entry.functional||transition)return;if(shot){shot.a.stop();shot=null;}transition={...action(powered?'Power_Off':'Power_On'),on:!powered};buttons()}
function flash(node,color,size){if(!node)return;current.group.updateMatrixWorld(true);const mesh=new T.Mesh(new T.SphereGeometry(size,8,5),new T.MeshBasicMaterial({color,transparent:true}));mesh.position.copy(node.getWorldPosition(new T.Vector3()));mesh.quaternion.copy(node.getWorldQuaternion(new T.Quaternion()));mesh.scale.set(1,1,2.4);scene.add(mesh);flashes.push({mesh,life:.12,total:.12})}
function fire(){if(!powered||transition||shot||shells<=0||!current?.entry.functional)return false;shot=action('Fire_Heavy');shells--;indicators();flash(current.refs.muzzle,0xffcc77,.25);buttons();return true}
function plasmaFire(){if(!powered||transition||!current?.entry.functional)return false;for(const s of ['L','R'])flash(current.group.getObjectByName('PLASMA_MUZZLE_'+s),0x41eaff,.19);return true}
async function load(){const ticket=++serial;window.tankReady=false;$('status').textContent='Loading MÖRK…';const e=catalog.find(e=>e.damage_level===+$('damage').value&&e.detail===$('detail').value);try{const gltf=await loader.loadAsync('../assets/hover-tank/'+e.file+'?v='+e.bytes);const item={gltf,group:gltf.scene,entry:e,mixer:new T.AnimationMixer(gltf.scene)};if(ticket!==serial){dispose(item);return;}dispose(current);current=item;scene.add(item.group);item.group.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;o.userData.original=o.material}});item.refs={hover:item.group.getObjectByName('HOVER_RIG'),body:item.group.getObjectByName('HULL_SUSPENSION'),yaw:item.group.getObjectByName('TURRET_YAW'),pitch:item.group.getObjectByName('GUN_PITCH'),recoil:item.group.getObjectByName('GUN_RECOIL'),muzzle:item.group.getObjectByName('MUZZLE_00'),emitters:[]};item.group.traverse(o=>{if(o.name.startsWith('LIFT_EMITTER_'))item.refs.emitters.push(o)});powered=false;transition=null;shot=null;shells=e.functional?27:0;for(const id of ['yaw','elevation','plasmaL','plasmaR'])$(id).value=0;pose();indicators();buttons();appearance();view();await callouts.load(item.group,e.file);if(ticket!==serial)return;$('labels').disabled=e.static===true;$('stats').textContent=e.triangles.toLocaleString()+' triangles · '+(e.draw_calls||'—')+' material batches · '+Math.round(e.bytes/1024)+' KB';$('description').textContent=e.description;$('download').href='../assets/hover-tank/'+e.file;$('sourceDownload').href=e.detail==='distance'?'../source/blender/mork-hover-tank-distance.blend':'../source/blender/a6-hover-tank'+(e.detail==='low'?'-low':'')+'.blend';window.tank={get current(){return current},get powered(){return powered},get shells(){return shells},get transitioning(){return !!transition},get firing(){return !!shot},power,fire,plasmaFire};window.tankReady=true;}catch(e){$('status').textContent=e.message;console.error(e)}}
$('damage').onchange=load;$('detail').onchange=()=>{const distance=$('detail').value==='distance';if(distance)$('damage').value='0';$('damage').disabled=distance;load()};$('power').onclick=power;$('fire').onclick=fire;$('plasmaFire').onclick=plasmaFire;$('reload').onclick=()=>{shells=27;indicators();buttons()};$('rear').onclick=()=>view('rear');$('front').onclick=()=>view('front');$('reset').onclick=()=>view();$('clay').onchange=$('wire').onchange=appearance;
new ResizeObserver(()=>{camera.aspect=stage.clientWidth/stage.clientHeight;camera.updateProjectionMatrix();renderer.setSize(stage.clientWidth,stage.clientHeight)}).observe(stage);
const clock=new T.Clock();renderer.setAnimationLoop(()=>{const dt=Math.min(clock.getDelta(),.04);elapsed+=dt;if(current){current.mixer.update(dt);
 if(transition){transition.time+=dt;if(transition.time>=transition.duration){powered=transition.on;transition.a.stop();transition=null;pose();buttons()}}
 if(shot){shot.time+=dt;if(shot.time>=shot.duration){shot.a.stop();shot=null;current.refs.body.position.set(0,0,0);current.refs.body.rotation.set(0,0,0);current.refs.recoil.position.set(0,0,0);buttons()}}
 if(!transition){current.refs.hover.position.y=powered?.55:0;for(const n of current.refs.emitters)n.scale.setScalar(powered?1:.001)}
 if(current.entry.damage_level<3){current.refs.yaw.rotation.y=T.MathUtils.degToRad(+$('yaw').value);current.refs.pitch.rotation.x=-T.MathUtils.degToRad(+$('elevation').value);for(const [side,id,sign] of [['L','plasmaL',-1],['R','plasmaR',1]]){const angle=powered&&$('sweep').checked?sign*12*Math.sin(elapsed*Math.PI/2):+$(id).value;current.group.getObjectByName('PLASMA_YAW_'+side).rotation.y=T.MathUtils.degToRad(angle);$(id+'Value').textContent=angle.toFixed(0)+'°'}}
 $('yawValue').textContent=$('yaw').value+'°';$('elevationValue').textContent=$('elevation').value+'°';const powerLevel=transition?T.MathUtils.clamp(current.refs.hover.position.y/.55,0,1):(powered?1:0);spill.forEach(l=>l.intensity=12*powerLevel);$('status').textContent=current.entry.static?'MÖRK / Static distance proxy / D0 intact':'MÖRK / '+current.entry.state+' / '+(transition?(transition.on?'Powering on':'Heavy shutdown'):(powered?'Hover active':'Grounded'));
 }
 for(let i=flashes.length-1;i>=0;i--){const f=flashes[i];f.life-=dt;f.mesh.material.opacity=Math.max(0,f.life/f.total);if(f.life<=0){scene.remove(f.mesh);f.mesh.geometry.dispose();f.mesh.material.dispose();flashes.splice(i,1)}}orbit.update();callouts.update();renderer.render(scene,camera)});
try{catalog=(await Promise.all(['standard','low','distance'].map(async detail=>{const suffix=detail==='low'?'-low':detail==='distance'?'-distance':'';const r=await fetch('../assets/hover-tank/manifest'+suffix+'.json',{cache:'no-cache'});if(!r.ok)throw Error('Manifest unavailable');return (await r.json()).assets.map(e=>({...e,detail}));}))).flat();await load()}catch(e){$('status').textContent=e.message;console.error(e)}
