import * as T from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';

const $=id=>document.getElementById(id),stage=$('stage'),COMPLETE='robotic_assembly_line';
const scene=new T.Scene();scene.background=new T.Color('#142129');scene.fog=new T.Fog('#142129',90,220);
const camera=new T.PerspectiveCamera(38,1,.05,180),renderer=new T.WebGLRenderer({antialias:true});
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;stage.prepend(renderer.domElement);
const orbit=new OrbitControls(camera,renderer.domElement);orbit.enableDamping=true;orbit.maxPolarAngle=Math.PI*.49;
scene.add(new T.HemisphereLight(0xe5f6ff,0x4f6460,2));const light=new T.DirectionalLight(0xfff4df,3.5);light.position.set(-12,28,15);light.castShadow=true;light.shadow.mapSize.set(2048,2048);Object.assign(light.shadow.camera,{left:-25,right:25,top:25,bottom:-25,near:.1,far:100});light.shadow.bias=-.00015;light.shadow.normalBias=.04;scene.add(light);
const fill=new T.DirectionalLight(0x90c9e4,1);fill.position.set(9,5,-7);scene.add(fill);
const ground=new T.Mesh(new T.PlaneGeometry(600,600),new T.MeshStandardMaterial({color:0x1e3036,roughness:.95}));ground.rotation.x=-Math.PI/2;ground.position.y=-.405;ground.receiveShadow=true;scene.add(ground);
const grid=new T.GridHelper(100,100,0x476267,0x2c434b);grid.position.y=-.397;scene.add(grid);
const neutral=new T.MeshStandardMaterial({color:0xbac5bf,roughness:.7});
let sourceCatalog=[],lodCatalog=[],current=null,serial=0,playing=true;
const loader=new GLTFLoader();
const numberLabel=value=>Number.isFinite(value)?value.toLocaleString():'—';
const byteLabel=value=>Number.isFinite(value)?(value<1e6?`${(value/1000).toFixed(0)} KB`:`${(value/1e6).toFixed(2)} MB`):'—';
function fit(front=false){if(!current)return;const box=new T.Box3();current.group.traverse(object=>{if(object.isMesh&&!object.userData.overlay)box.union(new T.Box3().setFromObject(object));});const sphere=box.getBoundingSphere(new T.Sphere());orbit.target.copy(sphere.center);const angle=Math.min(T.MathUtils.degToRad(camera.fov/2),Math.atan(Math.tan(T.MathUtils.degToRad(camera.fov/2))*camera.aspect));const distance=sphere.radius/Math.sin(angle)*1.15;camera.position.copy(sphere.center).add(new T.Vector3(front?0:.9,front?.05:.75,front?1:1).normalize().multiplyScalar(distance));camera.far=Math.max(200,distance*4);camera.updateProjectionMatrix();orbit.update();}
function dispose(item){if(!item)return;item.mixer?.stopAllAction();item.mixer?.uncacheRoot(item.group);scene.remove(item.group);const geometries=new Set(),materials=new Set();item.group.traverse(object=>{if(object.geometry)geometries.add(object.geometry);for(const material of [object.userData.original||object.material].flat())if(material&&material!==neutral)materials.add(material);});geometries.forEach(geometry=>geometry.dispose());materials.forEach(material=>material.dispose());}
function overlays(item){item.marks=new T.Group();for(const socket of item.entry.sockets||[])item.marks.add(new T.ArrowHelper(new T.Vector3(...socket.normal),new T.Vector3(...socket.position_m),.7,socket.available?0x63edca:0xfb856a,.18,.1));item.bounds=new T.Group();for(const collider of item.entry.colliders||[]){const wire=new T.LineSegments(new T.EdgesGeometry(new T.BoxGeometry(...collider.size_m)),new T.LineBasicMaterial({color:0x70b5e7,depthTest:false,transparent:true,opacity:.7}));wire.position.fromArray(collider.center_m);item.bounds.add(wire);}item.group.add(item.marks,item.bounds);}
function appearance(){if(!current)return;current.marks.visible=$('sockets').checked;current.bounds.visible=$('colliders').checked;current.group.traverse(object=>{if(object.userData.original)object.material=$('clay').checked?neutral:object.userData.original;});}
function showTime(){const time=current?.action?current.action.time:0;$('timeline').value=time;$('time').textContent=time.toFixed(1)+' s';}
function selectedEntry(){const family=$('asset').value,damage=+$('damage').value;if(family===COMPLETE&&$('quality').value!=='detailed')return lodCatalog.find(entry=>entry.damage_level===damage&&entry.lod===+$('quality').value.slice(-1));return sourceCatalog.find(entry=>entry.family===family&&entry.damage_level===damage);}
function syncTierControl(){const complete=$('asset').value===COMPLETE;$('quality').disabled=!complete;if(!complete)$('quality').value='detailed';}
async function load(){const ticket=++serial;window.assemblyReady=false;syncTierControl();const entry=selectedEntry();if(!entry){$('status').textContent='Selected export is unavailable';return;}$('status').textContent='Loading module…';let item;
try{const gltf=await loader.loadAsync('../assets/assembly-line/'+entry.file+'?v='+entry.bytes);item={group:gltf.scene,entry};if(ticket!==serial){dispose(item);return;}let measuredDrawCalls=0;item.group.traverse(object=>{if(object.isMesh){object.castShadow=true;object.receiveShadow=true;object.userData.original=object.material;measuredDrawCalls+=Array.isArray(object.material)?object.material.length:1;}else if(object.isLine||object.isPoints)measuredDrawCalls++;});if(gltf.animations.length){item.mixer=new T.AnimationMixer(item.group);item.action=item.mixer.clipAction(gltf.animations[0]);item.action.play();item.duration=gltf.animations[0].duration;}$('motionPanel').hidden=!item.action;$('timeline').max=item.duration||8;overlays(item);dispose(current);current=item;scene.add(item.group);appearance();fit();showTime();const source=sourceCatalog.find(candidate=>candidate.family===entry.family&&candidate.damage_level===entry.damage_level);$('triangles').textContent=numberLabel(entry.triangles);$('draws').textContent=numberLabel(entry.draw_calls??measuredDrawCalls);$('bytes').textContent=byteLabel(entry.bytes);$('plot').textContent=Array.isArray(entry.plot_m)?entry.plot_m.join(' × ')+' m':'—';$('description').textContent=entry.description||source?.description||'';const tier=entry.lod===1?'LOD1 game candidate':entry.lod===2?'LOD2 static distance':'Detailed source';$('status').textContent=`${entry.name} / ${entry.state} / ${tier}`;$('download').href='../assets/assembly-line/'+entry.file;$('downloadMeshopt').hidden=!entry.meshopt_file;if(entry.meshopt_file)$('downloadMeshopt').href='../assets/assembly-line/'+entry.meshopt_file;window.assemblyKit={current,sourceCatalog,lodCatalog,scene,camera,orbit};window.assemblyReady=true;}catch(error){if(item)dispose(item);$('status').textContent='Load failed: '+error.message;console.error(error);}}
$('asset').onchange=()=>{$('quality').value=$('asset').value===COMPLETE?'lod1':'detailed';syncTierControl();load();};for(const id of ['damage','quality'])$(id).onchange=load;for(const id of ['sockets','colliders','clay'])$(id).onchange=appearance;
$('play').onclick=()=>{playing=!playing;$('play').textContent=playing?'Pause':'Play';};
$('rewind').onclick=()=>{current?.mixer?.setTime(0);showTime();};
$('timeline').oninput=()=>{playing=false;$('play').textContent='Play';current?.mixer?.setTime(+$('timeline').value);$('time').textContent=(+$('timeline').value).toFixed(1)+' s';};
$('reset').onclick=()=>fit();$('front').onclick=()=>fit(true);
new ResizeObserver(()=>{camera.aspect=stage.clientWidth/stage.clientHeight;camera.updateProjectionMatrix();renderer.setSize(stage.clientWidth,stage.clientHeight);fit();}).observe(stage);
const clock=new T.Clock();renderer.setAnimationLoop(()=>{const dt=Math.min(clock.getDelta(),.05);if(current?.mixer&&playing){current.mixer.update(dt*+$('speed').value);showTime();}orbit.update();renderer.render(scene,camera);});
try{const [sourceResponse,lodResponse]=await Promise.all([fetch('../assets/assembly-line/manifest.json',{cache:'no-cache'}),fetch('../assets/assembly-line/manifest-lods.json',{cache:'no-cache'})]);if(!sourceResponse.ok||!lodResponse.ok)throw Error('Manifest unavailable');sourceCatalog=(await sourceResponse.json()).assets;lodCatalog=(await lodResponse.json()).assets;$('asset').replaceChildren(...sourceCatalog.filter(entry=>entry.damage_level===0).map(entry=>new Option(entry.name,entry.family)));$('asset').value=COMPLETE;$('quality').value='lod1';await load();}catch(error){$('status').textContent=error.message;console.error(error);}
