export const collections=[
['korp','KORP / Heavy gunship','Combat','MÖRK-family assault aircraft with forward rotary cannons, a downward-aiming heavy gun, tilting engines and mechanical animations.','3 LODs · 7 clips · Engine-driven aiming','Animated'],
['fabrication-lab','Stålheart / MÖRK fabrication','Industry','Watch the existing Stålheart Terraformer form an existing MÖRK tank from an energized AFR-9 structural lattice.','3 LODs · 16-second one-shot · Meshopt','Animated'],
['ammunition','Ammunition / bullets, shells & missiles','Missile','Companion ammunition for Rotor, Needle, MÖRK and mortar sentries. Inspect flight projectiles, complete rounds, empty cases and missiles.','21 families · Game + display tiers','Game-ready'],
['hugin-flight','HUGIN / SH02 · 3D rocket','Industry','Orbit the standalone rocket, inspect its tripod joints, play landing suspension and top-door animations, and change its marking.','Interactive 3D · 5 animations','Animated'],
['antenna-array','SKYWARD / Antenna array','Infrastructure','Steerable radio dishes with continuous reflector shells, three detail levels, destruction states and a lightweight synchronized seven-dish scene.','3 detail levels · 4 states','Animated'],
['missile-lab','Missile motion lab','Combat','Three reusable projectiles. Soft launch, nose-up coast and accelerating flight arcs.','3 mesh budgets · 3 flight profiles','Animated'],
['hover-tank','MÖRK','Combat','MÖRK hover tank plus fitted armored transport containers: empty, loaded and a numbered three-bay deployment diorama.','Tank + 3 transport add-ons','Animated'],
['sentries','Sentry families','Combat','Eleven articulated tower families, from Needle to the six-legged Heptapod A6.','33 equipment variants','Animated'],
['reckon-guard','Reckon-Guard','Combat','Inspect the autonomous guard drone and its moving assemblies.','Interactive model','Animated'],
['game-assets','HUGIN + Stålheart / Game editions','Industry','Reduced-mesh editions of the launchpad and planetary printer, together for comparison.','Around 40K triangles each','Game-ready'],
['launchpad','HUGIN','Industry','Reusable entry vehicle, launch platform and articulated cargo-catching arm.','2 detail levels · 4 states','Animated'],
['terraformer','Stålheart / Terraformer 3000','Industry','An imposing rail-mounted printer with a six-joint arm and twin material reservoirs.','2 detail levels · 4 states','Animated'],
['assembly-line','Robotic assembly line','Industry','A long conveyor, articulated robots, gantries and reusable factory modules.','Complete line + modules','Animated'],
['warehouse-props','Logistics & cargo','Industry','A roofless loading-bay diorama with a container, loaded pallet, cases and fuel barrels.','Modular collection','Props'],
['solar-power','Solar power network','Infrastructure','Solar arrays and tower grids with detailed, game and distance models, Meshopt downloads and automatic LOD preview.','3 LODs · Meshopt · 4 damage states','Game-ready'],
['micro-reactor','Open micro-reactor','Infrastructure','An exposed reactor core and its surrounding machinery.','Power systems','Animated'],
['research-outpost','Alien research outpost','Infrastructure','Labs, habitats, utilities and service structures for an extraterrestrial settlement.','12 families · 48 models','Modular'],
['base-kit','Foundations & walls / Game-ready','Infrastructure','Lightweight foundations, walls, corners and an animated gate. Compare original meshes and inspect up to 1,000 GPU-instanced modules.','8 modules · Original + game tiers','Game-ready'],
['ctf-flags','Capture the Flag','Props','Faction banners, pole styles and capture sockets with animated flag behavior.','6 banners · 3 pole styles','Animated'],
['station-crew','Station crew','Characters','Suited astronauts, scientists and workers with shared animation controls.','3 roles · 7 clips','Animated'],
['animation-tests','KESTREL / Frontier EVA','Characters','An original detailed astronaut with a lean weathered suit, opaque visor and circular walk/run previews.','Original EVA · 7 clips','Animated']
].map(([id,title,category,description,meta,tag])=>({id,title,category,description,meta,tag,image:id==='fabrication-lab'?'assets/workshop/terraformer.jpg':`assets/workshop/${id}.jpg`,url:`${id}/`}));
