import * as T from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {MeshoptDecoder} from 'three/addons/libs/meshopt_decoder.module.js';

const $=id=>document.getElementById(id),stage=$('stage');
const scene=new T.Scene(),camera=new T.PerspectiveCamera(40,1,.1,500),renderer=new T.WebGLRenderer({antialias:true});
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0x0d1920);renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;stage.prepend(renderer.domElement);
const pmrem=new T.PMREMGenerator(renderer),environment=new RoomEnvironment();scene.environment=pmrem.fromScene(environment).texture;environment.dispose();pmrem.dispose();
scene.add(new T.HemisphereLight(0xd8f4ff,0x33454a,2.2));const sun=new T.DirectionalLight(0xffe9c7,3.4);sun.position.set(-24,48,35);scene.add(sun);const rim=new T.DirectionalLight(0x4bdcff,1.5);rim.position.set(25,12,-30);scene.add(rim);
const floor=new T.Mesh(new T.PlaneGeometry(150,150),new T.MeshStandardMaterial({color:0x1c3037,roughness:.93,metalness:.08}));floor.rotation.x=-Math.PI/2;floor.position.y=-.03;scene.add(floor);const grid=new T.GridHelper(80,8,0x52737a,0x304950);grid.position.y=-.02;scene.add(grid);
const orbit=new OrbitControls(camera,renderer.domElement);orbit.enableDamping=true;orbit.maxPolarAngle=Math.PI*.49;
const loader=new GLTFLoader().setMeshoptDecoder(MeshoptDecoder);let manifest,model,mixer,action,entry,playing=false,ticket=0;
const size=bytes=>bytes>1048576?(bytes/1048576).toFixed(1)+' MB':(bytes/1024).toFixed(0)+' KB';
function cameraPreset(name='bay'){const poses={bay:{target:[-1,3,2],eye:[18,12,25]},wide:{target:[0,11,0],eye:[47,35,57]},top:{target:[-1,1.5,2],eye:[-1,48,2.01]}},pose=poses[name];orbit.target.fromArray(pose.target);camera.position.fromArray(pose.eye);orbit.update();}
function phaseText(time){const machine='The canonical Terraformer tier remains complete and solid. ';if(entry?.lod===2)return machine+'Static distance view holds the authored endpoint: a complete, recognizable MÖRK made only from cyan wireframe linework.';if(time<.25)return machine+'Stålheart has energized the MÖRK fabrication origin; no solid tank geometry is present.';if(time<15.95)return machine+'The MÖRK wireframe rises with the fabrication boundary. Its linework remains the only tank representation throughout the one-shot.';return machine+'Endpoint reached: the complete MÖRK silhouette, turret, cannon and hover chassis remain a wireframe. Armor reveal is intentionally deferred.';}
function showTime(time){const percent=Math.round(time/16*100);$('timeline').value=time;$('time').textContent=`${time.toFixed(1)} s / ${percent}%`;$('phase').textContent=phaseText(time);$('badge').textContent=`MÖRK WIREFRAME ${percent}% · MACHINE COMPLETE`;}
function syncPrintBands(time){const wireframe=model?.getObjectByName('MORK_BUILD_WIREFRAME'),names=wireframe?.userData.band_nodes||[];if(names.length<2)return;for(let index=0;index<names.length;index++){const band=model.getObjectByName(names[index]);band.position.y=0;band.visible=time+1e-4>=(index+1)/names.length*16;}}
function setTime(time){if(!mixer)return;time=Math.min(16,Math.max(0,time));mixer.setTime(time);syncPrintBands(time);showTime(time);appearance();}
function appearance(){if(!model)return;const wireframe=model.getObjectByName('MORK_BUILD_WIREFRAME'),front=model.getObjectByName('FABRICATION_FRONT');if(wireframe)wireframe.visible=$('wireframe').checked;if(front)front.visible=$('front').checked;}
function dispose(root){if(!root)return;const geometries=new Set(),materials=new Set();root.traverse(o=>{if(o.isMesh){geometries.add(o.geometry);[].concat(o.material).forEach(m=>materials.add(m));}});geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());scene.remove(root);}
async function load(){const serial=++ticket;playing=false;$('status').textContent='Loading fabrication scene…';entry=manifest.assets.find(asset=>asset.lod===+$('lod').value);const compressed=$('encoding').value==='meshopt',file=compressed?entry.meshopt_file:entry.file;
 try{const gltf=await loader.loadAsync('../assets/fabrication-lab/'+file+'?v='+(compressed?entry.meshopt_bytes:entry.bytes));if(serial!==ticket){dispose(gltf.scene);return;}mixer?.stopAllAction();dispose(model);model=gltf.scene;scene.add(model);mixer=new T.AnimationMixer(model);action=gltf.animations[0]?mixer.clipAction(gltf.animations[0]):null;if(action){action.setLoop(T.LoopOnce,1);action.clampWhenFinished=true;action.play();setTime(16);}else{showTime(16);}$('motion').hidden=!action;$('front').parentElement.hidden=!action;$('triangles').textContent=entry.triangles.toLocaleString();$('draws').textContent=entry.draw_calls.toLocaleString();$('plainBytes').textContent=size(entry.bytes);$('meshoptBytes').textContent=size(entry.meshopt_bytes);$('download').href='../assets/fabrication-lab/'+file;appearance();cameraPreset('bay');$('status').textContent=`LOD${entry.lod} / ${entry.detail} · ${compressed?'decoded Meshopt':'plain GLB'} · ${entry.state}`;window.fabricationViewer={model,mixer,entry,manifest,scene,camera,orbit,setTime};window.fabricationViewerReady=true;}catch(error){$('status').textContent='Unable to load: '+error.message;console.error(error);}}
$('lod').onchange=load;$('encoding').onchange=load;$('timeline').oninput=()=>{playing=false;setTime(+$('timeline').value);};$('play').onclick=()=>{if(!action)return;setTime(0);playing=true;};$('pause').onclick=()=>{playing=false;};for(const button of document.querySelectorAll('[data-time]'))button.onclick=()=>{playing=false;setTime(+button.dataset.time);};for(const id of ['wireframe','front'])$(id).onchange=appearance;for(const button of document.querySelectorAll('[data-camera]'))button.onclick=()=>cameraPreset(button.dataset.camera);
new ResizeObserver(()=>{renderer.setSize(stage.clientWidth,stage.clientHeight);camera.aspect=stage.clientWidth/stage.clientHeight;camera.updateProjectionMatrix();}).observe(stage);const clock=new T.Clock();renderer.setAnimationLoop(()=>{const dt=Math.min(clock.getDelta(),.05);if(playing&&mixer){mixer.update(dt);const time=action.time;syncPrintBands(time);showTime(time);if(time>=15.999)playing=false;}orbit.update();renderer.render(scene,camera);});
try{const response=await fetch('../assets/fabrication-lab/manifest.json',{cache:'no-cache'});if(!response.ok)throw Error('Manifest unavailable');manifest=await response.json();await load();}catch(error){$('status').textContent=error.message;console.error(error);}
