import * as T from 'three';import {OrbitControls} from 'three/addons/controls/OrbitControls.js';import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
const $=id=>document.getElementById(id),stage=$('stage'),scene=new T.Scene();scene.background=new T.Color('#15242a');scene.add(new T.HemisphereLight(0xd3eaff,0x756552,2.6));const sun=new T.DirectionalLight(0xffe7c4,3.6);sun.position.set(60,110,30);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-110,right:110,top:110,bottom:-110,near:1,far:300});sun.shadow.normalBias=.08;sun.shadow.bias=-.00015;scene.add(sun);
const camera=new T.PerspectiveCamera(38,1,.1,1200),renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;stage.prepend(renderer.domElement);const orbit=new OrbitControls(camera,renderer.domElement);orbit.enableDamping=true;orbit.maxPolarAngle=Math.PI*.49;
const ground=new T.Mesh(new T.PlaneGeometry(1600,1600),new T.MeshStandardMaterial({color:0x514b40,roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.y=-.08;ground.receiveShadow=true;scene.add(ground);const grid=new T.GridHelper(400,80,0x696858,0x575c51);grid.position.y=-.065;scene.add(grid);
const loader=new GLTFLoader(),neutral=new T.MeshStandardMaterial({color:0xabb9b2,roughness:.75});let catalog=[],current=null,serial=0,time=0,playing=true;
function dispose(item){if(!item)return;item.mixer.stopAllAction();item.mixer.uncacheRoot(item.group);scene.remove(item.group);const gs=new Set(),ms=new Set();item.group.traverse(o=>{if(o.geometry)gs.add(o.geometry);for(const m of [o.userData.original||o.material].flat())if(m&&m!==neutral)ms.add(m)});gs.forEach(g=>g.dispose());ms.forEach(m=>m.dispose());}
function fit(){if(!current)return;const array=current.entry.kind==='array';orbit.target.set(0,array?8:10,0);const offset=new T.Vector3(...(array?[150,107,180]:[30,15,37])).multiplyScalar(Math.max(1,1.15/camera.aspect));camera.position.copy(orbit.target).add(offset);orbit.update();}
function appearance(){current?.group.traverse(o=>{if(o.userData.original)o.material=$('clay').checked?neutral:o.userData.original;});}
function controls(){const active=!!current?.entry.functional;$('play').disabled=$('scrub').disabled=$('speed').disabled=!active;$('play').textContent=playing?'Pause':'Play';$('detail').disabled=$('damage').disabled=$('mode').value==='array';}
async function load(){const ticket=++serial;window.antennaReady=false;$('caption').textContent='Loading…';const entry=catalog.find(e=>$('mode').value==='array'?e.kind==='array':e.kind==='antenna'&&e.detail===$('detail').value&&e.damage_level===+$('damage').value);try{const gltf=await loader.loadAsync('../assets/antenna-array/'+entry.file),item={entry,group:gltf.scene,mixer:new T.AnimationMixer(gltf.scene),gltf};if(ticket!==serial){dispose(item);return;}dispose(current);current=item;scene.add(item.group);item.group.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;o.userData.original=o.material;}});if(entry.functional)item.mixer.clipAction(gltf.animations.find(a=>a.name==='Array_Slew')).play();item.mixer.setTime(time);appearance();controls();fit();$('stats').textContent=`${entry.triangles.toLocaleString()} triangles · ${entry.draw_calls} batches${entry.kind==='array'?' · 7 low-detail antennas':''}`;$('description').textContent=entry.description;$('download').href='../assets/antenna-array/'+entry.file;$('caption').textContent=entry.name+' / '+entry.state;window.antennaReady=true;}catch(e){$('caption').textContent=e.message;console.error(e);}}
for(const id of ['detail','damage'])$(id).onchange=load;$('mode').onchange=()=>{if($('mode').value==='array'){$('detail').value='low';$('damage').value='0';}load();};$('play').onclick=()=>{playing=!playing;controls();};$('reset').onclick=fit;$('clay').onchange=appearance;$('scrub').oninput=()=>{time=+$('scrub').value;playing=false;current?.mixer.setTime(time);controls();};new ResizeObserver(()=>{camera.aspect=stage.clientWidth/stage.clientHeight;camera.updateProjectionMatrix();renderer.setSize(stage.clientWidth,stage.clientHeight);fit();}).observe(stage);
const clock=new T.Clock();renderer.setAnimationLoop(()=>{const dt=Math.min(clock.getDelta(),.05);if(current?.entry.functional&&playing){time=(time+dt*+$('speed').value)%44;current.mixer.setTime(time);} $('scrub').value=time;$('time').textContent=time.toFixed(1)+' / 44 s';orbit.update();renderer.render(scene,camera);});window.antenna={get current(){return current},get time(){return time}};
try{const r=await fetch('../assets/antenna-array/manifest.json');if(!r.ok)throw Error('Manifest unavailable');catalog=(await r.json()).assets;await load();}catch(e){$('caption').textContent=e.message;console.error(e);}
