import * as T from 'three';import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
const $=id=>document.getElementById(id),stage=$('stage'),scene=new T.Scene();scene.background=new T.Color('#172329');scene.add(new T.HemisphereLight(0xe5f6ff,0x43504b,2.2));const sun=new T.DirectionalLight(0xffe4bf,3.4);sun.position.set(-10,18,12);scene.add(sun);const camera=new T.PerspectiveCamera(38,1,.05,300),renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.toneMapping=T.ACESFilmicToneMapping;stage.prepend(renderer.domElement);const orbit=new OrbitControls(camera,renderer.domElement);orbit.enableDamping=true;orbit.maxPolarAngle=Math.PI*.49;const ground=new T.Mesh(new T.PlaneGeometry(220,220),new T.MeshStandardMaterial({color:0x202d2e,roughness:.95}));ground.rotation.x=-Math.PI/2;ground.position.y=-.35;scene.add(ground);scene.add(new T.GridHelper(120,120,0x4a6262,0x2c4244));const neutral=new T.MeshStandardMaterial({color:0xbac5bf,roughness:.7});const loader=new GLTFLoader();let catalog=[],item=null,serial=0;
function fit(front=false){if(!item)return;const box=new T.Box3().setFromObject(item.group,true),sphere=box.getBoundingSphere(new T.Sphere());orbit.target.copy(sphere.center);const distance=sphere.radius/Math.sin(T.MathUtils.degToRad(camera.fov/2))*1.25;camera.position.copy(sphere.center).add(new T.Vector3(front?0:.65,front?.05:.65,1).normalize().multiplyScalar(distance));camera.far=Math.max(300,distance*4);camera.updateProjectionMatrix();orbit.update();}
function dispose(x){if(!x)return;scene.remove(x.group);x.group.traverse(o=>{o.geometry?.dispose();});}
function decorate(x){x.marks=new T.Group();for(const s of x.entry.sockets)x.marks.add(new T.ArrowHelper(new T.Vector3(...s.normal),new T.Vector3(...s.position_m),.7,s.available?0x65dfb8:0xf38369,.15,.1));x.bounds=new T.Group();for(const c of x.entry.colliders){const w=new T.LineSegments(new T.EdgesGeometry(new T.BoxGeometry(...c.size_m)),new T.LineBasicMaterial({color:0x6eafe7,transparent:true,opacity:.7,depthTest:false}));w.position.fromArray(c.center_m);x.bounds.add(w)}x.group.add(x.marks,x.bounds)}
function appearance(){if(!item)return;item.marks.visible=$('sockets').checked;item.bounds.visible=$('colliders').checked;item.group.traverse(o=>{if(o.userData.original)o.material=$('clay').checked?neutral:o.userData.original})}
async function load(){const e=catalog.find(x=>x.family===$('asset').value&&x.damage_level===+$('damage').value);window.warehouseReady=false;$('status').textContent='Loading…';try{const g=await loader.loadAsync('../assets/micro-reactor/'+e.file),x={entry:e,group:g.scene};x.group.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;o.userData.original=o.material}});decorate(x);dispose(item);item=x;scene.add(x.group);$('download').href='../assets/micro-reactor/'+e.file;$('plot').textContent=e.plot_m.join(' × ')+' m';$('triangles').textContent=e.triangles.toLocaleString();$('description').textContent=e.description;$('status').textContent=e.name+' / '+e.state;appearance();fit();window.warehouseKit={item,catalog,camera,orbit};window.warehouseReady=true}catch(err){$('status').textContent='Load failed: '+err.message;console.error(err)}}
for(const id of ['asset','damage'])$(id).onchange=load;for(const id of ['sockets','colliders','clay'])$(id).onchange=appearance;$('reset').onclick=()=>fit();$('front').onclick=()=>fit(true);new ResizeObserver(()=>{camera.aspect=stage.clientWidth/stage.clientHeight;camera.updateProjectionMatrix();renderer.setSize(stage.clientWidth,stage.clientHeight);fit()}).observe(stage);renderer.setAnimationLoop(()=>{orbit.update();renderer.render(scene,camera)});
try{const r=await fetch('../assets/micro-reactor/manifest.json');catalog=(await r.json()).assets;$('asset').replaceChildren(...catalog.filter(e=>e.damage_level===0).map(e=>new Option(e.name,e.family)));await load()}catch(e){$('status').textContent=e.message}
