import * as T from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
const $=id=>document.getElementById(id),stage=$('stage'),scene=new T.Scene();scene.background=new T.Color('#0c1820');
const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));stage.append(renderer.domElement);const camera=new T.PerspectiveCamera(43,1,.1,100);camera.position.set(7,6,9);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,1.7,.6);controls.enableDamping=true;
scene.add(new T.HemisphereLight(0xc2e6ff,0x54616a,2.5));const key=new T.DirectionalLight(0xffe1b4,3.5);key.position.set(2,7,4);scene.add(key);const rim=new T.DirectionalLight(0x61e9dd,3);rim.position.set(-4,3,-4);scene.add(rim);scene.add(new T.GridHelper(24,24,0x4a6771,0x203841));
const targets=[new T.Vector3(0,.1,3.2),new T.Vector3(-3,.1,1.2),new T.Vector3(3,.1,.4)].map((position,i)=>{const marker=new T.Mesh(new T.CylinderGeometry(.55,.55,.12,12),new T.MeshStandardMaterial({color:0xc5783c,metalness:.4,roughness:.55}));marker.position.copy(position);scene.add(marker);const ring=new T.Mesh(new T.TorusGeometry(.68,.022,4,24),new T.MeshBasicMaterial({color:0x65d9cd}));ring.rotation.x=Math.PI/2;ring.position.copy(position).y=.18;scene.add(ring);return {position:position.clone().setY(.17),marker,ring,hits:0};});
const gltf=await new GLTFLoader().loadAsync('../assets/reckon-guard/reckon_guard.glb'),drone=new T.Group();drone.add(gltf.scene);scene.add(drone);const gimbal=gltf.scene.getObjectByName('GIMBAL'),recoil=gltf.scene.getObjectByName('RECOIL'),muzzle=gltf.scene.getObjectByName('MUZZLE_00');const mixer=new T.AnimationMixer(gltf.scene);for(const clip of gltf.animations)mixer.clipAction(clip).play();
const {assets:[entry]}=await fetch('../assets/reckon-guard/manifest.json').then(r=>r.json());$('stats').textContent=`${entry.triangles.toLocaleString()} triangles · ${(entry.bytes/1024).toFixed(0)} KB · Independent rotors and weapon mount`;
const shots=[],impacts=[],shotGeo=new T.SphereGeometry(.055,6,4),shotMat=new T.MeshBasicMaterial({color:0xb0fff0});let elapsed=0,cooldown=0,kick=0,shotsFired=0,totalHits=0;
function aim(){drone.updateMatrixWorld(true);const target=targets[Number($('target').value)].position,origin=gimbal.getWorldPosition(new T.Vector3()),direction=target.clone().sub(origin).normalize();const world=new T.Quaternion().setFromUnitVectors(new T.Vector3(0,0,1),direction);gimbal.quaternion.copy(gimbal.parent.getWorldQuaternion(new T.Quaternion()).invert().multiply(world));drone.updateMatrixWorld(true);}
function fire(){if(cooldown>0)return false;aim();const origin=muzzle.getWorldPosition(new T.Vector3()),direction=muzzle.getWorldDirection(new T.Vector3());const projectile=new T.Mesh(shotGeo,shotMat);projectile.position.copy(origin);scene.add(projectile);shots.push({mesh:projectile,velocity:direction.multiplyScalar(15),life:2,target:Number($('target').value)});kick=.09;cooldown=.28;shotsFired++;return true;}
$('fire').onclick=fire;$('reset').onclick=()=>{for(const t of targets){t.hits=0;t.marker.material.color.setHex(0xc5783c);}totalHits=0;};
new ResizeObserver(()=>{camera.aspect=stage.clientWidth/stage.clientHeight;camera.updateProjectionMatrix();renderer.setSize(stage.clientWidth,stage.clientHeight);}).observe(stage);
const clock=new T.Clock();renderer.setAnimationLoop(()=>{const dt=Math.min(clock.getDelta(),.04);elapsed+=dt;cooldown=Math.max(0,cooldown-dt);drone.position.y=Number($('altitude').value)+($('hover').checked?.07*Math.sin(elapsed*1.8):0);drone.rotation.z=$('hover').checked?.018*Math.sin(elapsed*1.1):0;mixer.update(dt*3);kick=Math.max(0,kick-dt*.65);recoil.position.z=-kick;aim();if($('auto').checked)fire();
for(let i=shots.length-1;i>=0;i--){const s=shots[i];s.life-=dt;const old=s.mesh.position.clone();s.mesh.position.addScaledVector(s.velocity,dt);if(s.mesh.position.y<=.17&&old.y>.17){const fraction=(old.y-.17)/(old.y-s.mesh.position.y);s.mesh.position.lerpVectors(old,s.mesh.position,fraction);const t=targets[s.target];if(s.mesh.position.distanceTo(t.position)<.55){t.hits++;totalHits++;t.marker.material.color.setHex(0x40565b);}const fx=new T.Mesh(new T.IcosahedronGeometry(.13,0),new T.MeshBasicMaterial({color:0xffb453,transparent:true}));fx.position.copy(s.mesh.position);scene.add(fx);impacts.push({mesh:fx,life:.35});s.life=0;}if(s.life<=0){scene.remove(s.mesh);shots.splice(i,1);}}
for(let i=impacts.length-1;i>=0;i--){const f=impacts[i];f.life-=dt;f.mesh.scale.multiplyScalar(1+dt*5);f.mesh.material.opacity=Math.max(0,f.life/.35);if(f.life<=0){scene.remove(f.mesh);f.mesh.geometry.dispose();f.mesh.material.dispose();impacts.splice(i,1);}}
targets.forEach((t,i)=>t.ring.visible=i===Number($('target').value));$('status').textContent=`${shotsFired} projectiles · ${totalHits} target hits · Altitude ${Number($('altitude').value).toFixed(1)} m`;controls.update();renderer.render(scene,camera);});
window.reckon={drone,gltf,gimbal,muzzle,targets,fire,get shotsFired(){return shotsFired},get hits(){return totalHits}};
