import * as T from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
const $=id=>document.getElementById(id),stage=$('stage'),scene=new T.Scene();scene.background=new T.Color('#14242a');scene.fog=new T.Fog('#14242a',70,180);
const camera=new T.PerspectiveCamera(38,1,.05,250),renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(stage.clientWidth,stage.clientHeight);renderer.shadowMap.enabled=true;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.35;stage.prepend(renderer.domElement);
const orbit=new OrbitControls(camera,renderer.domElement);orbit.enableDamping=true;orbit.maxPolarAngle=Math.PI*.495;scene.add(new T.HemisphereLight(0xe9f6ff,0x516e69,2.3));const sun=new T.DirectionalLight(0xffedcc,3.2);sun.position.set(-9,16,12);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-20,right:20,top:20,bottom:-20,near:.1,far:50});scene.add(sun);const fill=new T.DirectionalLight(0x7fc9e6,1);fill.position.set(8,7,-8);scene.add(fill);const floor=new T.Mesh(new T.PlaneGeometry(200,200),new T.MeshStandardMaterial({color:0x20343a,roughness:.95}));floor.rotation.x=-Math.PI/2;floor.position.y=-.025;floor.receiveShadow=true;scene.add(floor);const grid=new T.GridHelper(80,80,0x527278,0x30484d);grid.position.y=.001;scene.add(grid);
const loader=new GLTFLoader();let catalog=[],current=null,request=0,playing=true,selected='ALL';
function fit(top=false){if(!current)return;const b=new T.Box3().setFromObject(current.group),s=b.getBoundingSphere(new T.Sphere());orbit.target.copy(s.center);const a=Math.min(T.MathUtils.degToRad(camera.fov/2),Math.atan(Math.tan(T.MathUtils.degToRad(camera.fov/2))*camera.aspect)),distance=s.radius/Math.sin(a)*1.22;camera.position.copy(s.center).add(new T.Vector3(top?0:.9,top?1:.65,top?.02:1).normalize().multiplyScalar(distance));orbit.update();}
function dispose(item){if(!item)return;item.mixer?.stopAllAction();scene.remove(item.group);const gs=new Set(),ms=new Set();item.group.traverse(o=>{if(o.geometry)gs.add(o.geometry);if(o.material)for(const m of [].concat(o.material))ms.add(m);});gs.forEach(g=>g.dispose());ms.forEach(m=>m.dispose());}
function focus(name){selected=name;for(const b of document.querySelectorAll('[data-focus]'))b.classList.toggle('active',b.dataset.focus===name);const notes={ALL:'Two gantry heads seat red explosive tips on empty shells. Eight crates hold 24 missiles, sorted by type.',GANTRY:'The compact dual fixture holds empty shells while the gantry lowers and seats separate explosive tips. A finished round rests on the output cradle.',DART:'DART: six lightweight swarm rounds in two mint-marked crates.',NEEDLE:'NEEDLE: six general sentry rounds in two blue-marked crates.',TALON:'TALON: six special rounds in two amber-marked crates.',CRUISE:'CRUISE: six larger ammunition-design missiles in two red-marked crates; the detailed source is displayed at 0.27 scale.'};$('focusNote').textContent=notes[name];if(!current)return;if(name==='ALL'){fit();return;}const targets=[];current.group.traverse(o=>{if(name==='GANTRY'&&o.name==='TIP_GANTRY_ROOT'||o.name.startsWith('STORAGE_CRATE_')&&o.userData.missile_family===name)targets.push(o);});if(targets.length){const p=new T.Vector3();targets.forEach(o=>p.add(o.getWorldPosition(new T.Vector3())));p.multiplyScalar(1/targets.length);orbit.target.copy(p);camera.position.copy(p).add(new T.Vector3(3.2,3.2,5));orbit.update();}}
function sockets(){if(current)current.arrows.visible=$('sockets').checked;}
async function load(){const ticket=++request,entry=catalog.find(e=>e.lod===+$('tier').value);if(!entry)return;$('status').textContent='Loading '+entry.file+'…';try{const gltf=await loader.loadAsync('../assets/missile-factory/'+entry.file+'?v='+entry.sha256.slice(0,10));if(ticket!==request)return;const item={group:gltf.scene,entry};item.group.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}});item.arrows=new T.Group();for(const socket of entry.sockets)item.arrows.add(new T.ArrowHelper(new T.Vector3(...socket.normal),new T.Vector3(...socket.position_m),.65,0x76e7c2,.17,.09));item.group.add(item.arrows);if(gltf.animations.length){item.mixer=new T.AnimationMixer(item.group);item.action=item.mixer.clipAction(gltf.animations[0]);item.action.play();}dispose(current);current=item;scene.add(item.group);$('motionPanel').hidden=!item.action;$('timeline').max=item.action?.getClip().duration||6;$('triangles').textContent=entry.triangles.toLocaleString();$('draws').textContent=entry.draw_calls.toLocaleString();$('bytes').textContent=(entry.bytes/1000).toFixed(0)+' KB';$('download').href='../assets/missile-factory/'+entry.file;$('downloadMeshopt').href='../assets/missile-factory/'+entry.meshopt_file;$('status').textContent=['Detailed master · original missile geometry','Game tier · animated tip gantry','Static distance tier'][entry.lod];sockets();fit();if(selected!=='ALL')focus(selected);window.missileFactory={scene,camera,orbit,current,manifest:catalog};window.missileFactoryReady=true;}catch(error){$('status').textContent='Unable to load factory: '+error.message;console.error(error);}}
document.querySelectorAll('[data-focus]').forEach(b=>b.onclick=()=>focus(b.dataset.focus));$('tier').onchange=load;$('sockets').onchange=sockets;$('play').onclick=()=>{playing=!playing;$('play').textContent=playing?'Pause':'Play';};$('restart').onclick=()=>{current?.mixer?.setTime(0);$('timeline').value=0;$('time').textContent='0.0 s';};$('timeline').oninput=()=>{playing=false;$('play').textContent='Play';current?.mixer?.setTime(+$('timeline').value);$('time').textContent=(+$('timeline').value).toFixed(1)+' s';};$('fit').onclick=()=>fit();$('top').onclick=()=>fit(true);new ResizeObserver(()=>{camera.aspect=stage.clientWidth/stage.clientHeight;camera.updateProjectionMatrix();renderer.setSize(stage.clientWidth,stage.clientHeight);fit();}).observe(stage);const clock=new T.Clock();renderer.setAnimationLoop(()=>{const dt=Math.min(clock.getDelta(),.05);if(current?.mixer&&playing){current.mixer.update(dt*+$('speed').value);$('timeline').value=current.action.time;$('time').textContent=current.action.time.toFixed(1)+' s';}orbit.update();renderer.render(scene,camera);});try{const r=await fetch('../assets/missile-factory/manifest.json',{cache:'no-cache'});if(!r.ok)throw Error('Manifest unavailable');catalog=(await r.json()).assets;await load();}catch(error){$('status').textContent=error.message;console.error(error);}
