import * as T from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
const $=id=>document.getElementById(id),stage=$('stage');
const scene=new T.Scene();scene.background=new T.Color('#142129');scene.fog=new T.Fog('#142129',65,140);
const camera=new T.PerspectiveCamera(38,1,.05,180),renderer=new T.WebGLRenderer({antialias:true});
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;stage.prepend(renderer.domElement);
const orbit=new OrbitControls(camera,renderer.domElement);orbit.enableDamping=true;orbit.maxPolarAngle=Math.PI*.49;
scene.add(new T.HemisphereLight(0xe5f6ff,0x4f6460,2));const light=new T.DirectionalLight(0xfff4df,3.5);light.position.set(-7,13,9);light.castShadow=true;light.shadow.mapSize.set(2048,2048);Object.assign(light.shadow.camera,{left:-20,right:20,top:20,bottom:-20,near:.1,far:50});light.shadow.bias=-.00015;light.shadow.normalBias=.04;scene.add(light);
const fill=new T.DirectionalLight(0x90c9e4,1);fill.position.set(9,5,-7);scene.add(fill);
const ground=new T.Mesh(new T.PlaneGeometry(180,180),new T.MeshStandardMaterial({color:0x1e3036,roughness:.95}));ground.rotation.x=-Math.PI/2;ground.position.y=-.405;ground.receiveShadow=true;scene.add(ground);
const grid=new T.GridHelper(100,100,0x476267,0x2c434b);grid.position.y=-.397;scene.add(grid);
const neutral=new T.MeshStandardMaterial({color:0xbac5bf,roughness:.7});let catalog=[],instances=[],serial=0,gateTarget=null,selected='wall',assetBase='../assets/base-kit-game/',frameSeconds=0,frameCount=0;const catalogs={};
function spec(){return catalog.find(a=>a.id===($('asset').value==='wall'?`wall_standard_d${$('damage').value}`:{corner:'wall_corner_d0',gate:'gate_vehicle_d0',foundation:'foundation_flat_d0',slab:'foundation_slab'}[$('asset').value]));}
function reset(front=false){const repeated=$('asset').value==='repeated',assembly=$('asset').value==='assembly',gate=$('asset').value==='gate',foundation=$('asset').value==='foundation';const slab=$('asset').value==='slab';const distance=slab?Math.max(...$('slabSize').value.split(',').map(Number))*1.8:repeated?Math.sqrt(Number($('count').value))*7.8:assembly?34:gate?18:9;camera.far=Math.max(180,distance*4);camera.updateProjectionMatrix();scene.fog.near=(repeated||slab)?distance*2:65;scene.fog.far=(repeated||slab)?distance*3:140;orbit.target.set(0,assembly?1.4:gate?2:(foundation||slab)?0:1.35,assembly?1.5:0);camera.position.copy(orbit.target).add(new T.Vector3(front?0:.55,front?.04:.36,front?1:.82).multiplyScalar(distance));orbit.update();}
function dispose(instance){instance.mixer?.stopAllAction();instance.mixer?.uncacheRoot(instance.group);scene.remove(instance.group);const materials=new Set();instance.group.traverse(o=>{if(o.geometry)o.geometry.dispose();if(o.material){const m=o.userData.original||o.material;for(const item of Array.isArray(m)?m:[m])if(item!==neutral)materials.add(item);}});materials.forEach(m=>m.dispose());}
function overlays(instance){const {entry,group}=instance;const marks=new T.Group();marks.name='Socket overlays';for(const s of entry.sockets){const arrow=new T.ArrowHelper(new T.Vector3(...s.normal),new T.Vector3(...s.position_m).add(new T.Vector3(0,.05,0)),.65,s.available?0x60ecc3:0xff795c,.15,.1);marks.add(arrow);const dot=new T.Mesh(new T.SphereGeometry(.06,8,6),new T.MeshBasicMaterial({color:s.available?0x60ecc3:0xff795c,depthTest:false}));dot.position.fromArray(s.position_m);marks.add(dot);}group.add(marks);instance.marks=marks;
 const bounds=new T.Group();for(const box of entry.colliders){const wire=new T.LineSegments(new T.EdgesGeometry(new T.BoxGeometry(...box.size_m)),new T.LineBasicMaterial({color:box.condition==='gate_closed'?0xffb962:0x6cadfa,transparent:true,opacity:.8,depthTest:false}));wire.position.fromArray(box.center_m);wire.userData.condition=box.condition;bounds.add(wire);}group.add(bounds);instance.bounds=bounds;}
function appearance(){for(const instance of instances){instance.marks.visible=$('sockets').checked;instance.bounds.visible=$('colliders').checked;instance.bounds.children.forEach(o=>o.visible=o.userData.condition!=='gate_closed'||+$('gate').value<.99);instance.group.traverse(o=>{if(o.isMesh&&o.userData.original){o.material=$('clay').checked?neutral:o.userData.original;for(const m of Array.isArray(o.material)?o.material:[o.material])m.wireframe=$('wireframe').checked;}});}}
function gatePose(){for(const i of instances){if(i.action){i.action.time=+$('gate').value*i.action.getClip().duration;i.mixer.update(0);}}$('gateButton').textContent=+$('gate').value>.5?'Close gate':'Open gate';appearance();}
async function instantiate(entry,pos=[0,0,0],rotation=0){const gltf=await new GLTFLoader().loadAsync((entry.id==='foundation_slab'?'../assets/base-kit-game/':assetBase)+entry.file),group=gltf.scene;group.position.fromArray(pos);group.rotation.y=rotation;group.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;o.userData.original=o.material;}});const instance={entry,group};if(gltf.animations.length){instance.mixer=new T.AnimationMixer(group);instance.action=instance.mixer.clipAction(gltf.animations[0]);instance.action.setLoop(T.LoopOnce,1);instance.action.clampWhenFinished=true;instance.action.play();instance.action.paused=true;}overlays(instance);return instance;}
async function repeatedModules(){
 const count=Number($('count').value),columns=Math.ceil(Math.sqrt(count));
 const ids=['foundation_flat_d0','wall_standard_d0','wall_corner_d0'];
 const templates=await Promise.all(ids.map(id=>instantiate(catalog.find(a=>a.id===id))));
 const group=new T.Group(),placements=ids.map(()=>[]);let triangles=0;
 for(let i=0;i<count;i++){
  const kind=i%10<6?0:i%10<9?1:2;
  const x=(i%columns-(columns-1)/2)*4,z=(Math.floor(i/columns)-(Math.ceil(count/columns)-1)/2)*4;
  placements[kind].push(new T.Matrix4().makeTranslation(x,0,z));triangles+=templates[kind].entry.triangles;
 }
 for(let j=0;j<templates.length;j++){
  const template=templates[j];template.group.remove(template.marks,template.bounds);template.group.updateMatrixWorld(true);
  if($('instancing').checked){
   template.group.traverse(o=>{if(!o.isMesh)return;const batch=new T.InstancedMesh(o.geometry,o.material,placements[j].length);batch.userData.original=o.material;batch.castShadow=true;batch.receiveShadow=true;
    placements[j].forEach((p,i)=>batch.setMatrixAt(i,new T.Matrix4().multiplyMatrices(p,o.matrixWorld)));batch.instanceMatrix.needsUpdate=true;batch.computeBoundingSphere();group.add(batch);
   });
  }else for(const transform of placements[j]){const copy=template.group.clone(true);copy.traverse(o=>{if(o.isMesh)o.userData.original=o.material;});copy.applyMatrix4(transform);group.add(copy);}
  // Overlay helper geometry is not included in repeated production meshes.
  for(const helper of [template.marks,template.bounds])helper.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});
 }
 const marks=new T.Group(),bounds=new T.Group();group.add(marks,bounds);
 return {group,marks,bounds,entry:{triangles,plot_m:[columns*4,Math.ceil(count/columns)*4]},moduleCount:count};
}
async function load(){const ticket=++serial,mode=$('asset').value;selected=mode;$('status').textContent='Loading geometry…';window.baseKitReady=false;gateTarget=null;const previousMode=load.previous;load.previous=mode;const tier=$('tier').value;const limited=tier==='original'&&!$('instancing').checked;for(const option of $('count').options)option.disabled=limited&&Number(option.value)>100;if(limited)$('count').value='100';assetBase=tier==='game'?'../assets/base-kit-game/':'../assets/base-kit/';if(!catalogs[tier]){const response=await fetch(assetBase+'manifest.json');if(!response.ok)throw Error('Manifest unavailable');catalogs[tier]=(await response.json()).assets;const slabResponse=await fetch('../assets/base-kit-game/foundation-slab.json');if(!slabResponse.ok)throw Error('Slab metadata unavailable');catalogs[tier].push(await slabResponse.json());}if(ticket!==serial)return;catalog=catalogs[tier];$('tierBadge').textContent=mode==='slab'?'SCALABLE SLAB / 28 TRIANGLES':tier==='game'?'8 MODULES / GAME-READY':'7 MODULES / ORIGINAL + SLAB';$('slabPanel').hidden=mode!=='slab';$('tier').disabled=mode==='slab';$('source').href=mode==='slab'?'../source/blender/foundation-slab.blend':tier==='game'?'../source/blender/a6-wall-kit-game.blend':'../source/blender/a6-wall-kit.blend';$('repeatPanel').hidden=mode!=='repeated';for(const id of ['sockets','colliders']){$(id).disabled=mode==='repeated';if(mode==='repeated')$(id).checked=false;}
 $('damagePanel').hidden=!['wall','assembly'].includes(mode);$('gatePanel').hidden=!['gate','assembly'].includes(mode);$('download').hidden=['assembly','repeated'].includes(mode);
 const find=id=>catalog.find(a=>a.id===id);let placement=[];
 if(mode==='assembly'){
  placement.push([find('gate_vehicle_d0'),[0,0,0],0]);
  for(const x of [-8,8])placement.push([find(`wall_standard_d${$('damage').value}`),[x,0,0],0]);
  placement.push([find('wall_corner_d0'),[-12,0,0],0],[find('wall_corner_d0'),[12,0,0],-Math.PI/2]);
  for(const x of [-12,12])placement.push([find('wall_standard_d0'),[x,0,4],Math.PI/2]);
  for(const x of [-12,-8,-4,0,4,8,12])for(const z of [0,4])placement.push([find('foundation_flat_d0'),[x,0,z],0]);
 }else if(mode!=='repeated')placement=[[spec(),[0,0,0],0]];
 const pending=await Promise.allSettled(mode==='repeated'?[repeatedModules()]:placement.map(([entry,pos,rot])=>instantiate(entry,pos,rot)));const loaded=pending.filter(r=>r.status==='fulfilled').map(r=>r.value);if(ticket!==serial){loaded.forEach(dispose);return;}const failed=pending.find(r=>r.status==='rejected');if(failed){loaded.forEach(dispose);$('status').textContent='Load failed — '+failed.reason.message;console.error(failed.reason);return;}
 instances.forEach(dispose);instances=loaded;if(mode==='slab'){const [w,d]=$('slabSize').value.split(',').map(Number);instances[0].group.scale.set(w/40,1,d/40);}instances.forEach(i=>scene.add(i.group));ground.visible=grid.visible=mode!=='repeated';ground.position.y=mode==='slab'?-1.205:['foundation','assembly'].includes(mode)?-.405:-.005;grid.position.y=ground.position.y+.008;gatePose();if(previousMode!==mode||['repeated','slab'].includes(mode))reset();
 const triangles=instances.reduce((sum,i)=>sum+i.entry.triangles,0);$('triangles').textContent=triangles.toLocaleString();
 if(mode==='repeated'){$('plot').textContent=instances[0].entry.plot_m.join(' × ')+' m';$('description').textContent=`${$('count').value} modules: 60% foundations, 30% straight walls, 10% corners. ${$('instancing').checked?'Shared geometry with GPU instancing.':'Individual mesh objects using shared geometry.'} Frame interval is measured on this device; shadows and pixel resolution affect results.`;$('status').textContent=`${tier==='game'?'Game-ready':'Original'} / repeated modules`;}
 else if(mode==='assembly'){$('plot').textContent='28 × 8 m';$('description').textContent='Gate, two wall states, corners and return walls on tiled foundations. Socket positions align exactly in the intact assembly. Destroyed walls lose their connection availability.';$('status').textContent='Connection study / wall state D'+$('damage').value;}
 else{const entry=spec();$('plot').textContent=(mode==='slab'?$('slabSize').value.split(','):entry.plot_m).join(' × ')+' m';$('description').textContent=entry.description;$('download').href=(mode==='slab'?'../assets/base-kit-game/':assetBase)+entry.file;$('status').textContent=entry.name+' / '+entry.state;}
 window.baseKit={instances,catalog,camera,orbit,mode};window.baseKitReady=true;
}
for(const id of ['asset','damage','tier','count','instancing','slabSize'])$(id).onchange=()=>load().catch(e=>{$('status').textContent=e.message;console.error(e);});for(const id of ['sockets','colliders','clay','wireframe'])$(id).onchange=appearance;$('gate').oninput=()=>{gateTarget=null;gatePose();};$('gateButton').onclick=()=>gateTarget=+$('gate').value>.5?0:1;$('reset').onclick=()=>reset();$('front').onclick=()=>reset(true);
new ResizeObserver(()=>{camera.aspect=stage.clientWidth/stage.clientHeight;camera.updateProjectionMatrix();renderer.setSize(stage.clientWidth,stage.clientHeight);}).observe(stage);
renderer.shadowMap.enabled=false;$('shadows').onchange=()=>{renderer.shadowMap.enabled=$('shadows').checked;};
const clock=new T.Clock();renderer.setAnimationLoop(()=>{const elapsed=clock.getDelta(),dt=Math.min(elapsed,.05);frameSeconds+=elapsed;frameCount++;if(gateTarget!==null){const value=+$('gate').value,step=dt/1.6;const next=Math.abs(gateTarget-value)<step?gateTarget:value+Math.sign(gateTarget-value)*step;$('gate').value=next;gatePose();if(next===gateTarget)gateTarget=null;}orbit.update();renderer.render(scene,camera);if(frameSeconds>=.5){$('performance').textContent=`${(frameSeconds/frameCount*1000).toFixed(1)} ms/frame · ${(frameCount/frameSeconds).toFixed(0)} FPS · ${renderer.info.render.calls} draws · ${renderer.info.render.triangles.toLocaleString()} rendered triangles` ;frameSeconds=0;frameCount=0;}});
const query=new URLSearchParams(location.search);if(query.get('module')==='repeated'){$('asset').value='repeated';if(['100','400','1000'].includes(query.get('count')))$('count').value=query.get('count');}if(query.get('module')==='slab'){$('asset').value='slab';if([...$('slabSize').options].some(o=>o.value===query.get('size')))$('slabSize').value=query.get('size');}
try{await load();}catch(e){$('status').textContent=e.message;console.error(e);}
