// Original procedural spiral galaxy: a fixed distant perspective reference.
export function createGalaxy(T){
 const galaxy=new T.Group();galaxy.name='CINEMATIC_DISTANT_GALAXY';galaxy.position.set(-700,-650,-1900);galaxy.rotation.set(.22,-.12,-.32);
 const count=11000,position=new Float32Array(count*3),color=new Float32Array(count*3),sizes=new Float32Array(count);let seed=8817;const random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};
 for(let i=0;i<count;i++){const r=Math.pow(random(),.72),arm=i%4,angle=arm*Math.PI/2+r*8.5+(random()-.5)*(.18+r*.52),radius=r*720,x=Math.cos(angle)*radius+(random()-.5)*35,y=Math.sin(angle)*radius*.36+(random()-.5)*13,z=(random()-.5)*25*(1-r);position.set([x,y,z],i*3);const c=new T.Color(0xffe2b3).lerp(new T.Color(i%7===0?0xc59af1:0x759fd8),Math.min(1,r*1.4));c.multiplyScalar(.5+random()*.5);color.set(c.toArray(),i*3);sizes[i]=1+random()*2.5;}
 const geometry=new T.BufferGeometry();geometry.setAttribute('position',new T.BufferAttribute(position,3));geometry.setAttribute('color',new T.BufferAttribute(color,3));geometry.setAttribute('pointSize',new T.BufferAttribute(sizes,1));
 const material=new T.ShaderMaterial({vertexColors:true,transparent:true,depthWrite:false,blending:T.AdditiveBlending,vertexShader:'attribute float pointSize;varying vec3 tint;void main(){tint=color;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);gl_PointSize=pointSize;}',fragmentShader:'varying vec3 tint;void main(){vec2 p=gl_PointCoord-.5;float a=exp(-dot(p,p)*18.0)*.52;gl_FragColor=vec4(tint,a);}'});galaxy.add(new T.Points(geometry,material));
 const glow=new T.Mesh(new T.PlaneGeometry(1000,390),new T.ShaderMaterial({transparent:true,depthWrite:false,side:T.DoubleSide,blending:T.AdditiveBlending,vertexShader:'varying vec2 uv0;void main(){uv0=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}',fragmentShader:'varying vec2 uv0;void main(){vec2 p=(uv0-.5)*2.0;float r=dot(p,p);float core=exp(-r*24.0);float halo=exp(-r*4.5);vec3 c=mix(vec3(.3,.42,.7),vec3(1.,.86,.63),core);gl_FragColor=vec4(c,core*.48+halo*.045);}'}));glow.position.z=-2;galaxy.add(glow);return galaxy;
}
