import {createGalaxy} from './galaxy.js?v=sol-tracking-3';
import {applyLaunch,launchState} from '../assets/orbital-launcher/runtime.js';
import {cinematicState,CENTER,PLANET_RADIUS,MIRROR_COUNT,mirrorOrbit} from './timeline.js?v=sol-tracking-3';
export function createCinematic(T,{launcher,sol,solClips,mirror}){
 const scene=new T.Scene();scene.background=new T.Color(0x020610);const center=new T.Vector3(...CENTER),site=new T.Group();site.name='CINEMATIC_LAUNCH_SITE';scene.add(site);site.add(launcher);
 const sphere=new T.SphereGeometry(PLANET_RADIUS,96,64),positions=sphere.attributes.position,colors=new Float32Array(positions.count*3);for(let i=0;i<positions.count;i++){const n=new T.Vector3().fromBufferAttribute(positions,i).normalize(),v=Math.sin(n.x*6+Math.sin(n.z*5))*Math.cos(n.y*8-n.z*3)+Math.sin(n.y*15+n.x*4)*.5,land=v>.22,c=new T.Color(Math.abs(n.y)>.88?0xcbd9d8:land?v>.8?0x697354:0x366651:0x123d59);c.multiplyScalar(.9+Math.sin(n.x*31+n.z*47)*.035);colors.set(c.toArray(),i*3);}sphere.setAttribute('color',new T.BufferAttribute(colors,3));const planet=new T.Mesh(sphere,new T.MeshStandardMaterial({vertexColors:true,roughness:.82,metalness:.12}));planet.name='CINEMATIC_SMALL_PLANET';planet.position.copy(center);scene.add(planet);
 const atmosphere=new T.Mesh(new T.SphereGeometry(PLANET_RADIUS*1.025,64,48),new T.ShaderMaterial({vertexShader:'varying vec3 n;varying vec3 v;void main(){vec4 p=modelViewMatrix*vec4(position,1.0);n=normalize(normalMatrix*normal);v=normalize(-p.xyz);gl_Position=projectionMatrix*p;}',fragmentShader:'varying vec3 n;varying vec3 v;void main(){float a=pow(1.0-abs(dot(normalize(n),normalize(v))),3.0);gl_FragColor=vec4(.16,.58,.85,a*.32);}',transparent:true,side:T.BackSide,depthWrite:false,blending:T.AdditiveBlending}));atmosphere.name='CINEMATIC_ATMOSPHERE';atmosphere.position.copy(center);scene.add(atmosphere);
 const platform=new T.Mesh(new T.CylinderGeometry(35,37,1.6,64),new T.MeshStandardMaterial({color:0x26363e,roughness:.85,metalness:.25}));platform.position.y=-.81;site.add(platform);
 const stars=new Float32Array(1800*3);for(let i=0;i<1800;i++){const y=1-2*(i+.5)/1800,a=i*2.399963,r=Math.sqrt(1-y*y);stars.set([Math.cos(a)*r*1600,y*1600-140,Math.sin(a)*r*1600],i*3);}const starGeometry=new T.BufferGeometry();starGeometry.setAttribute('position',new T.BufferAttribute(stars,3));scene.add(new T.Points(starGeometry,new T.PointsMaterial({color:0xbad9ed,size:1.25,sizeAttenuation:false,transparent:true,opacity:.7})));
 const galaxy=createGalaxy(T);scene.add(galaxy);
 const solRig=new T.Group();solRig.name='CINEMATIC_SOL88_PAYLOAD';solRig.add(sol);scene.add(solRig);const mixer=new T.AnimationMixer(sol),actions=new Map(solClips.map(c=>[c.name,mixer.clipAction(c)]));let active;
 mirror.updateMatrixWorld(true);const pitch=mirror.getObjectByName('MIRROR_PITCH'),parts=[];pitch.traverse(o=>{if(!o.isMesh)return;const g=o.geometry.clone();g.applyMatrix4(new T.Matrix4().copy(pitch.matrixWorld).invert().multiply(o.matrixWorld));parts.push({geometry:g,material:o.material.clone()});});const mirrorInstances=parts.map(({geometry,material})=>{const mesh=new T.InstancedMesh(geometry,material,MIRROR_COUNT);mesh.name='CINEMATIC_HEL01_'+material.name;mesh.instanceMatrix.setUsage(T.DynamicDrawUsage);mesh.frustumCulled=false;scene.add(mesh);return mesh;});const dockMirror=new T.Group();for(const p of parts)dockMirror.add(new T.Mesh(p.geometry,p.material));site.add(dockMirror);
 const paths=new T.Group();paths.name='CINEMATIC_ORBIT_GUIDES';for(let ring=0;ring<3;ring++){const points=Array.from({length:129},(_,i)=>{const angle=i/128*Math.PI*2,r=310+ring*26,tilt=[-.8,.15,.95][ring];return new T.Vector3(Math.cos(angle)*r*Math.cos(tilt),CENTER[1]+Math.sin(angle)*r,Math.cos(angle)*r*Math.sin(tilt));});const g=new T.BufferGeometry().setFromPoints(points);paths.add(new T.Line(g,new T.LineBasicMaterial({color:0x507b94,transparent:true,opacity:.15,depthWrite:false})));}scene.add(paths);
 const trailGeometry=new T.BufferGeometry();trailGeometry.setAttribute('position',new T.BufferAttribute(new Float32Array(MIRROR_COUNT*6),3));const trails=new T.LineSegments(trailGeometry,new T.LineBasicMaterial({color:0x94ecff,transparent:true,opacity:.65}));trails.frustumCulled=false;scene.add(trails);
 const beam=new T.Group();for(const [radius,opacity] of [[.18,1],[.72,.18],[1.5,.045]])beam.add(new T.Mesh(new T.CylinderGeometry(radius,radius,1,16,1,true),new T.MeshBasicMaterial({color:0x8deeff,transparent:true,opacity,blending:T.AdditiveBlending,depthWrite:false})));scene.add(beam);
 const impact=new T.Mesh(new T.SphereGeometry(1.7,20,12),new T.MeshBasicMaterial({color:0xc2fbff,transparent:true,blending:T.AdditiveBlending,depthWrite:false}));scene.add(impact);const dummy=new T.Object3D();
 function update(seconds){const state=cinematicState(seconds),t=state.time;applyLaunch(T,launcher,null,state.arcTime,1);planet.rotation.y=state.planetAngle;site.rotation.y=state.planetAngle;solRig.visible=state.solVisible;solRig.position.fromArray(state.solPosition);solRig.scale.setScalar(state.solScale);const alignment=new T.Quaternion().setFromUnitVectors(new T.Vector3(0,-1,0),center.clone().sub(solRig.position).normalize());solRig.quaternion.setFromEuler(new T.Euler(state.launch.payload.pitch,state.planetAngle,0));solRig.quaternion.slerp(alignment,Math.max(0,Math.min(1,(t-17)/6)));
 if(active!==state.clip){mixer.stopAllAction();active=state.clip;actions.get(active).reset().setLoop(T.LoopOnce,1).play();actions.get(active).clampWhenFinished=true;}actions.get(active).time=state.clipTime;mixer.update(0);solRig.updateMatrixWorld(true);
 beam.visible=impact.visible=state.beam;if(state.beam){const aperture=sol.getObjectByName('APERTURE'),origin=aperture.getWorldPosition(new T.Vector3()),direction=new T.Vector3(0,-1,0).applyQuaternion(aperture.getWorldQuaternion(new T.Quaternion())).normalize(),offset=origin.clone().sub(center),b=offset.dot(direction),disc=b*b-offset.lengthSq()+PLANET_RADIUS**2,length=disc>0?-b-Math.sqrt(disc):150;beam.position.copy(origin).addScaledVector(direction,length/2);beam.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),direction);beam.scale.set(1,length,1);beam.children.forEach((o,i)=>o.material.opacity=[1,.18,.045][i]*state.beamPower);impact.position.copy(origin).addScaledVector(direction,length);impact.scale.setScalar(.8+Math.sin(t*19)*.08);impact.material.opacity=state.beamPower;}
 paths.visible=t>=55;const before=cinematicState(Math.max(0,t-.14)),array=trailGeometry.attributes.position.array;state.mirrors.forEach((m,i)=>{dummy.position.fromArray(m.position);dummy.quaternion.setFromUnitVectors(new T.Vector3(0,0,1),new T.Vector3(1,.55,1).normalize());dummy.rotateZ(i*.41+t*.025);dummy.scale.setScalar(m.visible?m.scale:0);dummy.updateMatrix();mirrorInstances.forEach(mesh=>mesh.setMatrixAt(i,dummy.matrix));const previous=before.mirrors[i];array.set(m.launching?previous.position:m.position,i*6);array.set(m.position,i*6+3);});mirrorInstances.forEach(mesh=>mesh.instanceMatrix.needsUpdate=true);trailGeometry.attributes.position.needsUpdate=true;
 dockMirror.visible=t>=51&&t<83; if(dockMirror.visible){const cycle=((Math.max(0,t-52))%.65),localTime=cycle<.22?cycle/.22*8:cycle<.4?8+(cycle-.22)/.18*.4:8.4+(cycle-.4)/.25*21.6,s=applyLaunch(T,launcher,null,localTime,1);dockMirror.visible=cycle<.4;dockMirror.position.fromArray(s.payload.position);dockMirror.position.add(new T.Vector3(0,.43,0).applyAxisAngle(new T.Vector3(1,0,0),s.payload.pitch));dockMirror.rotation.set(s.payload.pitch+Math.PI/2,0,0);dockMirror.scale.setScalar(.2);}
 return state;}
 update(0);return {scene,update,planet,atmosphere,galaxy,site,launcher,sol,solRig,mixer,mirrorInstances,beam,impact,paths,trails};
}
