// Deterministic presentation choreography. Units/scales are cinematic, not orbital physics.
import {launchState,extensionPose} from '../assets/orbital-launcher/runtime.js';
export const DURATION=100,PLANET_RADIUS=140,MIRROR_COUNT=48;
export const CHAPTERS=[{time:0,label:'01 · ARC-01 launch'},{time:16,label:'02 · Small world'},{time:27,label:'03 · SOL-88 revealed'},{time:35,label:'04 · Laser test'},{time:52,label:'05 · HEL-01 launches'},{time:83,label:'06 · Orbital constellation'}];
export const clamp=x=>Math.max(0,Math.min(1,x));export const smooth=(t,a,b)=>{const u=clamp((t-a)/(b-a));return u*u*(3-2*u);};const mix=(a,b,u)=>a.map((v,i)=>v+(b[i]-v)*u);
export const CENTER=[0,-PLANET_RADIUS,0];
export function orbitPosition(angle,radius=285,tilt=.52){return [Math.sin(angle)*radius,CENTER[1]+Math.cos(angle)*radius*Math.cos(tilt),Math.cos(angle)*radius*Math.sin(tilt)];}
export function mirrorOrbit(i,t){const ring=i%3,slot=Math.floor(i/3),angle=slot/16*Math.PI*2+(t-52)*(.011+ring*.002),r=235+ring*24,tilt=[-.8,.15,.95][ring],p=[Math.cos(angle)*r,Math.sin(angle)*r,0];return [p[0]*Math.cos(tilt),CENTER[1]+p[1],p[0]*Math.sin(tilt)];}
export function flightPosition(start,end,u){const a=start.map((v,i)=>v-CENTER[i]),b=end.map((v,i)=>v-CENTER[i]),ra=Math.hypot(...a),rb=Math.hypot(...b),na=a.map(v=>v/ra),nb=b.map(v=>v/rb),dot=Math.max(-1,Math.min(1,na.reduce((s,v,i)=>s+v*nb[i],0))),angle=Math.acos(dot);let direction;if(angle<.001)direction=na;else if(dot<-.995){const tangent=[na[1],-na[0],0],n=Math.hypot(...tangent)||1;direction=na.map((v,i)=>v*Math.cos(Math.PI*u)+tangent[i]/n*Math.sin(Math.PI*u));}else direction=na.map((v,i)=>(v*Math.sin((1-u)*angle)+nb[i]*Math.sin(u*angle))/Math.sin(angle));const radius=ra+(rb-ra)*u+Math.sin(u*Math.PI)*45;return direction.map((v,i)=>CENTER[i]+v*radius);}
export function cinematicState(seconds){if(!Number.isFinite(seconds))throw Error('Time must be finite');const t=Math.max(0,Math.min(DURATION,seconds)),arcTime=t<6?t/6*8:t<6.8?8+(t-6)/.8*.4:8.4+(t-6.8),launch=launchState(Math.min(30,arcTime)),exit=extensionPose(0),u=smooth(t,6.8,23),dest=orbitPosition(.34+(Math.max(23,t)-23)*.009),start=exit.position.map((v,i)=>v+(i===1?.43*Math.cos(exit.pitch):i===2?.43*Math.sin(exit.pitch):0));let solPosition=t<6.8?launch.payload.position.map((v,i)=>v+(i===1?.43*Math.cos(launch.payload.pitch):i===2?.43*Math.sin(launch.payload.pitch):0)):mix(start,dest,u);
// A convex arc raises the payload above the surface before it approaches orbit.
if(t>=6.8&&t<23)solPosition[1]+=Math.sin(u*Math.PI)*45;
let clip='Idle_Cycle',clipTime=t%24;if(t>=30&&t<34){clip='Convergence';clipTime=t-30;}else if(t>=34&&t<44){clip='Firing_Cycle';clipTime=t-34;}else if(t>=44&&t<49){clip='Recovery';clipTime=t-44;}
const mirrors=Array.from({length:MIRROR_COUNT},(_,i)=>{const launchAt=52.4+i*.65,flight=clamp((t-launchAt)/5),visible=t>=launchAt;const end=mirrorOrbit(i,t),f=smooth(flight,0,1),p=flightPosition(start,end,f);return {index:i,visible,deployed:flight>=1,flight,position:p,scale:.2+smooth(flight,0,1)*3.8};});
const deployed=mirrors.filter(m=>m.deployed).length,inFlight=mirrors.filter(m=>m.visible&&!m.deployed).length;
let camera=[62,38,70],target=[0,10,0];
if(t<7){const k=smooth(t,0,7);camera=mix(camera,[48,30,53],k);target=mix(target,[0,14,7],k);}else if(t<24){const k=smooth(t,7,24);camera=mix([48,30,53],[350,200,490],k);target=mix([0,14,7],CENTER,k);}else if(t<30){const k=smooth(t,24,30),close=solPosition.map((v,i)=>v+[57,22,74][i]);camera=mix([350,200,490],close,k);target=mix(CENTER,solPosition,k);}else if(t<45){camera=solPosition.map((v,i)=>v+[57,22,74][i]);target=[...solPosition];if(t>=36){const k=smooth(t,36,41);camera=mix(camera,[230,140,360],k);target=mix(solPosition,mix(solPosition,CENTER,.38),k);}}else if(t<53){const k=smooth(t,45,53);camera=mix([230,140,360],[68,42,75],k);target=mix(mix(solPosition,CENTER,.38),[0,16,0],k);}else{const k=smooth(t,55,86);camera=mix([68,42,75],[500,280,680],k);target=mix([0,16,0],CENTER,k);if(t>86){const a=(t-86)*.016,x=camera[0],z=camera[2];camera[0]=x*Math.cos(a)+z*Math.sin(a);camera[2]=-x*Math.sin(a)+z*Math.cos(a);}}
const phase=t<6?'ARC-01 · charge and load':t<7?'Launch / SOL-88 payload':t<24?'Leaving the surface':t<30?'SOL-88 / Syzygy':t<34?'Cages converging':t<44?'SOL-88 / ten-second laser test':t<49?'Optics closed / thermal recovery':t<57?'HEL-01 / first mirror launches':t<88?'Building the orbital constellation':'48 HEL-01 mirrors / deployment complete';
return {time:t,arcTime:Math.min(30,arcTime),launch,solPosition,solScale:.045+u*.755,solOrbit:t>=23,clip,clipTime,beam:t>=34&&t<44,beamPower:smooth(t,34,34.5)*(1-smooth(t,43.5,44)),mirrors,deployed,inFlight,camera,target,phase,chapter:CHAPTERS.filter(c=>c.time<=t).at(-1)};
}
