import * as T from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {createCinematic} from './scene.js?v=sol-tracking-3';
import {DURATION,CHAPTERS} from './timeline.js?v=sol-tracking-3';
const $=id=>document.getElementById(id),stage=$('stage'),renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;stage.prepend(renderer.domElement);const camera=new T.PerspectiveCamera(42,1,.1,4000),controls=new OrbitControls(camera,renderer.domElement);controls.enabled=false;controls.minDistance=3;controls.maxDistance=1600;const loader=new GLTFLoader();let world,time=0,playing=false,last=performance.now(),ready=false,generation=0,w=0,h=0;
const clock=s=>String(Math.floor(s/60)).padStart(2,'0')+':'+String(Math.floor(s%60)).padStart(2,'0');
for(const chapter of CHAPTERS)$('chapter').add(new Option(chapter.label,chapter.time));
function resize(){if(stage.clientWidth&&stage.clientHeight&&(w!==stage.clientWidth||h!==stage.clientHeight)){w=stage.clientWidth;h=stage.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();}}
function paint(){if(!ready)return;resize();renderer.render(world.scene,camera);}
function update(){if(!ready)return;const state=world.update(time);if(!$('freeCamera').checked){camera.position.fromArray(state.camera);controls.target.fromArray(state.target);if(camera.aspect<1)camera.position.sub(controls.target).multiplyScalar(1/Math.sqrt(camera.aspect)).add(controls.target);camera.lookAt(controls.target);}$('timeline').value=time;$('time').textContent=clock(time)+' / '+clock(DURATION);$('chapter').value=state.chapter.time;$('chapterTitle').textContent=state.chapter.label.toUpperCase();$('phase').textContent=state.phase;$('count').textContent='HEL-01 IN ORBIT / '+String(state.deployed).padStart(2,'0');$('flight').textContent=time<52?'PAYLOAD / SOL-88 SYZYGY':'IN TRANSIT / '+String(state.inFlight).padStart(2,'0');paint();}
function play(value){if(!ready)return;playing=value;last=performance.now();$('play').textContent=value?'Pause':'Play cinematic';}
function seek(t){play(false);time=Math.max(0,Math.min(DURATION,t));update();}
async function load(){const ticket=++generation;playing=false;ready=false;$('loading').hidden=false;$('retry').hidden=true;$('status').textContent='Loading ARC-01, SOL-88 and HEL-01…';try{const specs=[['orbital-launcher',e=>e.family==='launcher'&&e.lod===0],['sol88',e=>e.lod===0],['settlement-industry',e=>e.family==='mirror'&&e.lod===1]],loaded=await Promise.all(specs.map(async([folder,choose])=>{const response=await fetch('../assets/'+folder+'/manifest.json');if(!response.ok)throw Error(folder+' manifest unavailable');const manifest=await response.json(),entry=manifest.assets.find(choose);if(!entry)throw Error(folder+' model missing');return {entry,gltf:await loader.loadAsync('../assets/'+folder+'/'+entry.file+'?v='+entry.sha256.slice(0,12))};}));if(ticket!==generation)return;world=createCinematic(T,{launcher:loaded[0].gltf.scene,sol:loaded[1].gltf.scene,solClips:loaded[1].gltf.animations,mirror:loaded[2].gltf.scene});const room=new RoomEnvironment(),pmrem=new T.PMREMGenerator(renderer);world.scene.environment=pmrem.fromScene(room,.05).texture;room.dispose();pmrem.dispose();const sunlight=new T.DirectionalLight(0xffe7c0,3.3);sunlight.position.set(300,260,400);world.scene.add(sunlight);world.scene.add(new T.HemisphereLight(0xa6d9ff,0x111727,1.1));const rim=new T.DirectionalLight(0x66a9ff,.75);rim.position.set(-300,30,-200);world.scene.add(rim);ready=true;time=0;resize();update();$('loading').hidden=true;for(const id of ['play','restart','timeline','chapter'])$(id).disabled=false;$('stats').textContent='Detailed ARC-01 + SOL-88 · instanced HEL-01';window.orbitalCinematic={get world(){return world;},get time(){return time;},get playing(){return playing;},seek,play,camera,renderer,update};}catch(e){if(ticket===generation){$('status').textContent='Could not load the cinematic: '+e.message;$('retry').hidden=false;}}}
$('play').onclick=()=>{if(time>=DURATION)time=0;play(!playing);update();};$('restart').onclick=()=>seek(0);$('timeline').oninput=()=>seek(Number($('timeline').value));$('chapter').onchange=()=>seek(Number($('chapter').value));$('freeCamera').onchange=()=>{controls.enabled=$('freeCamera').checked;update();};controls.addEventListener('change',paint);$('retry').onclick=load;$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if(stage.requestFullscreen)await stage.requestFullscreen();else $('note').textContent='Fullscreen is unavailable in this browser.';}catch(e){$('note').textContent=e.message;}};
new ResizeObserver(()=>{resize();update();}).observe(stage);document.addEventListener('visibilitychange',()=>{if(document.hidden)play(false);});document.addEventListener('keydown',e=>{if(e.code==='Space'&&!['INPUT','SELECT','BUTTON','TEXTAREA'].includes(document.activeElement?.tagName)){e.preventDefault();$('play').onclick();}});renderer.setAnimationLoop(now=>{const dt=Math.max(0,Math.min(.1,(now-last)/1000));last=now;if(playing&&ready){time=Math.min(DURATION,time+dt*Number($('speed').value));update();if(time>=DURATION)play(false);}if(controls.enabled)controls.update();paint();});
await load();
