import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {MeshoptDecoder} from 'three/addons/libs/meshopt_decoder.module.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {applyWrite} from '../assets/chip-manufacturing/runtime.js';
const $=id=>document.getElementById(id),stage=$('stage'),base='../assets/chip-manufacturing/';
const scene=new T.Scene();scene.background=new T.Color(0x233943);
const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.4;stage.prepend(renderer.domElement);
const env=new RoomEnvironment(),pm=new T.PMREMGenerator(renderer);scene.environment=pm.fromScene(env).texture;env.dispose();pm.dispose();
scene.add(new T.HemisphereLight(0xe2f7ff,0x3d515a,2));const key=new T.DirectionalLight(0xffe6cc,3);key.position.set(3,10,6);scene.add(key);
const ground=new T.GridHelper(30,30,0x57727a,0x344f59);ground.position.y=-.02;scene.add(ground);
const camera=new T.PerspectiveCamera(40,1,.05,100),controls=new OrbitControls(camera,renderer.domElement);controls.maxPolarAngle=Math.PI*.49;controls.minDistance=2;controls.maxDistance=35;
let root,manifest,lod=1,time=3,playing=false,generation=0,last=performance.now(),width=0,height=0;
function paint(){const w=stage.clientWidth,h=stage.clientHeight;if(!w||!h)return;if(w!==width||h!==height){width=w;height=h;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();}renderer.render(scene,camera);}
function frame(kind){controls.target.set(kind==='optics'?.2:0,kind==='optics'?2.7:1.3,0);camera.position.set(...(kind==='top'?[0,16,.01]:kind==='optics'?[7,8,9]:[10,9,12]));controls.update();paint();}
function update(){if(!root)return;const s=applyWrite(root,time,lod,$('beam').checked);$('phase').textContent=s.phase+' · '+time.toFixed(1)+' s';$('time').value=time;paint();}
function dispose(r){r.traverse(o=>{if(o.isMesh){o.geometry.dispose();o.material.dispose();}});}
async function load(){const token=++generation,next=Number($('lod').value);playing=false;$('play').textContent='Play';$('status').textContent='Loading…';try{if(!manifest){const r=await fetch(base+'manifest.json');if(!r.ok)throw Error('Manifest HTTP '+r.status);manifest=await r.json();}const e=manifest.assets.find(e=>e.lod===next),file=$('encoding').value==='meshopt'?e.meshopt_file:e.file;const gltf=await new GLTFLoader().setMeshoptDecoder(MeshoptDecoder).loadAsync(base+file);if(token!==generation){dispose(gltf.scene);return;}if(root){scene.remove(root);dispose(root);}root=gltf.scene;scene.add(root);lod=next;root.traverse(o=>{if(o.isMesh)o.material.wireframe=$('wire').checked;});$('play').disabled=$('time').disabled=$('beam').disabled=lod===2;$('stats').textContent=e.triangles.toLocaleString()+' triangles · '+e.draw_calls+' draws · '+e.bytes.toLocaleString()+' plain bytes';$('download').href=base+file;$('status').textContent='D0 / '+(lod===2?'Static distance':'Articulated inspection')+' · Game review pending';update();window.chipWriter={get root(){return root;},renderer,scene,camera};}catch(e){if(token===generation)$('status').textContent='Load failed: '+e.message+' · Change tier or encoding to retry.';}}
$('lod').onchange=load;$('encoding').onchange=load;$('beam').onchange=update;$('time').oninput=()=>{playing=false;$('play').textContent='Play';time=Number($('time').value);update();};$('play').onclick=()=>{playing=!playing;last=performance.now();$('play').textContent=playing?'Pause':'Play';};$('reset').onclick=()=>{playing=false;$('play').textContent='Play';time=0;update();};$('wire').onchange=()=>{root?.traverse(o=>{if(o.isMesh)o.material.wireframe=$('wire').checked;});paint();};document.querySelectorAll('[data-camera]').forEach(b=>b.onclick=()=>frame(b.dataset.camera));controls.addEventListener('change',paint);new ResizeObserver(paint).observe(stage);renderer.setAnimationLoop(now=>{const dt=Math.min(.15,Math.max(0,(now-last)/1000));last=now;if(playing){time=(time+dt)%12;update();}else paint();});frame('site');await load();
