import * as T from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {MeshoptDecoder} from 'three/addons/libs/meshopt_decoder.module.js';

const $=id=>document.getElementById(id),stage=$('stage'),scene=new T.Scene(),camera=new T.PerspectiveCamera(40,1,.1,500),renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0x0c1920);renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;renderer.shadowMap.enabled=true;stage.prepend(renderer.domElement);
const pmrem=new T.PMREMGenerator(renderer),environment=new RoomEnvironment();scene.environment=pmrem.fromScene(environment).texture;environment.dispose();pmrem.dispose();scene.add(new T.HemisphereLight(0xdff7ff,0x263b42,2.2));const sun=new T.DirectionalLight(0xffeed3,3.3);sun.position.set(-18,34,24);sun.castShadow=true;scene.add(sun);const rim=new T.DirectionalLight(0x27d9ff,1.5);rim.position.set(18,10,-18);scene.add(rim);
const floor=new T.Mesh(new T.PlaneGeometry(100,100),new T.MeshStandardMaterial({color:0x20343a,roughness:.94,metalness:.06}));floor.rotation.x=-Math.PI/2;floor.position.y=-.02;floor.receiveShadow=true;scene.add(floor);const grid=new T.GridHelper(80,40,0x4a6970,0x2e464d);grid.position.y=-.01;scene.add(grid);const orbit=new OrbitControls(camera,renderer.domElement);orbit.enableDamping=true;orbit.maxPolarAngle=Math.PI*.49;
const loader=new GLTFLoader().setMeshoptDecoder(MeshoptDecoder);let manifest,model,rocket,mixer,action,entry,clips=[],playing=true,ticket=0,manualSparkVisibility=true;
const size=bytes=>bytes>1048576?(bytes/1048576).toFixed(1)+' MB':(bytes/1024).toFixed(0)+' KB';
function cameraPreset(name='site'){const poses={site:{target:[-2,3,0],eye:[20,12,23]},machine:{target:[3.2,1.35,0],eye:[13,6.5,11]},top:{target:[-2,0,0],eye:[-2,31,.01]}},pose=poses[name];orbit.target.fromArray(pose.target);camera.position.fromArray(pose.eye);orbit.update();}
function dispose(root){if(!root)return;scene.remove(root);const geometries=new Set(),materials=new Set();root.traverse(object=>{if(object.geometry)geometries.add(object.geometry);for(const material of [].concat(object.material||[]))materials.add(material);});geometries.forEach(item=>item.dispose());materials.forEach(item=>item.dispose());}
function phase(time){if(entry?.lod===2)return'Static distance tier: the service-arm, compact foundry and feedstock barrel remain one readable silhouette; motion and sparks are intentionally absent.';if($('clip').value==='Foundry_Process_Cycle')return'The induction chamber pulses while the separator keeps recovered material moving toward standardized feedstock.';if(time<2)return'The reused service arm aligns its cutter with the first removable SH02 panel.';if(time<5.1)return'Blue-white cutter VFX marks the contact point; the rocket remains the material source.';if(time<10)return'The detached panel travels from the rocket into the Seed Foundry input chute.';if(time<15)return'Recovered structure is sorted with local silicate/regolith and carried additives; the barrel fill rises.';return'The first ferroceramic feedstock barrel is sealed and ready for Stålheart.';}
function showTime(time){$('timeline').value=time;$('time').textContent=time.toFixed(1)+' s';$('phase').textContent=phase(time);const sparks=model?.getObjectByName('CUTTER_SPARKS');if(sparks)sparks.visible=manualSparkVisibility;$('badge').textContent=entry?.lod===2?'STATIC DISTANCE / PROCESS SILHOUETTE':time<5.1?'SH02 / CUTTING':time<10?'TRANSFER / SCRAP INPUT':time<15?'PROCESS / FERROCERAMIC':'BARREL READY / STÅLHEART FEED';}
function setTime(time){if(!mixer||!action)return;time=Math.min(action.getClip().duration,Math.max(0,time));mixer.setTime(time);model.updateMatrixWorld(true);showTime(time);}
function setClip(name,start=0){if(!mixer)return;action?.stop();const selected=clips.find(item=>item.name===name);if(!selected)return;action=mixer.clipAction(selected);const loop=selected.name==='Foundry_Process_Cycle';action.setLoop(loop?T.LoopRepeat:T.LoopOnce,loop?Infinity:1);action.clampWhenFinished=!loop;action.play();$('timeline').max=selected.duration;$('timeline').value=Math.min(start,selected.duration);setTime(Math.min(start,selected.duration));}
async function loadContext(lod,serial){dispose(rocket);rocket=null;if(!$('context').checked)return;try{const detailed=lod===0,file=detailed?'../assets/sh-rocket/sh_rocket.glb':'../assets/sh-rocket/sh02_landing_island_d0_lod2.glb',gltf=await loader.loadAsync(file);if(serial!==ticket){dispose(gltf.scene);return;}rocket=gltf.scene;rocket.position.x=-6.8;rocket.userData.context_only=true;scene.add(rocket);}catch(error){console.warn('SH02 context unavailable',error);}}
async function load(){const serial=++ticket;playing=false;$('status').textContent='Loading AFR-01…';entry=manifest.assets.find(item=>item.lod===+$('lod').value);const compressed=$('encoding').value==='meshopt',file=compressed?entry.meshopt_file:entry.file;try{const gltf=await loader.loadAsync('../assets/arrival-foundry/'+file+'?v='+(compressed?entry.meshopt_bytes:entry.bytes));if(serial!==ticket){dispose(gltf.scene);return;}mixer?.stopAllAction();dispose(model);model=gltf.scene;model.traverse(object=>{if(object.isMesh){object.castShadow=true;object.receiveShadow=true;}});scene.add(model);clips=gltf.animations;mixer=new T.AnimationMixer(model);$('clip').replaceChildren(...clips.map(clip=>new Option(clip.name.replaceAll('_',' '),clip.name)));$('motion').hidden=!clips.length;if(clips.length){$('clip').value='Recycle_Panel_To_Barrel';setClip($('clip').value,3);}else{action=null;showTime(0);}$('triangles').textContent=entry.triangles.toLocaleString();$('draws').textContent=entry.draw_calls.toLocaleString();$('plainBytes').textContent=size(entry.bytes);$('meshoptBytes').textContent=size(entry.meshopt_bytes);$('download').href='../assets/arrival-foundry/'+file;await loadContext(entry.lod,serial);cameraPreset('site');$('status').textContent=`AFR-01 D0 / LOD${entry.lod} ${entry.quality.replaceAll('_',' ')} · ${compressed?'decoded Meshopt':'plain GLB'} · SH02 context excluded from metrics`;playing=!!action;window.arrivalFoundry={model,rocket,mixer,entry,manifest,scene,camera,orbit,setTime};window.arrivalFoundryReady=true;}catch(error){$('status').textContent='Unable to load: '+error.message;console.error(error);}}
$('lod').onchange=load;$('encoding').onchange=load;$('clip').onchange=()=>{setClip($('clip').value,0);playing=true;};$('timeline').oninput=()=>{playing=false;setTime(+$('timeline').value);};$('play').onclick=()=>{if(!action)return;if(action.time>=action.getClip().duration-.01)setTime(0);playing=true;};$('pause').onclick=()=>playing=false;for(const button of document.querySelectorAll('[data-time]'))button.onclick=()=>{if(!action)return;playing=false;setTime(Math.min(+button.dataset.time,action.getClip().duration));};$('context').onchange=()=>loadContext(entry.lod,ticket);$('sparks').onchange=()=>{manualSparkVisibility=$('sparks').checked;showTime(action?.time||0);};for(const button of document.querySelectorAll('[data-camera]'))button.onclick=()=>cameraPreset(button.dataset.camera);
new ResizeObserver(()=>{renderer.setSize(stage.clientWidth,stage.clientHeight);camera.aspect=stage.clientWidth/stage.clientHeight;camera.updateProjectionMatrix();}).observe(stage);const clock=new T.Clock();renderer.setAnimationLoop(()=>{const dt=Math.min(clock.getDelta(),.05);if(playing&&mixer&&action){mixer.update(dt);showTime(action.time);if(action.loop===T.LoopOnce&&action.time>=action.getClip().duration-.001)playing=false;}orbit.update();renderer.render(scene,camera);});
try{const response=await fetch('../assets/arrival-foundry/manifest.json',{cache:'no-cache'});if(!response.ok)throw Error('Manifest unavailable');manifest=await response.json();await load();}catch(error){$('status').textContent=error.message;console.error(error);}
