import * as T from 'three';import {OrbitControls} from 'three/addons/controls/OrbitControls.js';import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';import {MeshoptDecoder} from 'three/addons/libs/meshopt_decoder.module.js';import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';import {DecalGeometry} from 'three/addons/geometries/DecalGeometry.js';import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';import {createAppearance,browserTexture,validateAppearance} from '../../assets/hover-tank/customization/runtime.js';
const $=id=>document.getElementById(id),base='../../assets/hover-tank/customization/',stage=$('stage'),scene=new T.Scene();scene.background=new T.Color(0x18212e);
const renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;stage.prepend(renderer.domElement);const env=new RoomEnvironment(),pm=new T.PMREMGenerator(renderer);scene.environment=pm.fromScene(env,.06).texture;env.dispose();pm.dispose();scene.add(new T.HemisphereLight(0xe0ebff,0x425067,2));const light=new T.DirectionalLight(0xffeddd,3);light.position.set(4,10,7);scene.add(light);const grid=new T.GridHelper(80,80,0x586378,0x29374a);grid.position.y=-.04;scene.add(grid);
const camera=new T.PerspectiveCamera(39,1,.03,180),orbit=new OrbitControls(camera,renderer.domElement);orbit.maxPolarAngle=Math.PI*.49;orbit.minDistance=3;orbit.maxDistance=65;const loader=new GLTFLoader().setMeshoptDecoder(MeshoptDecoder);
let manifest,presets={},recipe,equipped,current,reference,serial=0,revision=0,history=[],powered=false,shells=27,shot=-1,width=0,height=0,storage={},saving=false;
const copy=x=>JSON.parse(JSON.stringify(x)),STORE='mork-liveries-v1';
function notice(s){$('notice').textContent=s;}
function paint(){const w=stage.clientWidth,h=stage.clientHeight;if(w&&h&&(w!==width||h!==height)){width=w;height=h;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();}renderer.render(scene,camera);}
function frame(kind='perspective'){paint();const box=current?new T.Box3().setFromObject(current.root):new T.Box3(new T.Vector3(-3,0,-5),new T.Vector3(3,3,9));if(reference)box.union(new T.Box3().setFromObject(reference.root));const center=box.getCenter(new T.Vector3()),direction=new T.Vector3(...(kind==='front'?[0,.14,1]:kind==='side'?[1,.22,0]:kind==='top'?[0,1,.001]:[1,.66,1.3])).normalize(),right=new T.Vector3().crossVectors(new T.Vector3(0,1,0),direction).normalize(),up=new T.Vector3().crossVectors(direction,right),tan=Math.tan(T.MathUtils.degToRad(camera.fov/2));let distance=0;for(const item of [current,reference]){if(!item)continue;item.root.updateMatrixWorld(true);item.root.traverse(o=>{if(!o.isMesh)return;const p=o.geometry.attributes.position;for(let i=0;i<p.count;i++){const v=new T.Vector3().fromBufferAttribute(p,i).applyMatrix4(o.matrixWorld).sub(center);distance=Math.max(distance,Math.abs(v.dot(right))/(tan*camera.aspect)+v.dot(direction),Math.abs(v.dot(up))/tan+v.dot(direction));}});}orbit.target.copy(center);camera.position.copy(center).addScaledVector(direction,distance*1.12);orbit.update();paint();}
function form(){for(const role of ['primary','secondary','accent'])$(role).value=recipe.paint[role];for(const id of ['pattern','finish','name','number','message','label'])$(id).value=recipe[id];zoneForm();$('title').textContent=recipe.label;$('subtitle').textContent=recipe.name+' / '+recipe.number;}
function zoneForm(){const d=recipe.decals.find(d=>d.zone===$('zone').value);for(const k of ['symbol','scale','rotation'])$(k).value=d[k];}
function stats(){if(!current)return;let triangles=0,draws=0;current.root.traverse(o=>{if(o.isMesh){triangles+=(o.geometry.index?.count||o.geometry.attributes.position.count)/3;draws+=o.geometry.groups.length||1;}});$('stats').textContent=Math.round(triangles).toLocaleString()+' triangles · '+draws+' mesh draws\n'+current.entry.bytes.toLocaleString()+' base GLB bytes · '+current.ctx.decalMeshes.length+' decal batches';}
function pose(){if(!current)return;const r=current.root,active=current.entry.lod<2&&current.entry.damage_level<2;for(const id of ['yaw','elevation','power','fire','reload'])$(id).disabled=!active;if(active){r.getObjectByName('HOVER_RIG').position.y=powered?.55:0;r.getObjectByName('TURRET_YAW').rotation.y=T.MathUtils.degToRad(Number($('yaw').value));r.getObjectByName('GUN_PITCH').rotation.x=-T.MathUtils.degToRad(Number($('elevation').value));r.traverse(o=>{if(o.name.startsWith('LIFT_EMITTER_'))o.scale.setScalar(powered?1:.001);});}for(let i=0;i<9;i++){const n=r.getObjectByName('AMMO_PORT_LIGHT_'+String(i).padStart(2,'0'));n?.traverse(o=>{if(!o.isMesh||current.entry.lod===2)return;if(!o.userData.independentAmmo){o.material=o.material.clone();o.userData.independentAmmo=true;}const amount=active?Math.max(0,Math.min(3,shells-i*3)):0,color=[0x080c10,0xff4538,0xffb52e,0x35eaff][amount];o.material.color.setHex(color);o.material.emissive.setHex(amount?color:0);});}$('ammo').textContent=(active?shells:0)+' / 27';$('power').textContent=powered?'Power off':'Power on';$('fire').disabled=!active||!powered||shells===0;}
function wire(){for(const item of [current,reference])item?.root.traverse(o=>{if(o.isMesh)o.material.wireframe=$('wire').checked;});}
async function apply(){if(!current)return;const rev=++revision,item=current;try{await item.ctx.apply(recipe);if(rev!==revision||item!==current)return;form();pose();wire();stats();paint();$('status').textContent=recipe.label+' · '+(item.entry.lod===2?'Static D0 / colors only':'D'+item.entry.damage_level+' / paint + supported markings')+' · Game review pending';}catch(e){notice(e.message);}}
function dispose(item){if(!item)return;item.ctx.dispose();const geo=new Set(),mats=new Set();item.root.traverse(o=>{if(o.isMesh){geo.add(o.geometry);mats.add(o.material);}});geo.forEach(g=>g.dispose());mats.forEach(m=>m.dispose());scene.remove(item.root);}
async function make(entry){const file=$('encoding').value==='meshopt'?entry.meshopt_file:entry.file,g=await loader.loadAsync(base+file+'?v='+entry.sha256.slice(0,12)),ctx=createAppearance(T,g.scene,{lod:entry.lod,damage:entry.damage_level,DecalGeometry,mergeGeometries,textureFactory:(svg,opts)=>browserTexture(T,svg,opts)});return {root:g.scene,ctx,entry};}
async function load(){const token=++serial;++revision;shot=-1;$('status').textContent='Loading MÖRK…';const lod=Number($('lod').value);if(lod===2)$('damage').value='0';$('damage').disabled=lod===2;const entry=manifest.assets.find(e=>e.lod===lod&&e.damage_level===Number($('damage').value));let next,ref;try{next=await make(entry);if($('compare').checked){ref=await make(entry);await ref.ctx.apply(presets.factory);}if(token!==serial){dispose(next);dispose(ref);return;}dispose(current);dispose(reference);current=next;reference=ref;scene.add(current.root);current.root.position.x=ref?-6.3:0;if(ref){ref.root.position.x=6.3;scene.add(ref.root);}await apply();frame();}catch(e){dispose(next);dispose(ref);if(token===serial)notice('Load failed: '+e.message);}}
function push(){history.push(copy(recipe));if(history.length>30)history.shift();}
function edit(){push();recipe.preset_id='custom';for(const role of ['primary','secondary','accent'])recipe.paint[role]=$(role).value;for(const id of ['pattern','finish','name','number','message','label'])recipe[id]=$(id).value;const d=recipe.decals.find(d=>d.zone===$('zone').value);d.symbol=$('symbol').value;d.scale=Number($('scale').value);d.rotation=Number($('rotation').value);recipe=validateAppearance(recipe);void apply();}
function savedOptions(){const old=$('saved').value;$('saved').replaceChildren(new Option('Choose a saved design…',''),...Object.entries(storage.designs||{}).map(([id,r])=>new Option(r.label,id)));$('saved').value=old;}
function saveStorage(){localStorage.setItem(STORE,JSON.stringify(storage));}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('preset').onchange=()=>{push();recipe=copy(presets[$('preset').value]);form();void apply();};for(const id of ['primary','secondary','accent','pattern','finish','name','number','message','label','symbol','scale','rotation'])$(id).onchange=edit;$('zone').onchange=zoneForm;
$('undo').onclick=()=>{if(history.length){recipe=history.pop();form();void apply();}};$('factory').onclick=()=>{push();recipe=copy(presets.factory);form();void apply();};$('cancel').onclick=()=>{push();recipe=copy(equipped);form();void apply();notice('Restored equipped appearance.');};$('save').onclick=()=>{try{const next=validateAppearance(recipe),key=next.label.trim()||'Custom livery',updated={...storage,designs:{...storage.designs,[key]:next},equipped:next};localStorage.setItem(STORE,JSON.stringify(updated));storage=updated;equipped=copy(next);savedOptions();notice('Saved and equipped locally. Export JSON to share.');}catch(e){notice('Could not save: '+e.message);}};$('saved').onchange=()=>{const r=storage.designs?.[$('saved').value];if(r){push();recipe=validateAppearance(r);form();void apply();}};
$('export').onclick=()=>download(new Blob([JSON.stringify(validateAppearance(recipe),null,2)+'\n'],{type:'application/json'}),'mork-'+recipe.name.toLowerCase().replaceAll(' ','-')+'.json');$('import').onclick=()=>$('importFile').click();$('importFile').onchange=async()=>{try{const file=$('importFile').files[0];if(!file)return;if(file.size>32768)throw Error('Recipe exceeds 32 KB');const next=validateAppearance(JSON.parse(await file.text()));push();recipe=next;form();await apply();notice('Recipe imported. Apply & save to keep it.');}catch(e){notice('Import rejected: '+e.message);}finally{$('importFile').value='';}};$('snapshot').onclick=()=>{paint();renderer.domElement.toBlob(b=>{if(b)download(b,'mork-livery.png');},'image/png');};
for(const id of ['lod','damage','encoding','compare'])$(id).onchange=load;$('wire').onchange=()=>{wire();paint();};for(const id of ['yaw','elevation'])$(id).oninput=()=>{pose();paint();};$('power').onclick=()=>{powered=!powered;pose();paint();};$('fire').onclick=()=>{if(!powered||shells<=0||current.entry.damage_level>1)return;shells--;shot=0;pose();};$('reload').onclick=()=>{shells=27;pose();paint();};document.querySelectorAll('[data-camera]').forEach(b=>b.onclick=()=>frame(b.dataset.camera));orbit.addEventListener('change',paint);new ResizeObserver(paint).observe(stage);let last=performance.now();renderer.setAnimationLoop(now=>{const dt=Math.min(.1,(now-last)/1000);last=now;if(shot>=0&&current){shot+=dt;const recoil=current.root.getObjectByName('GUN_RECOIL');if(recoil)recoil.position.z=-.82*(shot<.08?shot/.08:Math.max(0,1-(shot-.08)/1.32));if(shot>=1.4)shot=-1;}paint();});
try{const response=await fetch(base+'manifest.json');if(!response.ok)throw Error('Manifest unavailable');manifest=await response.json();await Promise.all(manifest.presets.map(async id=>{const response=await fetch(base+'presets/'+id+'.json');if(!response.ok)throw Error('Preset unavailable');presets[id]=validateAppearance(await response.json());}));for(const id of manifest.presets)$('preset').add(new Option(presets[id].label,id));try{const data=JSON.parse(localStorage.getItem(STORE)||'{}');storage={designs:Object.create(null)};for(const [id,r] of Object.entries(data.designs||{})){try{storage.designs[id]=validateAppearance(r);}catch{}}if(data.equipped)storage.equipped=validateAppearance(data.equipped);}catch{storage={designs:Object.create(null)};notice('Stored appearance unavailable; using examples.');}equipped=copy(storage.equipped||presets['bunny-overdrive']);recipe=copy(equipped);$('preset').value=recipe.preset_id;form();savedOptions();await load();window.morkCustomization={get current(){return current;},get reference(){return reference;},get recipe(){return copy(recipe);},get shells(){return shells;},apply,load,renderer,scene,camera};}catch(e){notice(e.message);$('status').textContent='Workshop could not load. Reload to retry.';}
