import * as T from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {attachScoreDisplay,normalizeScore,MAX_SCORE} from '../assets/planet-scoreboards/runtime.js';
const $=id=>document.getElementById(id),stage=$('stage'),scene=new T.Scene();scene.background=new T.Color('#14242a');scene.fog=new T.Fog('#14242a',80,190);const camera=new T.PerspectiveCamera(38,1,.05,250),renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(stage.clientWidth,stage.clientHeight);renderer.shadowMap.enabled=true;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.4;stage.prepend(renderer.domElement);const orbit=new OrbitControls(camera,renderer.domElement);orbit.enableDamping=true;orbit.maxPolarAngle=Math.PI*.495;scene.add(new T.HemisphereLight(0xe9f6ff,0x516e69,2.4));const sun=new T.DirectionalLight(0xffedcc,3.4);sun.position.set(-9,16,12);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-20,right:20,top:20,bottom:-20,near:.1,far:50});scene.add(sun);const fill=new T.DirectionalLight(0x7fc9e6,1);fill.position.set(8,7,-8);scene.add(fill);const floor=new T.Mesh(new T.PlaneGeometry(200,200),new T.MeshStandardMaterial({color:0x20343a,roughness:.95}));floor.rotation.x=-Math.PI/2;floor.position.y=-.025;floor.receiveShadow=true;scene.add(floor);const grid=new T.GridHelper(80,80,0x527278,0x30484d);grid.position.y=.001;scene.add(grid);
const loader=new GLTFLoader();let catalog=[],items=[],ticket=0,score=12345678,target=score,counting=false;
function fit(mode='perspective'){if(!items.length)return;const bounds=new T.Box3();items.forEach(i=>bounds.expandByObject(i.group));const sphere=bounds.getBoundingSphere(new T.Sphere());orbit.target.copy(sphere.center);const angle=Math.min(T.MathUtils.degToRad(camera.fov/2),Math.atan(Math.tan(T.MathUtils.degToRad(camera.fov/2))*camera.aspect)),distance=sphere.radius/Math.sin(angle)*1.22;camera.position.copy(sphere.center).add(new T.Vector3(mode==='front'?0:mode==='top'?.05:.55,mode==='front'?.08:mode==='top'?1:.32,mode==='front'?1:mode==='top'?.05:1).normalize().multiplyScalar(distance));orbit.update();}
function dispose(){for(const item of items){item.runtime?.dispose();scene.remove(item.group);const geometries=new Set(),materials=new Set();item.group.traverse(o=>{if(o.geometry)geometries.add(o.geometry);if(o.material)for(const m of [].concat(o.material))materials.add(m);});geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());}items=[];}
function syncScore(value){score=normalizeScore(value);$('score').value=score;$('scoreValue').textContent=score.toLocaleString();for(const item of items)item.runtime?.setScore(score);}
function chooseEntries(){const variant=$('variant').value,lod=+$('tier').value;return catalog.filter(e=>e.lod===lod&&(variant==='all'||e.variant===variant));}
async function load(){const thisTicket=++ticket;window.scoreboardsReady=false;$('status').textContent='Loading scoreboards…';try{const entries=chooseEntries(),results=await Promise.all(entries.map(async entry=>({entry,gltf:await loader.loadAsync('../assets/planet-scoreboards/'+entry.file+'?v='+entry.sha256.slice(0,10))})));if(thisTicket!==ticket)return;dispose();const all=$('variant').value==='all';for(const {entry,gltf} of results){const group=gltf.scene;if(all)group.position.x=({beacon:-8,flipdot:0,splitflap:8})[entry.variant];group.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}});const runtime=entry.lod===2?null:attachScoreDisplay(T,group,entry,score);scene.add(group);items.push({entry,group,runtime});}const first=entries[0];$('triangles').textContent=first.triangles.toLocaleString();$('draws').textContent=first.draw_calls.toLocaleString();$('bytes').textContent=(first.bytes/1000).toFixed(0)+' KB';$('download').href='../assets/planet-scoreboards/'+first.file;$('downloadMeshopt').href='../assets/planet-scoreboards/'+first.meshopt_file;$('download').textContent=all?'Download Beacon plain GLB':'Download plain GLB';$('downloadMeshopt').textContent=all?'Download Beacon Meshopt GLB':'Download optional Meshopt GLB';const frozen=first.lod===2;$('score').disabled=frozen;for(const id of ['plusOne','plusThousand','plusMillion','countUp','maximum','resetScore'])$(id).disabled=frozen;$('scoreNote').textContent=frozen?'LOD2 is a fixed 12,345,678 snapshot. Choose LOD1 or LOD0 to update the score.':'Enter a value or add points. Every live board updates through one instanced digit draw.';$('status').textContent=all?'Three physical scoreboards / '+(['Detailed','Game','Static distance'][first.lod]):first.name+' / '+(['Detailed','Game','Static distance'][first.lod]);fit();window.scoreboards={items,score,scene,camera,orbit};window.scoreboardsReady=true;}catch(error){$('status').textContent='Unable to load scoreboards: '+error.message;console.error(error);}}
$('variant').onchange=load;$('tier').onchange=load;$('score').onchange=()=>{try{syncScore($('score').value);counting=false;}catch(error){$('scoreNote').textContent=error.message;}};for(const [id,increment] of [['plusOne',1],['plusThousand',1000],['plusMillion',1000000]])$(id).onclick=()=>{counting=false;syncScore(score+increment);};$('maximum').onclick=()=>{counting=false;syncScore(MAX_SCORE);};$('resetScore').onclick=()=>{counting=false;syncScore(0);};$('countUp').onclick=()=>{target=Math.min(MAX_SCORE,score+1000000);counting=true;};$('front').onclick=()=>fit('front');$('top').onclick=()=>fit('top');$('fit').onclick=()=>fit();new ResizeObserver(()=>{camera.aspect=stage.clientWidth/stage.clientHeight;camera.updateProjectionMatrix();renderer.setSize(stage.clientWidth,stage.clientHeight);fit();}).observe(stage);const clock=new T.Clock();renderer.setAnimationLoop(()=>{const dt=Math.min(clock.getDelta(),.05);if(counting){const step=Math.max(1,Math.ceil((target-score)*Math.min(1,dt*5)));syncScore(Math.min(target,score+step));if(score>=target)counting=false;}orbit.update();renderer.render(scene,camera);});try{const r=await fetch('../assets/planet-scoreboards/manifest.json',{cache:'no-cache'});if(!r.ok)throw Error('Manifest unavailable');catalog=(await r.json()).assets;await load();}catch(error){$('status').textContent=error.message;console.error(error);}
