import * as T from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {MeshoptDecoder} from 'three/addons/libs/meshopt_decoder.module.js';

const $=id=>document.getElementById(id),stage=$('stage'),scene=new T.Scene();scene.background=new T.Color(0x050c13);scene.fog=new T.FogExp2(0x050c13,.005);
const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;stage.prepend(renderer.domElement);const pmrem=new T.PMREMGenerator(renderer),room=new RoomEnvironment();scene.environment=pmrem.fromScene(room).texture;room.dispose();pmrem.dispose();scene.add(new T.HemisphereLight(0xc6f4ff,0x111820,1.7));const key=new T.DirectionalLight(0xe8f7ff,3.5);key.position.set(-24,38,-32);scene.add(key);const rim=new T.DirectionalLight(0x6478ff,4);rim.position.set(35,8,28);scene.add(rim);const warm=new T.DirectionalLight(0xffa83c,1.5);warm.position.set(-20,5,35);scene.add(warm);
const camera=new T.PerspectiveCamera(42,1,.1,500),orbit=new OrbitControls(camera,renderer.domElement);orbit.enableDamping=true;orbit.minDistance=8;orbit.maxDistance=180;const loader=new GLTFLoader().setMeshoptDecoder(MeshoptDecoder);let manifest,entry,model,mixer,action,clips=[],playing=true,ticket=0,materialDefaults=new Map(),sequence=false;
const params=new URLSearchParams(location.search);for(const id of ['lod','surface','encoding'])if(params.has(id))$(id).value=params.get(id);
const corridor=new T.Mesh(new T.CylinderGeometry(.75,.75,32,24),new T.MeshBasicMaterial({color:0x70eeff,transparent:true,opacity:.15,depthWrite:false}));corridor.name='VIEWER_ONLY_CLEARANCE_GUIDE';corridor.visible=false;scene.add(corridor);
const size=bytes=>bytes>1048576?(bytes/1048576).toFixed(1)+' MB':(bytes/1024).toFixed(0)+' KB';
function dispose(root){if(!root)return;scene.remove(root);const geometries=new Set(),materials=new Set();root.traverse(object=>{if(object.geometry)geometries.add(object.geometry);for(const material of [].concat(object.material||[]))materials.add(material);});geometries.forEach(item=>item.dispose());materials.forEach(item=>item.dispose());}
function cameraPreset(name='orbit'){const poses={orbit:{target:[0,5,0],eye:[48,34,-64]},planet:{target:[0,4,0],eye:[25,-54,-28]},flight:{target:[0,4.5,1],eye:[25,18,-58]},top:{target:[0,5,0],eye:[0,83,.01]},core:{target:[0,3.5,0],eye:[10,-10,-14]}},pose=poses[name];orbit.target.fromArray(pose.target);camera.position.fromArray(pose.eye);orbit.update();}
function applyPresentation(){if(!model)return;const wire=$('surface').value==='wireframe';model.traverse(object=>{if(!object.isMesh)return;for(const material of [].concat(object.material||[])){const defaults=materialDefaults.get(material);material.wireframe=wire;if(wire){material.color.setHex(0x75eaff);material.emissive?.setHex(0x245f78);material.emissiveIntensity=.8;}else if(defaults){material.color.copy(defaults.color);material.emissive?.copy(defaults.emissive);material.emissiveIntensity=defaults.intensity;}}});if(!wire){for(const material of materialDefaults.keys()){if(material.name==='M_Radiator_Glow')material.emissiveIntensity=+$('radiatorGlow').value;if(material.name==='M_Aperture_Glow')material.emissiveIntensity=+$('apertureGlow').value;}}$('badge').textContent=wire?'WIRE TELEMETRY / PLATFORM ACQUIRED':'FULL MATERIAL / CLOSE-ORBIT STUDY';}
function applyEngineControls(){if(!model||entry?.lod===2)return;const yaw=model.getObjectByName('OPTICS_YAW'),pitch=model.getObjectByName('OPTICS_PITCH');if(yaw)yaw.rotation.y=T.MathUtils.degToRad(+$('yaw').value);if(pitch)pitch.rotation.x=T.MathUtils.degToRad(+$('pitch').value);}
function phase(){
  if(entry?.lod===2)return'Static charging silhouette. Switch to Game or Detailed for ring motion and optics.';
  const name=action?.getClip().name,time=action?.time||0;
  if(name==='Convergence')return time<3.2?'Containment cages phase-lock; the iris stays closed until the firing corridor clears.':'Lens carriages advance and the eight iris shutters retract.';
  if(name==='Firing_Cycle')return'Ten-second firing window: the rotating cages maintain a clear polar corridor around the stabilized optics.';
  if(name==='Recovery')return time<.6?'Beam inhibited. The iris seals before the cages leave alignment.':'Field phases separate; radiator sectors reject accumulated heat.';
  if(name==='Aperture_Open')return'Isolated iris preview. An open iris alone does not authorize firing.';
  if(name==='Aperture_Close')return'Eight mechanical shutters close over the optical throat.';
  return'Independent containment cages circulate stored energy. The central optical engine remains stabilized.';
}
function showTime(){const duration=action?.getClip().duration||0;$('timeline').value=Math.min(duration,action?.time||0);$('time').textContent=(action?.time||0).toFixed(2)+' s';$('phase').textContent=phase();}
function setClip(name,start=0,blend=0){if(!mixer)return;const previous=action;if(!blend)action?.stop();const clip=clips.find(item=>item.name===name);if(!clip)return;action=mixer.clipAction(clip);const loop=!sequence&&['Idle_Cycle','Firing_Cycle'].includes(name);action.setLoop(loop?T.LoopRepeat:T.LoopOnce,loop?Infinity:1);action.clampWhenFinished=!loop;action.reset().play();if(blend&&previous&&previous!==action)action.crossFadeFrom(previous,blend,false);$('timeline').max=clip.duration;action.time=Math.min(start,clip.duration);mixer.update(0);showTime();}
async function load(){const serial=++ticket,compressed=$('encoding').value==='meshopt';playing=false;sequence=false;$('status').textContent='Loading SOL-88…';entry=manifest.assets.find(item=>item.lod===+$('lod').value);const file=compressed?entry.meshopt_file:entry.file;try{const gltf=await loader.loadAsync('../assets/sol88/'+file+'?v='+(compressed?entry.meshopt_bytes:entry.bytes));if(serial!==ticket){dispose(gltf.scene);return;}mixer?.stopAllAction();dispose(model);model=gltf.scene;materialDefaults=new Map();model.traverse(object=>{if(!object.isMesh)return;object.frustumCulled=false;const list=[].concat(object.material||[]),clones=list.map(material=>{const clone=material.clone();materialDefaults.set(clone,{color:clone.color.clone(),emissive:clone.emissive?.clone()||new T.Color(),intensity:clone.emissiveIntensity});return clone;});object.material=Array.isArray(object.material)?clones:clones[0];});scene.add(model);clips=gltf.animations;mixer=new T.AnimationMixer(model);$('clip').replaceChildren(...clips.map(clip=>new Option(clip.name.replaceAll('_',' '),clip.name)));$('motion').hidden=!clips.length;if(clips.length){$('clip').value='Idle_Cycle';setClip(params.get('clip')||'Idle_Cycle',0);$('clip').value=action.getClip().name;playing=true;}else{action=null;showTime();}$('triangles').textContent=entry.triangles.toLocaleString();$('draws').textContent=entry.draw_calls.toLocaleString();$('plainBytes').textContent=size(entry.bytes);$('meshoptBytes').textContent=size(entry.meshopt_bytes);$('download').href='../assets/sol88/'+file;for(const id of ['yaw','pitch','radiatorGlow','apertureGlow','runPass','corridor'])$(id).disabled=entry.lod===2;applyPresentation();applyEngineControls();cameraPreset('orbit');$('status').textContent=`SOL-88 D0 / LOD${entry.lod} ${entry.quality.replaceAll('_',' ')} · ${compressed?'decoded Meshopt':'plain GLB'} · 40.2 m reserved motion envelope`;window.sol88={model,mixer,entry,manifest,scene,camera,orbit,renderer,setClip,cameraPreset};window.sol88Ready=true;}catch(error){$('status').textContent='Unable to load: '+error.message;console.error(error);}}
$('lod').onchange=load;$('encoding').onchange=load;$('surface').onchange=applyPresentation;$('clip').onchange=()=>{sequence=false;setClip($('clip').value);playing=true;};$('timeline').oninput=()=>{sequence=false;playing=false;if(action)action.paused=false;mixer?.setTime(+$('timeline').value);applyEngineControls();showTime();};$('play').onclick=()=>{if(!action)return;if(action.time>=action.getClip().duration-.01)setClip(action.getClip().name);else action.paused=false;playing=true;};$('pause').onclick=()=>playing=false;$('runPass').onclick=()=>{if(entry?.lod===2)return;sequence=true;setClip('Convergence',0,.4);$('clip').value='Convergence';playing=true;};for(const id of ['yaw','pitch'])$(id).oninput=applyEngineControls;for(const id of ['radiatorGlow','apertureGlow'])$(id).oninput=applyPresentation;for(const button of document.querySelectorAll('[data-camera]'))button.onclick=()=>cameraPreset(button.dataset.camera);
new ResizeObserver(()=>{renderer.setSize(stage.clientWidth,stage.clientHeight);camera.aspect=stage.clientWidth/stage.clientHeight;camera.updateProjectionMatrix();}).observe(stage);const clock=new T.Clock();renderer.setAnimationLoop(()=>{const dt=Math.min(clock.getDelta(),.05);if(playing&&mixer&&action){mixer.update(dt);if(action.loop===T.LoopOnce&&action.time>=action.getClip().duration-.001){if(sequence){const next={Convergence:'Firing_Cycle',Firing_Cycle:'Recovery',Recovery:'Idle_Cycle'}[action.getClip().name];if(next==='Idle_Cycle')sequence=false;if(next){setClip(next);$('clip').value=next;}else playing=false;}else playing=false;}}applyEngineControls();showTime();if(model){const aperture=model.getObjectByName('APERTURE');model.updateMatrixWorld(true);corridor.visible=$('corridor').checked&&entry.lod<2&&action?.getClip().name==='Firing_Cycle';if(aperture&&corridor.visible){aperture.getWorldQuaternion(corridor.quaternion);corridor.position.copy(new T.Vector3(0,-16,0).applyQuaternion(corridor.quaternion)).add(aperture.getWorldPosition(new T.Vector3()));}}orbit.update();renderer.render(scene,camera);});
try{const response=await fetch('../assets/sol88/manifest.json',{cache:'no-cache'});if(!response.ok)throw Error('SOL-88 manifest unavailable');manifest=await response.json();await load();}catch(error){$('status').textContent=error.message;console.error(error);}
