import {evaluatePowerGrid,solarCapacity,requestTowerFire} from './power-grid.js';
import * as T from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
const $=id=>document.getElementById(id),stage=$('stage');
const scene=new T.Scene();scene.background=new T.Color('#142129');scene.fog=new T.Fog('#142129',90,220);
const camera=new T.PerspectiveCamera(38,1,.05,180),renderer=new T.WebGLRenderer({antialias:true});
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;stage.prepend(renderer.domElement);
const orbit=new OrbitControls(camera,renderer.domElement);orbit.enableDamping=true;orbit.maxPolarAngle=Math.PI*.49;
scene.add(new T.HemisphereLight(0xe5f6ff,0x4f6460,2));const light=new T.DirectionalLight(0xfff4df,3.5);light.position.set(-12,28,15);light.castShadow=true;light.shadow.mapSize.set(2048,2048);Object.assign(light.shadow.camera,{left:-25,right:25,top:25,bottom:-25,near:.1,far:100});light.shadow.bias=-.00015;light.shadow.normalBias=.04;scene.add(light);
const fill=new T.DirectionalLight(0x90c9e4,1);fill.position.set(9,5,-7);scene.add(fill);
const ground=new T.Mesh(new T.PlaneGeometry(600,600),new T.MeshStandardMaterial({color:0x1e3036,roughness:.95}));ground.rotation.x=-Math.PI/2;ground.position.y=-.405;ground.receiveShadow=true;scene.add(ground);
const grid=new T.GridHelper(100,100,0x476267,0x2c434b);grid.position.y=-.397;scene.add(grid);
const neutral=new T.MeshStandardMaterial({color:0xbac5bf,roughness:.7}),loader=new GLTFLoader();
let catalog=[],items=[],towers=[],serial=0,network=[],lineGroup=new T.Group(),pulseGroup=new T.Group(),elapsed=0,shots=0;scene.add(lineGroup,pulseGroup);
const consumerSpecs=[{id:'Needle',file:'needle_t3.glb',position:[-14,0,2],demand:20,sourceId:'solar'},{id:'Plasma',file:'plasma_t3.glb',position:[14,0,2],demand:20,sourceId:'solar'},{id:'Railgun',file:'railgun_t3.glb',position:[0,0,-12],demand:20,sourceId:'solar'}];
const sourcePosition=[0,0,8];const entry=(family,state)=>catalog.find(e=>e.family===family&&e.damage_level===+state);
function clearLines(group){for(const child of [...group.children]){child.geometry?.dispose();child.material?.dispose();group.remove(child);}}
function dispose(item){scene.remove(item.group);const geometries=new Set(),materials=new Set();item.group.traverse(o=>{if(o.geometry)geometries.add(o.geometry);for(const m of [o.userData.original||o.material].flat())if(m&&m!==neutral)materials.add(m);});geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());}
function fit(front=false){const bounds=new T.Box3();for(const i of [...items,...towers]){i.group.updateMatrixWorld(true);i.group.traverse(o=>{if(o.isMesh&&!o.userData.overlay)bounds.union(new T.Box3().setFromObject(o,true));});}if(bounds.isEmpty())return;const sphere=bounds.getBoundingSphere(new T.Sphere());orbit.target.copy(sphere.center);const angle=Math.min(T.MathUtils.degToRad(camera.fov/2),Math.atan(Math.tan(T.MathUtils.degToRad(camera.fov/2))*camera.aspect));camera.position.copy(sphere.center).add(new T.Vector3(front?0:.55,front?.08:.85,front?1:1).normalize().multiplyScalar(sphere.radius/Math.sin(angle)*1.08));camera.far=400;camera.updateProjectionMatrix();orbit.update();}
function appearance(){for(const i of [...items,...towers]){if(i.marks)i.marks.visible=$('sockets').checked;if(i.bounds)i.bounds.visible=$('colliders').checked;i.group.traverse(o=>{if(o.userData.original)o.material=$('clay').checked?neutral:o.userData.original;});}}
async function loadAsset(e,position=[0,0,0]){const gltf=await loader.loadAsync('../assets/solar-power/'+e.file),group=gltf.scene;group.position.fromArray(position);group.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;o.userData.original=o.material;}});const marks=new T.Group(),bounds=new T.Group();for(const s of e.sockets)marks.add(new T.ArrowHelper(new T.Vector3(...s.normal),new T.Vector3(...s.position_m),.7,s.available?0x70eec6:0xf88765,.15,.1));for(const c of e.colliders){const wire=new T.LineSegments(new T.EdgesGeometry(new T.BoxGeometry(...c.size_m)),new T.LineBasicMaterial({color:0x6db5e7,depthTest:false,transparent:true,opacity:.65}));wire.position.fromArray(c.center_m);bounds.add(wire);}group.add(marks,bounds);return{entry:e,group,marks,bounds};}
async function loadTower(spec){const gltf=await loader.loadAsync('../assets/'+spec.file),group=gltf.scene;group.position.fromArray(spec.position);group.scale.setScalar(1.5);group.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;o.material=o.material.clone();o.userData.original=o.material;o.userData.baseColor=o.material.color.clone();o.userData.baseEmission=o.material.emissive?.clone();o.userData.baseIntensity=o.material.emissiveIntensity;}});const lamp=new T.Mesh(new T.SphereGeometry(.16,12,8),new T.MeshBasicMaterial({color:0x64ffbc}));lamp.position.set(0,2.3,0);lamp.userData.overlay=true;group.add(lamp);return{...spec,group,lamp,yaw:group.getObjectByName('YAW')};}
function updatePower(){if($('asset').value!=='network')return;const capacity=solarCapacity(entry('solar_array',$('damage').value),entry('solar_power_station',$('stationDamage').value));network=evaluatePowerGrid([{id:'solar',position:sourcePosition,radius:28,capacity,enabled:capacity>0}],consumerSpecs);const active=network.filter(t=>t.powered).length;$('powerStatus').textContent=`${active} / 3 towers powered · ${capacity} power units`;$('towerStatus').replaceChildren(...network.map(t=>{const d=document.createElement('div');d.textContent=`${t.id}: ${t.reason}`;return d;}));$('fire').disabled=active===0;$('fireStatus').textContent=active?'Powered towers can track and fire.':'Power lost: tracking and firing disabled.';clearLines(lineGroup);clearLines(pulseGroup);
for(const t of towers){t.powered=network.find(n=>n.id===t.id).powered;t.lamp.material.color.set(t.powered?0x64ffbc:0xe6684d);t.group.traverse(o=>{if(o.userData.baseColor){o.userData.original.color.copy(o.userData.baseColor).multiplyScalar(t.powered?1:.4);if(o.userData.baseEmission)o.userData.original.emissive.copy(o.userData.baseEmission).multiplyScalar(t.powered?1:0);}});const points=[new T.Vector3(0,.2,10),new T.Vector3(t.position[0],.2,10),new T.Vector3(t.position[0],.2,t.position[2])];const line=new T.Line(new T.BufferGeometry().setFromPoints(points),new T.LineBasicMaterial({color:t.powered?0x65ddbc:0x674b47}));lineGroup.add(line);}
window.solarKit.network=network;window.solarKit.capacity=capacity;}
function fire(){if(!window.solarReady)return;for(const n of network)requestTowerFire(n,()=>{const t=towers.find(t=>t.id===n.id);const a=new T.Vector3(...t.position).add(new T.Vector3(0,1.8,0)),b=a.clone().add(new T.Vector3(0,1,-4));pulseGroup.add(new T.Line(new T.BufferGeometry().setFromPoints([a,b]),new T.LineBasicMaterial({color:0xa7ffe2})));shots++;});window.solarKit.shots=shots;elapsed=0;$('fireStatus').textContent=network.some(n=>n.powered)?'Powered towers fired a test pulse.':'No power: firing blocked.';}
async function load(){const ticket=++serial;window.solarReady=false;$('status').textContent='Loading solar installation…';const mode=$('asset').value,isNetwork=mode==='network';$('fire').disabled=true;if(isNetwork&&window.solarKit)updatePower();$('stationPanel').hidden=!isNetwork;$('networkPanel').hidden=!isNetwork;$('download').hidden=isNetwork;const jobs=isNetwork?[()=>loadAsset(entry('solar_array',$('damage').value)),()=>loadAsset(entry('solar_power_station',$('stationDamage').value),sourcePosition),...consumerSpecs.map(t=>()=>loadTower(t))]:[()=>loadAsset(entry(mode,$('damage').value))];
const results=await Promise.allSettled(jobs.map(j=>j()));const loaded=results.filter(r=>r.status==='fulfilled').map(r=>r.value);if(ticket!==serial){loaded.forEach(dispose);return;}const failure=results.find(r=>r.status==='rejected');if(failure){loaded.forEach(dispose);$('status').textContent='Load failed: '+failure.reason.message;console.error(failure.reason);return;}
[...items,...towers].forEach(dispose);items=loaded.filter(i=>i.entry);towers=loaded.filter(i=>!i.entry);for(const i of loaded)scene.add(i.group);clearLines(lineGroup);clearLines(pulseGroup);window.solarKit={items,towers,catalog,network,shots,fire,camera,orbit};appearance();fit();
if(isNetwork){updatePower();$('plot').textContent='28 m radius';$('description').textContent='Three nearby sentries draw power from this solar grid. D3 on either the array or station cuts supply. Restore both to bring the towers online. Orange cables belong to the model; colored lines show the power network.';$('status').textContent='Solar grid / interactive destruction test';}else{network=[];const e=items[0].entry;$('plot').textContent=e.plot_m.join(' × ')+' m';$('description').textContent=e.description;$('status').textContent=e.name+' / '+e.state;$('download').href='../assets/solar-power/'+e.file;}$('triangles').textContent=items.reduce((n,i)=>n+i.entry.triangles,0).toLocaleString();window.solarReady=true;}
for(const id of ['asset','damage','stationDamage'])$(id).onchange=load;for(const id of ['sockets','colliders','clay'])$(id).onchange=appearance;
$('destroy').onclick=()=>{$('stationDamage').value='3';load();};$('repair').onclick=()=>{$('stationDamage').value='0';$('damage').value='0';load();};$('fire').onclick=fire;$('reset').onclick=()=>fit();$('front').onclick=()=>fit(true);
new ResizeObserver(()=>{camera.aspect=stage.clientWidth/stage.clientHeight;camera.updateProjectionMatrix();renderer.setSize(stage.clientWidth,stage.clientHeight);fit();}).observe(stage);
const clock=new T.Clock();renderer.setAnimationLoop(()=>{const dt=Math.min(clock.getDelta(),.05);elapsed+=dt;for(const t of towers)if(t.powered&&t.yaw)t.yaw.rotation.y+=dt*.25;if(elapsed>.3&&pulseGroup.children.length)clearLines(pulseGroup);orbit.update();renderer.render(scene,camera);});
try{const response=await fetch('../assets/solar-power/manifest.json');if(!response.ok)throw Error('Manifest unavailable');catalog=(await response.json()).assets;$('asset').replaceChildren(new Option('Live grid / three sentry towers','network'),...catalog.filter(e=>e.damage_level===0).map(e=>new Option(e.name,e.family)));await load();}catch(e){$('status').textContent=e.message;console.error(e);}
