import * as T from 'three';import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';import {OrbitControls} from 'three/addons/controls/OrbitControls.js';import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
const $=id=>document.getElementById(id),stage=$('stage'),scene=new T.Scene(),camera=new T.PerspectiveCamera(40,1,.1,500),renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0x14252d);renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;stage.prepend(renderer.domElement);const env=new RoomEnvironment(),pmrem=new T.PMREMGenerator(renderer);scene.environment=pmrem.fromScene(env).texture;env.dispose();pmrem.dispose();scene.add(new T.HemisphereLight(0xe0f2ff,0x435456,2));const sun=new T.DirectionalLight(0xffedcc,3);sun.position.set(15,30,20);scene.add(sun);const floor=new T.Mesh(new T.PlaneGeometry(250,250),new T.MeshStandardMaterial({color:0x253c41,roughness:.9}));floor.rotation.x=-Math.PI/2;floor.position.y=-.02;scene.add(floor);const grid=new T.GridHelper(120,40,0x4b696a,0x32494f);scene.add(grid);const orbit=new OrbitControls(camera,renderer.domElement);orbit.enableDamping=true;orbit.maxPolarAngle=Math.PI*.85;
let entries=[],model,mixer,clips=[],ticket=0,active;const loader=new GLTFLoader();const node=name=>model?.getObjectByName(name),rad=v=>T.MathUtils.degToRad(+v);
function fit(){if(!model)return;const box=new T.Box3().setFromObject(model),center=box.getCenter(new T.Vector3()),radius=box.getSize(new T.Vector3()).length()/2;orbit.target.copy(center);camera.position.copy(center).add(new T.Vector3(.8,.6,1).normalize().multiplyScalar(radius/Math.sin(rad(20))/Math.min(camera.aspect,1)*1.1));orbit.update();}
function aim(){if(!model||$('lod').value==='2')return;for(const name of ['L','R','HEAVY']){node('GUN_'+name+'_PITCH').rotation.x=rad($(name==='HEAVY'?'heavy':'rotary').value);node('GUN_'+name+'_YAW').rotation.y=rad($('yaw').value);}for(const name of ['FL','FR','RL','RR'])node('ENGINE_'+name+'_PITCH').rotation.x=-rad($('engines').value);}
function pose(){if(!model)return;mixer.stopAllAction();active=null;const landed=$('pose').value==='landed',support=$('pose').value==='support';model.position.y=landed?0:12;$('rotary').value=support?50:0;$('heavy').value=support?45:0;$('engines').value=support||landed?90:0;if($('lod').value!=='2')for(const name of ['NOSE','L','R'])node('GEAR_'+name).rotation.x=landed?0:-Math.PI/2;aim();fit();}
function appearance(){if(!model)return;node('MARKING_GS01').visible=$('marking').checked;model.traverse(o=>{if(o.isMesh)for(const mat of [].concat(o.material))mat.wireframe=$('wire').checked;});}
function dispose(g){const geometries=new Set(),materials=new Set();g.traverse(o=>{if(o.isMesh){geometries.add(o.geometry);[].concat(o.material).forEach(m=>materials.add(m));}});geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());}
async function load(){const serial=++ticket;$('status').textContent='Loading KORP…';try{const e=entries.find(e=>e.lod===+$('lod').value),g=await loader.loadAsync('../assets/korp/'+e.file);if(serial!==ticket){dispose(g.scene);return;}if(model){mixer.stopAllAction();scene.remove(model);dispose(model);}model=g.scene;scene.add(model);mixer=new T.AnimationMixer(model);clips=g.animations;$('clip').replaceChildren(...clips.map(c=>new Option(c.name,c.name)));$('articulation').hidden=e.static;$('pose').disabled=e.static;$('marking').disabled=e.static;if(e.static)$('pose').value='landed';$('stats').textContent=`${e.triangles.toLocaleString()} triangles · ${e.draw_calls} draw calls · ${(e.bytes/1024).toFixed(1)} KB · ${clips.length} clips`;$('download').href='../assets/korp/'+e.file;pose();appearance();$('status').textContent=e.static?'Static distance tier / one mesh, one material':'KORP / forward weapons with downward ground-support articulation';}catch(e){$('status').textContent='Unable to load: '+e.message;}}
$('lod').onchange=load;$('pose').onchange=pose;for(const id of ['rotary','heavy','yaw','engines'])$(id).oninput=aim;for(const id of ['marking','wire'])$(id).onchange=appearance;$('reset').onclick=fit;$('play').onclick=()=>{if(!mixer)return;mixer.stopAllAction();const c=clips.find(c=>c.name===$('clip').value);if(!c)return;active=mixer.clipAction(c);active.reset().setLoop(c.name.endsWith('_Cycle')?T.LoopRepeat:T.LoopOnce,c.name.endsWith('_Cycle')?Infinity:1);active.clampWhenFinished=true;active.play();};$('stop').onclick=()=>{if(mixer){mixer.stopAllAction();pose();}};
new ResizeObserver(()=>{renderer.setSize(stage.clientWidth,stage.clientHeight);camera.aspect=stage.clientWidth/stage.clientHeight;camera.updateProjectionMatrix();}).observe(stage);const clock=new T.Clock();renderer.setAnimationLoop(()=>{mixer?.update(Math.min(clock.getDelta(),.05));orbit.update();renderer.render(scene,camera);});
try{const r=await fetch('../assets/korp/manifest.json');if(!r.ok)throw Error(r.status);entries=(await r.json()).assets;await load();}catch(e){$('status').textContent=e.message;}
