import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {MeshoptDecoder} from 'three/addons/libs/meshopt_decoder.module.js';
const $=id=>document.getElementById(id),stage=$('stage'),scene=new THREE.Scene();scene.background=new THREE.Color('#101820');
const camera=new THREE.PerspectiveCamera(40,1,.01,1000),renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));stage.prepend(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;
scene.add(new THREE.HemisphereLight(0xd9efff,0x34434b,3));const light=new THREE.DirectionalLight(0xffffff,4);light.position.set(3,6,4);scene.add(light);scene.add(new THREE.GridHelper(10,20,0x4a6572,0x263640));
const loader=new GLTFLoader().setMeshoptDecoder(MeshoptDecoder),neutral=new THREE.MeshStandardMaterial({color:0xa2adb5,roughness:.7});let model,serial=0,kick=0,mixer,clips=[],entry,manifest;
function fixed(){return !entry||entry.static||['Relay','Heptapod A6'].includes(entry.family);}
function pose(){if(!model)return;model.getObjectByName('YAW').rotation.y=fixed()?0:THREE.MathUtils.degToRad(+$('yaw').value);model.getObjectByName('PITCH').rotation.x=fixed()?0:-THREE.MathUtils.degToRad(+$('pitch').value);neutral.wireframe=$('wire').checked;model.traverse(o=>{if(o.isMesh){o.userData.original.wireframe=$('wire').checked;o.material=$('clay').checked?neutral:o.userData.original;}});}
function frame(){if(!model)return;model.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(model,true),center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3()),radius=size.length()*.5,distance=radius/Math.sin(THREE.MathUtils.degToRad(camera.fov*.5))*Math.max(1,1/camera.aspect)*1.13;controls.target.copy(center);camera.position.copy(center).addScaledVector(new THREE.Vector3(1.2,.8,1.6).normalize(),distance);camera.near=Math.max(.005,distance/1000);camera.far=Math.max(100,distance*10);camera.updateProjectionMatrix();controls.update();}
function mobility(){if(!mixer||entry.static)return;mixer.stopAllAction();const mode=$('mode').value;if(mode==='idle')return;const clip=clips.find(c=>c.name===(mode==='walk'?'Walk':'Anchor'));if(!clip)return;const action=mixer.clipAction(clip);action.reset();action.setLoop(mode==='walk'?THREE.LoopRepeat:THREE.LoopOnce,mode==='walk'?Infinity:1);action.clampWhenFinished=true;action.play();}
function reset(){mixer?.stopAllAction();kick=0;$('mode').value='idle';$('pitch').value=entry?.family==='Howitzer'?25:entry?.family==='Mortar'?68:0;$('yaw').value=0;pose();}
function dispose(root){const materials=new Set(),geometries=new Set();root.traverse(o=>{if(o.isMesh){geometries.add(o.geometry);materials.add(o.userData.original||o.material);}});geometries.forEach(g=>g.dispose());materials.forEach(m=>{if(m!==neutral)m.dispose();});}
async function load(){if(!manifest)return;const ticket=++serial,selected=manifest.assets.find(e=>e.family===$('family').value&&e.equipment_tier===+$('tier').value&&e.lod===+$('lod').value),file=$('encoding').value==='meshopt'?selected.meshopt_file:selected.file,url='assets/sentries/'+file;$('status').textContent='Loading…';try{const gltf=await loader.loadAsync(url);if(ticket!==serial){dispose(gltf.scene);return;}if(model){mixer?.stopAllAction();mixer?.uncacheRoot(model);scene.remove(model);dispose(model);}entry=selected;model=gltf.scene;clips=gltf.animations;mixer=clips.length?new THREE.AnimationMixer(model):null;model.traverse(o=>{if(o.isMesh)o.userData.original=o.material;});scene.add(model);$('pitch').min=entry.family==='Mortar'?45:entry.family==='Howitzer'?0:-10;for(const id of ['yaw','pitch','recoil'])$(id).disabled=fixed();$('mobility').hidden=entry.family!=='Heptapod A6'||entry.static;reset();frame();$('download').href=url;$('stats').textContent=`${entry.triangles.toLocaleString()} triangles · ${entry.draw_calls} draws · ${($('encoding').value==='meshopt'?entry.meshopt_bytes:entry.bytes).toLocaleString()} bytes`;$('status').textContent=`${entry.family} / Equipment ${entry.equipment_tier} / LOD${entry.lod} · D0 · ${entry.static?'Static preview — no aiming or clips':entry.stationary?'Fixed structure':entry.mobile?'Six legs · Walk / Anchor':'Articulated turret'}${entry.clips.length?' · '+entry.clips.map(c=>c.name+' '+Number(c.duration_s.toFixed(2))+'s').join(' / '):''}`;}catch(e){if(ticket===serial)$('status').textContent='Preview failed: '+e.message;console.error(e);}}
for(const id of ['family','tier','lod','encoding'])$(id).addEventListener('change',load);for(const id of ['yaw','pitch','clay','wire'])$(id).addEventListener('input',pose);$('recoil').onclick=()=>{if(!fixed())kick=.15;};$('mode').onchange=mobility;$('frame').onclick=frame;$('reset').onclick=reset;
new ResizeObserver(()=>{camera.aspect=stage.clientWidth/Math.max(1,stage.clientHeight);camera.updateProjectionMatrix();renderer.setSize(stage.clientWidth,stage.clientHeight);}).observe(stage);
const clock=new THREE.Clock();renderer.setAnimationLoop(()=>{const dt=Math.min(clock.getDelta(),.05);kick=Math.max(0,kick-dt*.35);if(model&&!entry.static)model.getObjectByName('RECOIL').position.z=-kick;mixer?.update(dt);controls.update();renderer.render(scene,camera);});
try{const response=await fetch('assets/sentries/manifest.json');if(!response.ok)throw Error('Manifest unavailable');manifest=await response.json();await load();}catch(e){$('status').textContent=e.message;}
window.sentryWorkshop={get model(){return model;},get entry(){return entry;},load,pose,frame,reset,scene,renderer};
