import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
import * as T from 'three';
import {GLTFExporter} from 'three/addons/exporters/GLTFExporter.js';
import {mergeGeometries,mergeVertices} from 'three/addons/utils/BufferGeometryUtils.js';
import {NodeIO} from '@gltf-transform/core';
import {ALL_EXTENSIONS,EXTMeshoptCompression} from '@gltf-transform/extensions';
import {dedup,prune,reorder} from '@gltf-transform/functions';
import {MeshoptEncoder,MeshoptDecoder,MeshoptSimplifier} from 'meshoptimizer';

const PROJECT=fileURLToPath(new URL('../..',import.meta.url));
const OUT=path.join(PROJECT,'assets/sol82');
const COLORS={carbon:0x101a21,gunmetal:0x50616a,steel:0x91a3a7,white:0xdce8e7,cyan:0x56e7f5,cyanDark:0x167a8c,amber:0xf0a638,radiator:0xffb04a,nav:0xa9f4ff,dark:0x050b10};
const CLIPS=[
  {name:'Arrays_Deploy',duration_s:2.5,loop:false},
  {name:'Aperture_Open',duration_s:.6,loop:false},
  {name:'Aperture_Close',duration_s:.6,loop:false},
  {name:'Idle_Cycle',duration_s:8,loop:true}
];
const REQUIRED=['ROOT','SOL82_RIG_ROOT','OPTICS_YAW','OPTICS_PITCH','APERTURE_IRIS','APERTURE','ARRAY_L','ARRAY_R','RADIATOR_L','RADIATOR_R','NAV_LIGHT_L','NAV_LIGHT_R','ENERGY_SPINE','SOL82_ARTICULATED_HARDWARE','SOL82_CARBON_ARMOR','SOL82_CYAN_ACCENTS','SOL82_WARNING_MARKS','SOL82_RADIATOR_SURFACES','SOL82_APERTURE_GLOW','NAV_LIGHTS_GEOMETRY','SOL82_DISTANCE_GEOMETRY','SOCKET_ENERGY_CORE','SOCKET_SENSOR_FORWARD','SOCKET_THRUSTER_REAR'];
const SOCKETS=[
  {id:'APERTURE',node:'APERTURE',kind:'beam_origin',position_m:[0,0,0],normal:[0,-1,0],available:true},
  {id:'ENERGY_CORE',node:'SOCKET_ENERGY_CORE',kind:'energy_core',position_m:[0,5.1,0],normal:[0,1,0],available:true},
  {id:'SENSOR_FORWARD',node:'SOCKET_SENSOR_FORWARD',kind:'sensor',position_m:[0,4.8,9],normal:[0,0,1],available:true},
  {id:'THRUSTER_REAR',node:'SOCKET_THRUSTER_REAR',kind:'propulsion',position_m:[0,4.8,-9],normal:[0,0,-1],available:true}
];
const MATERIAL_NAMES=['M_Hull_Carbon','M_Hull_Gunmetal','M_Ours_Cyan','M_Warning_Amber','M_Radiator_Glow','M_Aperture_Glow','M_Nav_Light'];

globalThis.FileReader=class{result=null;onloadend=null;onerror=null;readAsArrayBuffer(blob){blob.arrayBuffer().then(value=>{this.result=value;this.onloadend?.();},error=>this.onerror?.(error));}readAsDataURL(blob){blob.arrayBuffer().then(value=>{this.result=`data:${blob.type};base64,${Buffer.from(value).toString('base64')}`;this.onloadend?.();},error=>this.onerror?.(error));}};
await Promise.all([MeshoptEncoder.ready,MeshoptDecoder.ready,MeshoptSimplifier.ready]);
for(const folder of ['lod0','lod1','lod2'])await fs.mkdir(path.join(OUT,folder),{recursive:true});
const io=new NodeIO().registerExtensions(ALL_EXTENSIONS).registerDependencies({'meshopt.encoder':MeshoptEncoder,'meshopt.decoder':MeshoptDecoder});

function matrix(position=[0,0,0],rotation=[0,0,0],scale=[1,1,1]){return new T.Matrix4().compose(new T.Vector3(...position),new T.Quaternion().setFromEuler(new T.Euler(...rotation)),new T.Vector3(...scale));}
function colored(geometry,color,localMatrix=new T.Matrix4()){
  const output=geometry.index?geometry.toNonIndexed():geometry.clone();geometry.dispose();output.applyMatrix4(localMatrix);for(const key of Object.keys(output.attributes))if(!['position','normal'].includes(key))output.deleteAttribute(key);if(!output.attributes.normal)output.computeVertexNormals();const c=new T.Color(color),colors=new Float32Array(output.attributes.position.count*3);for(let i=0;i<colors.length;i+=3){colors[i]=c.r;colors[i+1]=c.g;colors[i+2]=c.b;}output.clearGroups();output.setAttribute('color',new T.Float32BufferAttribute(colors,3));return output;
}
function box(size,position,color,rotation=[0,0,0]){return colored(new T.BoxGeometry(...size),color,matrix(position,rotation));}
function cyl(radius,height,segments,position,color,rotation=[0,0,0],top=radius){return colored(new T.CylinderGeometry(top,radius,height,segments,1,false),color,matrix(position,rotation));}
function ring(radius,tube,segments,position,color,rotation=[0,0,0]){return colored(new T.TorusGeometry(radius,tube,6,segments),color,matrix(position,rotation));}
function sphere(radius,segments,position,color){return colored(new T.SphereGeometry(radius,segments,Math.max(6,Math.floor(segments*.6))),color,matrix(position));}
function merge(parts){const result=mergeGeometries(parts,false);for(const item of parts)item.dispose();if(!result)throw Error('Unable to merge SOL-82 geometry');return result;}
function packColors(geometry){const source=geometry.attributes.color,packed=new Uint8Array(source.count*3);for(let i=0;i<packed.length;i++)packed[i]=Math.max(0,Math.min(255,Math.round(source.array[i]*255)));geometry.setAttribute('color',new T.Uint8BufferAttribute(packed,3,true));}
function weldPack(geometry){const welded=mergeVertices(geometry,1e-5);geometry.dispose();packColors(welded);return welded;}
function triangles(geometry){return(geometry.index?geometry.index.count:geometry.attributes.position.count)/3;}
function simplifyGeometry(geometry,target,error=.035){
  if(triangles(geometry)<=target)return geometry.clone();const source=geometry.index?geometry.toNonIndexed():geometry.clone(),input=new T.BufferGeometry();input.setAttribute('position',source.attributes.position.clone());input.setAttribute('color',source.attributes.color.clone());source.dispose();const welded=mergeVertices(input,1e-5);input.dispose();const position=welded.attributes.position,index=Uint32Array.from(welded.index.array),targetCount=Math.max(3,Math.floor(target)*3),color=welded.attributes.color,colors=Float32Array.from({length:color.count*3},(_,i)=>color.getComponent(Math.floor(i/3),i%3));const [simplified]=MeshoptSimplifier.simplifyWithAttributes(index,position.array,3,colors,3,[.12,.12,.12],null,targetCount,error,['Permissive']),remap=new Map(),positions=[],outColors=[],indices=new Uint32Array(simplified.length);let next=0;for(let i=0;i<simplified.length;i++){const old=simplified[i];if(!remap.has(old)){remap.set(old,next++);positions.push(position.getX(old),position.getY(old),position.getZ(old));outColors.push(colors[old*3],colors[old*3+1],colors[old*3+2]);}indices[i]=remap.get(old);}welded.dispose();const output=new T.BufferGeometry();output.setAttribute('position',new T.Float32BufferAttribute(positions,3));output.setAttribute('color',new T.Float32BufferAttribute(outColors,3));output.setIndex(new T.BufferAttribute(indices,1));output.computeVertexNormals();return output;
}
function mat(name,{emissive=0,intensity=0,metalness=.45,roughness=.5}={}){const material=new T.MeshStandardMaterial({name,color:0xffffff,vertexColors:true,metalness,roughness});if(emissive){material.emissive.setHex(emissive);material.emissiveIntensity=intensity;material.userData={engine_driven_emissive:true,default_intensity:intensity};}return material;}
function beam(a,b,width,color){const p0=new T.Vector3(...a),p1=new T.Vector3(...b),direction=p1.clone().sub(p0),length=direction.length(),q=new T.Quaternion().setFromUnitVectors(new T.Vector3(0,1,0),direction.clone().normalize());return colored(new T.BoxGeometry(width,length,width),color,new T.Matrix4().compose(p0.add(p1).multiplyScalar(.5),q,new T.Vector3(1,1,1)));}
function makeBone(name,parent,position){const bone=new T.Bone();bone.name=name;bone.position.fromArray(position);parent.add(bone);return bone;}
function skinPart(geometry,bone,bones){geometry.applyMatrix4(bone.matrixWorld);const count=geometry.attributes.position.count,indices=new Uint16Array(count*4),weights=new Float32Array(count*4),boneIndex=bones.indexOf(bone);for(let i=0;i<count;i++){indices[i*4]=boneIndex;weights[i*4]=1;}geometry.setAttribute('skinIndex',new T.Uint16BufferAttribute(indices,4));geometry.setAttribute('skinWeight',new T.Float32BufferAttribute(weights,4));return geometry;}
function skinnedGeometry(parts,bones){const merged=merge(parts.map(item=>skinPart(item.geometry,item.bone,bones)));return weldPack(merged);}
function addLookup(root,name,position,normal=[0,0,1],data={}){const node=new T.Object3D();node.name=name;node.position.fromArray(position);node.quaternion.setFromUnitVectors(new T.Vector3(0,0,1),new T.Vector3(...normal).normalize());node.userData=data;root.add(node);return node;}
function arrayParts(side,lod){const parts=[],length=23,width=lod===0?7.6:7.2,thin=.14,seg=lod===0?10:6;parts.push(box([length,thin,width],[side*length/2,0,0],COLORS.cyanDark));parts.push(box([length+.35,.22,.18],[side*length/2,.01,width/2],COLORS.steel),box([length+.35,.22,.18],[side*length/2,.01,-width/2],COLORS.steel),box([.22,.24,width],[side*length,.01,0],COLORS.steel));for(let i=1;i<seg;i++){const x=side*(i*length/seg);parts.push(box([.09,.19,width],[x,.015,0],i%3===0?COLORS.cyan:COLORS.gunmetal));}for(const z of lod===0?[-2.85,-1.9,-.95,0,.95,1.9,2.85]:[-2.35,0,2.35])parts.push(box([length,.19,.08],[side*length/2,.015,z],COLORS.gunmetal));parts.push(box([1.2,.48,1.15],[side*.6,-.18,0],COLORS.gunmetal),ring(.42,.08,lod===0?20:12,[side*.18,-.18,0],COLORS.amber,[Math.PI/2,0,0]));return merge(parts);}
function radiatorParts(side,lod){const parts=[box([2.45,.14,9.4],[0,0,0],COLORS.dark),box([2.7,.18,.16],[0,.02,4.65],COLORS.radiator),box([2.7,.18,.16],[0,.02,-4.65],COLORS.radiator)];for(const z of lod===0?[-3.6,-2.4,-1.2,0,1.2,2.4,3.6]:[-3,0,3])parts.push(box([2.35,.19,.10],[0,.02,z],COLORS.radiator));parts.push(box([.16,.2,9.4],[side*.95,.02,0],COLORS.radiator));return merge(parts);}
function fixedGeometry(lod){const seg=lod===0?32:16,carbon=[cyl(3.15,14,8,[0,4.8,0],COLORS.carbon,[Math.PI/2,0,0]),cyl(3.05,2.8,8,[0,4.8,8.2],COLORS.carbon,[Math.PI/2,0,0],.25),cyl(3.05,1.2,8,[0,4.8,-7.6],COLORS.carbon,[Math.PI/2,0,0]),box([6.2,1.0,7.2],[0,7.15,0],COLORS.carbon),box([7.2,2.1,3.0],[0,4.9,-5.2],COLORS.carbon)],cyan=[],amber=[],nav=[];
  for(const x of [-2.45,2.45])for(const z of [-5.8,-2,2,5.8])carbon.push(box([.45,2.4,1.15],[x,4.8,z],COLORS.carbon,[0,0,x<0?-.16:.16]));
  for(const z of [-5.4,-1.8,1.8,5.4])cyan.push(box([4.85,.13,.18],[0,6.55,z],COLORS.cyan),ring(.48,.08,seg,[0,7.72,z],COLORS.cyan,[Math.PI/2,0,0]));
  for(const x of [-2.95,2.95])for(const z of [-6.3,6.3])cyan.push(box([.12,.65,1.1],[x,5.1,z],COLORS.cyan));
  for(const x of [-2.75,2.75])for(const z of [-4.2,0,4.2])amber.push(box([.12,.3,1.4],[x,3.8,z],COLORS.amber,[0,0,x<0?-.08:.08]));
  for(const x of [-2.8,2.8])for(const z of [-7.2,7.2])nav.push(sphere(.17,lod===0?16:8,[x,6.0,z],COLORS.nav));
  return{carbon:merge(carbon),cyan:merge(cyan),amber:merge(amber),nav:merge(nav)};
}
function hardwareGeometry(rig,lod){const seg=lod===0?32:16,parts=[];
  const rootParts=[box([6.8,.35,15.2],[0,4.8,0],COLORS.gunmetal),box([7.1,.25,4.3],[0,6.25,0],COLORS.steel)];for(const z of [-5.3,0,5.3])rootParts.push(cyl(.92,3.7,seg,[0,7.0,z],COLORS.gunmetal,[Math.PI/2,0,0]),ring(.94,.12,seg,[0,7.0,z-1.6],COLORS.amber,[0,0,0]),ring(.94,.12,seg,[0,7.0,z+1.6],COLORS.amber,[0,0,0]));for(const x of [-1.8,1.8])for(const y of [4.0,5.7])rootParts.push(cyl(.55,1.15,seg,[x,y,-8.3],COLORS.gunmetal,[Math.PI/2,0,0],.38));for(const x of [-2.2,2.2])rootParts.push(beam([x,5.5,6.4],[x,5.1,9.0],.22,COLORS.steel));parts.push({bone:rig.root,geometry:merge(rootParts)});
  parts.push({bone:rig.yaw,geometry:merge([ring(2.2,.25,seg,[0,0,0],COLORS.gunmetal,[Math.PI/2,0,0]),box([4.6,.35,1.0],[0,.25,0],COLORS.steel)])});
  parts.push({bone:rig.pitch,geometry:merge([cyl(1.85,2.9,seg,[0,0,0],COLORS.gunmetal),ring(1.9,.18,seg,[0,-1.35,0],COLORS.steel,[Math.PI/2,0,0]),ring(1.95,.16,seg,[0,1.2,0],COLORS.amber,[Math.PI/2,0,0])])});
  parts.push({bone:rig.iris,geometry:merge([cyl(1.45,.12,seg,[0,0,0],COLORS.dark),...Array.from({length:8},(_,i)=>box([.16,.15,1.35],[Math.sin(i*Math.PI/4)*.66,0,Math.cos(i*Math.PI/4)*.66],COLORS.gunmetal,[0,i*Math.PI/4,0]))])});
  parts.push({bone:rig.arrayL,geometry:arrayParts(-1,lod)},{bone:rig.arrayR,geometry:arrayParts(1,lod)});return parts;
}
function buildRig(root){const rigRoot=new T.Bone();rigRoot.name='SOL82_RIG_ROOT';root.add(rigRoot);const yaw=makeBone('OPTICS_YAW',rigRoot,[0,1.5,0]),pitch=makeBone('OPTICS_PITCH',yaw,[0,0,0]),iris=makeBone('APERTURE_IRIS',pitch,[0,-1.5,0]),arrayL=makeBone('ARRAY_L',rigRoot,[-3.1,4.8,0]),arrayR=makeBone('ARRAY_R',rigRoot,[3.1,4.8,0]),radiatorL=makeBone('RADIATOR_L',rigRoot,[-1.75,7.7,0]),radiatorR=makeBone('RADIATOR_R',rigRoot,[1.75,7.7,0]),nav=makeBone('NAV_LIGHTS_GEOMETRY',rigRoot,[0,0,0]);const aperture=new T.Object3D();aperture.name='APERTURE';aperture.position.set(0,-1.5,0);aperture.userData={socket_kind:'beam_origin',fire_axis:'-Y',engine_driven_parent:['OPTICS_YAW','OPTICS_PITCH']};pitch.add(aperture);root.updateMatrixWorld(true);return{root:rigRoot,yaw,pitch,iris,arrayL,arrayR,radiatorL,radiatorR,nav,bones:[rigRoot,yaw,pitch,iris,arrayL,arrayR,radiatorL,radiatorR,nav]};}
function qTrack(object,times,axis,angles){const values=[];for(const angle of angles)values.push(...new T.Quaternion().setFromAxisAngle(axis,angle).toArray());return new T.QuaternionKeyframeTrack(`${object.name}.quaternion`,times,values);}
function animationClips(rig,nav){const arrays=new T.AnimationClip('Arrays_Deploy',2.5,[qTrack(rig.arrayL,[0,1.3,2.5],new T.Vector3(0,0,1),[-1.38,-.55,0]),qTrack(rig.arrayR,[0,1.3,2.5],new T.Vector3(0,0,1),[1.38,.55,0]),qTrack(rig.radiatorL,[0,1.5,2.5],new T.Vector3(1,0,0),[-1.2,-.4,0]),qTrack(rig.radiatorR,[0,1.5,2.5],new T.Vector3(1,0,0),[1.2,.4,0])]);const open=new T.AnimationClip('Aperture_Open',.6,[new T.VectorKeyframeTrack('APERTURE_IRIS.scale',[0,.6],[1,1,1,.08,1,.08]),qTrack(rig.iris,[0,.6],new T.Vector3(0,1,0),[0,Math.PI*.55])]),close=new T.AnimationClip('Aperture_Close',.6,[new T.VectorKeyframeTrack('APERTURE_IRIS.scale',[0,.6],[.08,1,.08,1,1,1]),qTrack(rig.iris,[0,.6],new T.Vector3(0,1,0),[Math.PI*.55,0])]),idle=new T.AnimationClip('Idle_Cycle',8,[qTrack(rig.arrayL,[0,4,8],new T.Vector3(0,0,1),[-.018,.018,-.018]),qTrack(rig.arrayR,[0,4,8],new T.Vector3(0,0,1),[.018,-.018,.018]),qTrack(rig.radiatorL,[0,4,8],new T.Vector3(1,0,0),[-.012,.012,-.012]),qTrack(rig.radiatorR,[0,4,8],new T.Vector3(1,0,0),[.012,-.012,.012]),new T.VectorKeyframeTrack(`${nav.name}.scale`,[0,1,2,4,5,6,8],[1,1,1,1.32,1.32,1.32,1,1,1,1,1,1,1.32,1.32,1.32,1,1,1,1,1,1])]);return[arrays,open,close,idle];}
function createArticulated(lod){const assembly=new T.Group();assembly.name='SOL82_EXPORT_ASSEMBLY';assembly.userData={asset_id:`sol82_platform_d0_lod${lod}`,family:'sol82_platform',designation:'SOL-82',damage_level:0,lod,origin:'beam exit aperture',units:'meters',up:'+Y',forward:'+Z',beam_direction:'-Y',static:false};const rig=buildRig(assembly),fixed=fixedGeometry(lod),materials={carbon:mat('M_Hull_Carbon',{metalness:.6,roughness:.48}),gunmetal:mat('M_Hull_Gunmetal',{metalness:.72,roughness:.38}),cyan:mat('M_Ours_Cyan',{metalness:.35,roughness:.4}),amber:mat('M_Warning_Amber',{metalness:.25,roughness:.48}),radiator:mat('M_Radiator_Glow',{emissive:COLORS.radiator,intensity:.18,metalness:.35,roughness:.45}),aperture:mat('M_Aperture_Glow',{emissive:COLORS.cyan,intensity:.45,metalness:.2,roughness:.28}),nav:mat('M_Nav_Light',{emissive:COLORS.nav,intensity:1.8,metalness:.1,roughness:.25})},geometries=[
    skinnedGeometry([{bone:rig.root,geometry:fixed.carbon}],rig.bones),
    skinnedGeometry(hardwareGeometry(rig,lod),rig.bones),
    skinnedGeometry([{bone:rig.root,geometry:fixed.cyan}],rig.bones),
    skinnedGeometry([{bone:rig.root,geometry:fixed.amber}],rig.bones),
    skinnedGeometry([{bone:rig.radiatorL,geometry:radiatorParts(-1,lod)},{bone:rig.radiatorR,geometry:radiatorParts(1,lod)}],rig.bones),
    skinnedGeometry([{bone:rig.pitch,geometry:merge([ring(1.56,.14,lod===0?32:16,[0,-1.5,0],COLORS.cyan,[Math.PI/2,0,0]),cyl(.34,.08,lod===0?24:12,[0,-1.56,0],COLORS.white)])}],rig.bones),
    skinnedGeometry([{bone:rig.nav,geometry:fixed.nav}],rig.bones)
  ],combined=mergeGeometries(geometries,true);for(const geometry of geometries)geometry.dispose();if(!combined)throw Error('Unable to assemble SOL-82 material groups');const root=new T.SkinnedMesh(combined,[materials.carbon,materials.gunmetal,materials.cyan,materials.amber,materials.radiator,materials.aperture,materials.nav]);root.name='ROOT';root.userData={...assembly.userData};for(const child of [...assembly.children])root.add(child);root.bind(new T.Skeleton(rig.bones));
  const components=['SOL82_ARTICULATED_HARDWARE','SOL82_CARBON_ARMOR','SOL82_CYAN_ACCENTS','SOL82_WARNING_MARKS','SOL82_RADIATOR_SURFACES','SOL82_APERTURE_GLOW'];for(const name of components)addLookup(root,name,[0,0,0],[0,0,1],{component_lookup:true,geometry_primitive_on:'ROOT'});const energy=new T.Object3D();energy.name='ENERGY_SPINE';energy.position.set(0,7,0);energy.userData={role:'shielded_reactor_and_1_2_gigajoule_pulse_store'};root.add(energy);for(const item of [{name:'NAV_LIGHT_L',p:[-2.8,6,7.2]},{name:'NAV_LIGHT_R',p:[2.8,6,7.2]}])addLookup(root,item.name,item.p,[0,0,1],{role:'distance_glint'});for(const socket of SOCKETS.filter(item=>item.node!=='APERTURE'))addLookup(root,socket.node,socket.position_m,socket.normal,{socket_kind:socket.kind});const distance=new T.Object3D();distance.name='SOL82_DISTANCE_GEOMETRY';distance.userData={static_lookup_only:true};root.add(distance);root.updateMatrixWorld(true);return{root,clips:animationClips(rig,rig.nav),rig,materials};}
function geometryFor(object,anchor){object.updateWorldMatrix(true,false);anchor.updateWorldMatrix(true,false);const geometry=object.geometry.index?object.geometry.toNonIndexed():object.geometry.clone();geometry.applyMatrix4(new T.Matrix4().copy(anchor.matrixWorld).invert().multiply(object.matrixWorld));for(const key of Object.keys(geometry.attributes))if(!['position','normal','color'].includes(key))geometry.deleteAttribute(key);const color=geometry.attributes.color;if(color&&!(color.array instanceof Float32Array)){const values=new Float32Array(color.count*3);for(let i=0;i<color.count;i++){values[i*3]=color.getX(i);values[i*3+1]=color.getY(i);values[i*3+2]=color.getZ(i);}geometry.setAttribute('color',new T.Float32BufferAttribute(values,3));}geometry.clearGroups();return geometry;}
function staticLookups(){const root=new T.Group();root.name='ROOT';root.userData={asset_id:'sol82_platform_d0_lod2',family:'sol82_platform',designation:'SOL-82',damage_level:0,lod:2,origin:'beam exit aperture',units:'meters',up:'+Y',forward:'+Z',beam_direction:'-Y',static:true};const created=new Map([['ROOT',root]]),add=(name,parent='ROOT',position=[0,0,0])=>{const node=new T.Object3D();node.name=name;node.position.fromArray(position);node.userData={static_lookup_only:true};created.get(parent).add(node);created.set(name,node);return node;};add('SOL82_RIG_ROOT');add('OPTICS_YAW','SOL82_RIG_ROOT',[0,1.5,0]);add('OPTICS_PITCH','OPTICS_YAW');add('APERTURE_IRIS','OPTICS_PITCH',[0,-1.5,0]);const aperture=add('APERTURE','OPTICS_PITCH',[0,-1.5,0]);aperture.userData={socket_kind:'beam_origin',fire_axis:'-Y',static_lookup_only:true};add('ARRAY_L','SOL82_RIG_ROOT',[-3.1,4.8,0]);add('ARRAY_R','SOL82_RIG_ROOT',[3.1,4.8,0]);add('RADIATOR_L','SOL82_RIG_ROOT',[-1.75,7.7,0]);add('RADIATOR_R','SOL82_RIG_ROOT',[1.75,7.7,0]);for(const name of REQUIRED.filter(name=>!created.has(name)&&name!=='SOL82_DISTANCE_GEOMETRY'))add(name);for(const socket of SOCKETS.filter(item=>item.node!=='APERTURE')){const node=created.get(socket.node);node.position.fromArray(socket.position_m);node.quaternion.setFromUnitVectors(new T.Vector3(0,0,1),new T.Vector3(...socket.normal));node.userData={socket_kind:socket.kind,static_lookup_only:true};}return root;}
function createDistance(){const detailed=createArticulated(1),parts=[];detailed.root.traverse(object=>{if(object.isMesh)parts.push(geometryFor(object,detailed.root));});const merged=merge(parts),reduced=simplifyGeometry(merged,2700,.05);merged.dispose();packColors(reduced);const root=staticLookups(),material=mat('M_SOL82_DISTANCE_VERTEX_PALETTE',{metalness:.45,roughness:.55}),mesh=new T.Mesh(reduced,material);mesh.name='SOL82_DISTANCE_GEOMETRY';root.add(mesh);root.updateMatrixWorld(true);return{root,clips:[],materials:{distance:material}};}
function measure(root){let triangleCount=0,drawCalls=0;const materials=new Set(),textures=new Set(),skins=[];root.traverse(object=>{if(!(object.isMesh||object.isLine||object.isPoints))return;drawCalls+=object.geometry.groups.length||1;for(const material of [].concat(object.material||[])){materials.add(material);for(const key of ['map','normalMap','roughnessMap','metalnessMap','emissiveMap','aoMap'])if(material?.[key])textures.add(material[key]);}if(object.isMesh){triangleCount+=(object.geometry.index?object.geometry.index.count:object.geometry.attributes.position.count)/3;if(object.isSkinnedMesh)skins.push(object);}});return{triangles:Math.round(triangleCount),draw_calls:drawCalls,materials:materials.size,textures:textures.size,skins:skins.length};}
function bounds(root){root.updateMatrixWorld(true);const box=new T.Box3().setFromObject(root,true);return{min:box.min.toArray(),max:box.max.toArray(),dimensions_m:box.getSize(new T.Vector3()).toArray()};}
async function exportGLB(root,animations,file){const data=await new GLTFExporter().parseAsync(root,{binary:true,animations,onlyVisible:true,trs:true});await fs.writeFile(file,Buffer.from(data));}
async function sha(file){return crypto.createHash('sha256').update(await fs.readFile(file)).digest('hex');}
async function meshopt(file){const document=await io.read(file);await document.transform(dedup(),prune({keepLeaves:true,keepAttributes:true}),reorder({encoder:MeshoptEncoder,target:'size'}));document.createExtension(EXTMeshoptCompression).setRequired(true).setEncoderOptions({method:EXTMeshoptCompression.EncoderMethod.FILTER});const output=file.replace(/\.glb$/,'.meshopt.glb');await io.write(output,document);return{file:path.relative(OUT,output).split(path.sep).join('/'),bytes:(await fs.stat(output)).size,sha256:await sha(output)};}

const definitions=[{lod:0,folder:'lod0',file:'sol82_platform_detailed.glb',quality:'detailed_master',role:'close_cinematic_recording'},{lod:1,folder:'lod1',file:'sol82_platform_game.glb',quality:'game',role:'arrival_departure_and_close_orbit'},{lod:2,folder:'lod2',file:'sol82_platform_distance.glb',quality:'distance',role:'sky_silhouette_glint_and_loading'}],assets=[];
for(const definition of definitions){const built=definition.lod===2?createDistance():createArticulated(definition.lod),file=path.join(OUT,definition.folder,definition.file);await exportGLB(built.root,built.clips,file);const compressed=await meshopt(file),metrics=measure(built.root),entry={id:`sol82_platform_d0_lod${definition.lod}`,family:'sol82_platform',designation:'SOL-82',name:'SOL-82 orbital laser platform',file:path.relative(OUT,file).split(path.sep).join('/'),meshopt_file:compressed.file,lod:definition.lod,quality:definition.quality,damage_level:0,state:'intact',role:definition.role,static:definition.lod===2,derived:definition.lod===2,derived_from:definition.lod===2?'lod1/sol82_platform_game.glb':null,sha256:await sha(file),meshopt_sha256:compressed.sha256,bytes:(await fs.stat(file)).size,meshopt_bytes:compressed.bytes,...metrics,bounds:bounds(built.root),span_m:52.55,main_bus_length_m:17.95,origin:'centre of beam exit aperture',fire_direction:'-Y',forward:'+Z',up:'+Y',plot_m:[60,24],sockets:SOCKETS,colliders:[{id:'main_bus',center_m:[0,4.8,0],size_m:[7.2,6.2,18],condition:'D0'},{id:'array_envelope',center_m:[0,4.8,0],size_m:[52.55,.5,8],condition:'arrays_deployed'}],clips:definition.lod<2?CLIPS:[],animations:definition.lod<2?CLIPS.map(item=>item.name):[],required_nodes:REQUIRED,engine_nodes:REQUIRED,materials:definition.lod<2?MATERIAL_NAMES:['M_SOL82_DISTANCE_VERTEX_PALETTE'],review_status:'contract_candidate_pending_laser_lab_ground_camera_close_orbit_reference_phone',credit:'Model by jelaludo'};assets.push(entry);console.log(entry.id,entry.triangles,'triangles',entry.draw_calls,'draws',entry.bytes,'plain bytes',entry.meshopt_bytes,'Meshopt bytes');}
const manifest={schema:'jelaludo.asset-family/v2-candidate',version:2,family:'sol82_platform',label:'SOL-82 orbital laser platform',status:'contract_candidate_pending_laser_lab_ground_camera_close_orbit_reference_phone',plain_glb_source_of_truth:true,coordinate_system:{units:'meters',up:'+Y',forward:'+Z',origin:'centre of beam exit aperture',beam_direction:'-Y'},supported_damage_levels:[0],missing_damage_states_reason:'SOL-82 cannot be damaged in the current game; D1-D3 require a future gameplay request.',budgets:{lod1:{triangles_max:8000,draw_calls_max:10,plain_bytes_max:400000},lod2:{triangles_max:3000,draw_calls_max:1,plain_bytes_max:250000}},lod_selection:{initial:'lod2',approach_distance_m:150,hysteresis_m:20,detailed:'manual cinematic selection',review:'Tune from the laser lab ground camera, close orbit cut-in and reference phone.'},presentation:{primary:'wireframe material override in game and Workshop',full_material_asset:true,wireframe_geometry_duplicate:false,note:'The same topology supports the primary cyan wireframe read and the full carbon/gunmetal close-up treatment without shipping duplicate geometry.'},gameplay:{pass_interval_s:180,overhead_window_s:20,burn_budget_s:10,beam_wavelength_um:1.064,optical_output_mw:120,beam_vfx_external:true,footprint_radius_m:6,aim_range_m:320},lore:{energy:'A shielded continuous-power core charges a 1.2 GJ pulse store between passes; solar wings run the bus, cryocoolers and optical control.',thermal:'Phase-change heat sinks absorb a burn, then the paired radiator vanes unfold and reject heat before the next firing opportunity.',optics:'A two-axis ventral telescope steers a continuous 1.064 µm beam. The engine drives OPTICS_YAW and OPTICS_PITCH and creates all beam and ground effects.',name:'The owner named SOL-82 as an homage to SOL-740 and 1982.'},compression:{extension:'EXT_meshopt_compression',required:true,source_of_truth:'plain_glb'},assets};await fs.writeFile(path.join(OUT,'manifest.json'),JSON.stringify(manifest,null,2)+'\n');
console.log('SOL82_COMPLETE');
