import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
import * as T from 'three';
import {GLTFExporter} from 'three/addons/exporters/GLTFExporter.js';
import {mergeGeometries,mergeVertices} from 'three/addons/utils/BufferGeometryUtils.js';
import {NodeIO} from '@gltf-transform/core';
import {ALL_EXTENSIONS,EXTMeshoptCompression} from '@gltf-transform/extensions';
import {dedup,prune,reorder} from '@gltf-transform/functions';
import {MeshoptEncoder,MeshoptDecoder,MeshoptSimplifier} from 'meshoptimizer';

import {buildSyzygy,CLIP_INFO,EXTRA_NODES} from './sol82-syzygy.mjs';

const PROJECT=fileURLToPath(new URL('../..',import.meta.url));
const OUT=path.join(PROJECT,'assets/sol82');
const CLIPS=CLIP_INFO;
const REQUIRED=[...EXTRA_NODES,'ROOT','SOL82_RIG_ROOT','OPTICS_YAW','OPTICS_PITCH','APERTURE_IRIS','APERTURE','ARRAY_L','ARRAY_R','RADIATOR_L','RADIATOR_R','NAV_LIGHT_L','NAV_LIGHT_R','ENERGY_SPINE','SOL82_ARTICULATED_HARDWARE','SOL82_CARBON_ARMOR','SOL82_CYAN_ACCENTS','SOL82_WARNING_MARKS','SOL82_RADIATOR_SURFACES','SOL82_APERTURE_GLOW','NAV_LIGHTS_GEOMETRY','SOL82_DISTANCE_GEOMETRY','SOCKET_ENERGY_CORE','SOCKET_SENSOR_FORWARD','SOCKET_THRUSTER_REAR'];
const SOCKETS=[
  {id:'APERTURE',node:'APERTURE',kind:'beam_origin',position_m:[0,0,0],normal:[0,-1,0],available:true},
  {id:'ENERGY_CORE',node:'SOCKET_ENERGY_CORE',kind:'energy_core',position_m:[0,8.1,0],normal:[0,1,0],available:true},
  {id:'SENSOR_FORWARD',node:'SOCKET_SENSOR_FORWARD',kind:'sensor',position_m:[0,5,3.5],normal:[0,0,1],available:true},
  {id:'THRUSTER_REAR',node:'SOCKET_THRUSTER_REAR',kind:'propulsion',position_m:[0,8.1,-2.5],normal:[0,0,-1],available:true}
];
const MATERIAL_NAMES=['M_Hull_Carbon','M_Hull_Gunmetal','M_Ours_Cyan','M_Warning_Amber','M_Radiator_Glow','M_Aperture_Glow','M_Nav_Light'];

globalThis.FileReader=class{result=null;onloadend=null;onerror=null;readAsArrayBuffer(blob){blob.arrayBuffer().then(value=>{this.result=value;this.onloadend?.();},error=>this.onerror?.(error));}readAsDataURL(blob){blob.arrayBuffer().then(value=>{this.result=`data:${blob.type};base64,${Buffer.from(value).toString('base64')}`;this.onloadend?.();},error=>this.onerror?.(error));}};
await Promise.all([MeshoptEncoder.ready,MeshoptDecoder.ready,MeshoptSimplifier.ready]);
for(const folder of ['lod0','lod1','lod2'])await fs.mkdir(path.join(OUT,folder),{recursive:true});
const io=new NodeIO().registerExtensions(ALL_EXTENSIONS).registerDependencies({'meshopt.encoder':MeshoptEncoder,'meshopt.decoder':MeshoptDecoder});

function matrix(position=[0,0,0],rotation=[0,0,0],scale=[1,1,1]){return new T.Matrix4().compose(new T.Vector3(...position),new T.Quaternion().setFromEuler(new T.Euler(...rotation)),new T.Vector3(...scale));}
function colored(geometry,color,localMatrix=new T.Matrix4()){
  const output=geometry.index?geometry.toNonIndexed():geometry.clone();geometry.dispose();output.applyMatrix4(localMatrix);for(const key of Object.keys(output.attributes))if(!['position','normal'].includes(key))output.deleteAttribute(key);if(!output.attributes.normal)output.computeVertexNormals();const c=new T.Color(color),colors=new Float32Array(output.attributes.position.count*3);for(let i=0;i<colors.length;i+=3){colors[i]=c.r;colors[i+1]=c.g;colors[i+2]=c.b;}output.clearGroups();output.setAttribute('color',new T.Float32BufferAttribute(colors,3));return output;
}
function box(size,position,color,rotation=[0,0,0]){return colored(new T.BoxGeometry(...size),color,matrix(position,rotation));}
function cyl(radius,height,segments,position,color,rotation=[0,0,0],top=radius){return colored(new T.CylinderGeometry(top,radius,height,segments,1,false),color,matrix(position,rotation));}
function ring(radius,tube,segments,position,color,rotation=[0,0,0]){return colored(new T.TorusGeometry(radius,tube,6,segments),color,matrix(position,rotation));}
function sphere(radius,segments,position,color){return colored(new T.SphereGeometry(radius,segments,Math.max(6,Math.floor(segments*.6))),color,matrix(position));}
function merge(parts){const result=mergeGeometries(parts,false);for(const item of parts)item.dispose();if(!result)throw Error('Unable to merge SOL-82 geometry');return result;}
function packColors(geometry){const source=geometry.attributes.color,packed=new Uint8Array(source.count*3);for(let i=0;i<packed.length;i++)packed[i]=Math.max(0,Math.min(255,Math.round(source.array[i]*255)));geometry.setAttribute('color',new T.Uint8BufferAttribute(packed,3,true));}
function weldPack(geometry){const welded=mergeVertices(geometry,1e-5);geometry.dispose();packColors(welded);return welded;}
function triangles(geometry){return(geometry.index?geometry.index.count:geometry.attributes.position.count)/3;}
function simplifyGeometry(geometry,target,error=.035){
  if(triangles(geometry)<=target)return geometry.clone();const source=geometry.index?geometry.toNonIndexed():geometry.clone(),input=new T.BufferGeometry();input.setAttribute('position',source.attributes.position.clone());input.setAttribute('color',source.attributes.color.clone());source.dispose();const welded=mergeVertices(input,1e-5);input.dispose();const position=welded.attributes.position,index=Uint32Array.from(welded.index.array),targetCount=Math.max(3,Math.floor(target)*3),color=welded.attributes.color,colors=Float32Array.from({length:color.count*3},(_,i)=>color.getComponent(Math.floor(i/3),i%3));const [simplified]=MeshoptSimplifier.simplifyWithAttributes(index,position.array,3,colors,3,[.12,.12,.12],null,targetCount,error,['Permissive']),remap=new Map(),positions=[],outColors=[],indices=new Uint32Array(simplified.length);let next=0;for(let i=0;i<simplified.length;i++){const old=simplified[i];if(!remap.has(old)){remap.set(old,next++);positions.push(position.getX(old),position.getY(old),position.getZ(old));outColors.push(colors[old*3],colors[old*3+1],colors[old*3+2]);}indices[i]=remap.get(old);}welded.dispose();const output=new T.BufferGeometry();output.setAttribute('position',new T.Float32BufferAttribute(positions,3));output.setAttribute('color',new T.Float32BufferAttribute(outColors,3));output.setIndex(new T.BufferAttribute(indices,1));output.computeVertexNormals();return output;
}
function mat(name,{emissive=0,intensity=0,metalness=.45,roughness=.5}={}){const material=new T.MeshStandardMaterial({name,color:0xffffff,vertexColors:true,metalness,roughness});if(emissive){material.emissive.setHex(emissive);material.emissiveIntensity=intensity;material.userData={engine_driven_emissive:true,default_intensity:intensity};}return material;}
function makeBone(name,parent,position){const bone=new T.Bone();bone.name=name;bone.position.fromArray(position);parent.add(bone);return bone;}
function skinPart(geometry,bone,bones){geometry.applyMatrix4(bone.matrixWorld);const count=geometry.attributes.position.count,indices=new Uint16Array(count*4),weights=new Float32Array(count*4),boneIndex=bones.indexOf(bone);for(let i=0;i<count;i++){indices[i*4]=boneIndex;weights[i*4]=1;}geometry.setAttribute('skinIndex',new T.Uint16BufferAttribute(indices,4));geometry.setAttribute('skinWeight',new T.Float32BufferAttribute(weights,4));return geometry;}
function skinnedGeometry(parts,bones){const merged=merge(parts.map(item=>skinPart(item.geometry,item.bone,bones)));return weldPack(merged);}
function addLookup(root,name,position,normal=[0,0,1],data={}){const node=new T.Object3D();node.name=name;node.position.fromArray(position);node.quaternion.setFromUnitVectors(new T.Vector3(0,0,1),new T.Vector3(...normal).normalize());node.userData=data;root.add(node);return node;}
function createArticulated(lod){
  const built=buildSyzygy(lod,{box,cyl,ring,sphere,merge,colored,matrix,mat,makeBone,skinnedGeometry,mergeGeometries});
  for(const name of REQUIRED)if(!built.root.getObjectByName(name))addLookup(built.root,name,[0,0,0],[0,0,1],{lookup_only:true});
  for(const socket of SOCKETS.filter(item=>item.node!=='APERTURE')){const node=built.root.getObjectByName(socket.node);node.position.fromArray(socket.position_m);node.quaternion.setFromUnitVectors(new T.Vector3(0,0,1),new T.Vector3(...socket.normal));node.userData={socket_kind:socket.kind};}
  built.root.updateMatrixWorld(true);return built;
}
function createDistance(){
  const built=createArticulated(1),source=built.root;
  source.updateMatrixWorld(true);source.skeleton.update();
  const geometry=source.geometry.clone(),positions=geometry.attributes.position,v=new T.Vector3();
  for(let i=0;i<positions.count;i++){source.getVertexPosition(i,v);positions.setXYZ(i,v.x,v.y,v.z);}
  for(const key of Object.keys(geometry.attributes))if(!['position','normal','color'].includes(key))geometry.deleteAttribute(key);
  geometry.clearGroups();geometry.computeVertexNormals();
  const reduced=simplifyGeometry(geometry,2700,.06);geometry.dispose();packColors(reduced);
  const root=new T.Group();root.name='ROOT';root.userData={...source.userData,lod:2,static:true};
  function cloneLookup(node,parent){const copy=new T.Object3D();copy.name=node.name;copy.position.copy(node.position);copy.quaternion.copy(node.quaternion);copy.scale.copy(node.scale);copy.userData={...node.userData,static_lookup_only:true};parent.add(copy);for(const child of node.children)cloneLookup(child,copy);}
  for(const child of source.children)if(child.name!=='SOL82_DISTANCE_GEOMETRY')cloneLookup(child,root);
  const material=mat('M_SOL82_DISTANCE_VERTEX_PALETTE',{metalness:.7,roughness:.35}),mesh=new T.Mesh(reduced,material);mesh.name='SOL82_DISTANCE_GEOMETRY';root.add(mesh);root.updateMatrixWorld(true);
  return{root,clips:[],materials:{distance:material}};
}
function measure(root){let triangleCount=0,drawCalls=0;const materials=new Set(),textures=new Set(),skins=[];root.traverse(object=>{if(!(object.isMesh||object.isLine||object.isPoints))return;drawCalls+=object.geometry.groups.length||1;for(const material of [].concat(object.material||[])){materials.add(material);for(const key of ['map','normalMap','roughnessMap','metalnessMap','emissiveMap','aoMap'])if(material?.[key])textures.add(material[key]);}if(object.isMesh){triangleCount+=(object.geometry.index?object.geometry.index.count:object.geometry.attributes.position.count)/3;if(object.isSkinnedMesh)skins.push(object);}});return{triangles:Math.round(triangleCount),draw_calls:drawCalls,materials:materials.size,textures:textures.size,skins:skins.length};}
function bounds(root){root.updateMatrixWorld(true);const box=new T.Box3().setFromObject(root,true);return{min:box.min.toArray(),max:box.max.toArray(),dimensions_m:box.getSize(new T.Vector3()).toArray()};}
async function exportGLB(root,animations,file){const data=await new GLTFExporter().parseAsync(root,{binary:true,animations,onlyVisible:true,trs:true});await fs.writeFile(file,Buffer.from(data));}
async function sha(file){return crypto.createHash('sha256').update(await fs.readFile(file)).digest('hex');}
async function meshopt(file){const document=await io.read(file);await document.transform(dedup(),prune({keepLeaves:true,keepAttributes:true}),reorder({encoder:MeshoptEncoder,target:'size'}));document.createExtension(EXTMeshoptCompression).setRequired(true).setEncoderOptions({method:EXTMeshoptCompression.EncoderMethod.FILTER});const output=file.replace(/\.glb$/,'.meshopt.glb');await io.write(output,document);return{file:path.relative(OUT,output).split(path.sep).join('/'),bytes:(await fs.stat(output)).size,sha256:await sha(output)};}

const definitions=[{lod:0,folder:'lod0',file:'sol82_platform_detailed.glb',quality:'detailed_master',role:'close_cinematic_recording'},{lod:1,folder:'lod1',file:'sol82_platform_game.glb',quality:'game',role:'arrival_departure_and_close_orbit'},{lod:2,folder:'lod2',file:'sol82_platform_distance.glb',quality:'distance',role:'sky_silhouette_glint_and_loading'}],assets=[];
for(const definition of definitions){const built=definition.lod===2?createDistance():createArticulated(definition.lod),file=path.join(OUT,definition.folder,definition.file);await exportGLB(built.root,built.clips,file);const compressed=await meshopt(file),metrics=measure(built.root),entry={id:`sol82_platform_d0_lod${definition.lod}`,family:'sol82_platform',designation:'SOL-82',name:'SOL-82 Syzygy orbital laser',file:path.relative(OUT,file).split(path.sep).join('/'),meshopt_file:compressed.file,lod:definition.lod,quality:definition.quality,damage_level:0,state:'intact',role:definition.role,static:definition.lod===2,derived:definition.lod===2,derived_from:definition.lod===2?'lod1/sol82_platform_game.glb':null,sha256:await sha(file),meshopt_sha256:compressed.sha256,bytes:(await fs.stat(file)).size,meshopt_bytes:compressed.bytes,...metrics,bounds:bounds(built.root),span_m:40.2,core_length_m:9,motion_envelope_m:{min:[-20.1,-15.1,-20.1],max:[20.1,25.1,20.1]},origin:'centre of beam exit aperture',fire_direction:'-Y',forward:'+Z',up:'+Y',plot_m:[41,41],sockets:SOCKETS,colliders:[{id:'orbital_envelope',center_m:[0,5,0],size_m:[40.2,40.2,40.2],condition:'D0_motion_envelope_not_gameplay_collision'}],clips:definition.lod<2?CLIPS:[],animations:definition.lod<2?CLIPS.map(item=>item.name):[],required_nodes:REQUIRED,engine_nodes:REQUIRED,materials:definition.lod<2?MATERIAL_NAMES:['M_SOL82_DISTANCE_VERTEX_PALETTE'],review_status:'contract_candidate_pending_laser_lab_ground_camera_close_orbit_reference_phone',credit:'Model by jelaludo'};assets.push(entry);console.log(entry.id,entry.triangles,'triangles',entry.draw_calls,'draws',entry.bytes,'plain bytes',entry.meshopt_bytes,'Meshopt bytes');}
const manifest={schema:'jelaludo.asset-family/v2-candidate',version:3,family:'sol82_platform',label:'SOL-82 Syzygy orbital laser',status:'contract_candidate_pending_laser_lab_ground_camera_close_orbit_reference_phone',plain_glb_source_of_truth:true,coordinate_system:{units:'meters',up:'+Y',forward:'+Z',origin:'centre of beam exit aperture',beam_direction:'-Y'},supported_damage_levels:[0],missing_damage_states_reason:'SOL-82 cannot be damaged in the current game; D1-D3 require a future gameplay request.',budgets:{lod1:{triangles_max:8000,draw_calls_max:10,plain_bytes_max:400000},lod2:{triangles_max:3000,draw_calls_max:1,plain_bytes_max:250000}},motion:{cage_radii_m:[19.2,15.1,11.1],cage_radial_half_envelope_m:1.05,core_radial_envelope_m:5.5,aim_yaw_deg:[-35,35],aim_pitch_deg:[-22,22],firing_clearance_radius_m:.75,firing_duration_max_s:10,sequence:['Idle_Cycle','Convergence','Firing_Cycle','Recovery'],legacy_arrays:'ARRAY_L and ARRAY_R retained as deprecated lookup-only nodes; Arrays_Deploy replaced by Convergence',controller:'Convergence occupies the first 4 seconds of the 20-second overhead pass. First burn starts a maximum 10-second alignment window bounded by pass expiry; release does not restart it. Enforce the 10-second energy budget separately. Suppress the beam before Recovery.'},lod_selection:{initial:'lod2',approach_distance_m:150,hysteresis_m:20,detailed:'manual cinematic selection',review:'Tune from the laser lab ground camera, close orbit cut-in and reference phone.'},presentation:{primary:'cyan wireframe in game',workshop_default:'full_material',full_material_asset:true,wireframe_geometry_duplicate:false,note:'The same topology supports the primary cyan wireframe read and the full carbon/gunmetal close-up treatment without shipping duplicate geometry.'},gameplay:{pass_interval_s:180,overhead_window_s:20,burn_budget_s:10,beam_wavelength_um:1.064,optical_output_mw:120,beam_vfx_external:true,footprint_radius_m:6,aim_range_m:320},lore:{energy:'A central power core charges a 1.2 GJ optical-energy budget between passes. Rotating containment cages circulate the fictional storage fields; charging losses and waste heat are additional.',thermal:'Embedded radiator sectors reject heat during recovery. Sustained phase alignment depletes field stability, so the cages must return to their charging paths after at most ten seconds.',optics:'Three nested cages converge to maintain a clear polar corridor. A stabilized lens train sustains the continuous 1.064 µm beam for the ten-second energy window. The engine drives OPTICS_YAW and OPTICS_PITCH; beam effects remain external.',name:'The owner named SOL-82 as an homage to SOL-740 and 1982.'},compression:{extension:'EXT_meshopt_compression',required:true,source_of_truth:'plain_glb'},assets};await fs.writeFile(path.join(OUT,'manifest.json'),JSON.stringify(manifest,null,2)+'\n');
console.log('SOL82_COMPLETE');
