import fs from 'node:fs';import assert from 'node:assert/strict';import * as T from 'three';import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';import validator from 'gltf-validator';
const dir=new URL('../../assets/korp/',import.meta.url),{assets}=JSON.parse(fs.readFileSync(new URL('manifest.json',dir)));let baseline;
for(const e of assets){const b=fs.readFileSync(new URL(e.file,dir));const report=await validator.validateBytes(b,{maxIssues:20});assert.equal(report.issues.numErrors,0,JSON.stringify(report.issues));const json=JSON.parse(b.subarray(20,20+b.readUInt32LE(12)));assert(!json.images?.length);assert.equal(json.scenes.length,1);assert(!json.skins?.length);const g=await new GLTFLoader().parseAsync(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),'');g.scene.updateMatrixWorld(true);const names=[];let triangles=0;g.scene.traverse(o=>{names.push(o.name);if(o.isMesh){const geo=o.geometry,pos=geo.attributes.position,idx=geo.index;triangles+=idx.count/3;for(let i=0;i<idx.count;i+=3){const a=new T.Vector3().fromBufferAttribute(pos,idx.getX(i)),b=new T.Vector3().fromBufferAttribute(pos,idx.getX(i+1)),c=new T.Vector3().fromBufferAttribute(pos,idx.getX(i+2));assert(b.sub(a).cross(c.sub(a)).lengthSq()>1e-18,'degenerate triangle');}}});assert.equal(triangles,e.triangles);assert.equal(new Set(names.filter(Boolean)).size,names.filter(Boolean).length);assert(names.every(n=>!n.includes('.')));const node=n=>g.scene.getObjectByName(n);for(const n of e.engine_nodes)assert(node(n),n);const set=[...e.engine_nodes].sort();if(baseline)assert.deepEqual(set,baseline);else baseline=set;
const box=new T.Box3().setFromObject(g.scene,true);assert(box.min.y>=-.001);assert(box.min.x>=-15&&box.max.x<=15);assert(box.min.z>=-16&&box.max.z<=16);for(const s of e.sockets)assert(node(s.id).getWorldPosition(new T.Vector3()).distanceTo(new T.Vector3(...s.position_m))<.001);
if(e.lod===2){assert.equal(e.draw_calls,1);assert(e.triangles<3000);assert.equal(g.animations.length,0);}else{assert(e.triangles<25000);assert.equal(g.animations.length,7);for(const c of e.clips){assert(Math.abs(g.animations.find(a=>a.name===c.name).duration-c.duration_s)<.001);}const hull=node('HULL');for(const pitch of [0,35,60,70])for(const yaw of [-12,0,12])for(const gun of ['L','R','HEAVY']){node(`GUN_${gun}_PITCH`).rotation.x=T.MathUtils.degToRad(Math.min(pitch,gun==='HEAVY'?60:70));node(`GUN_${gun}_YAW`).rotation.y=T.MathUtils.degToRad(yaw);g.scene.updateMatrixWorld(true);const muzzle=node('SOCKET_MUZZLE_'+gun);const origin=muzzle.getWorldPosition(new T.Vector3()),direction=new T.Vector3(0,0,1).applyQuaternion(muzzle.getWorldQuaternion(new T.Quaternion()));assert.equal(new T.Raycaster(origin,direction,.01,40).intersectObject(hull,true).length,0,gun+' hull firing obstruction');}
const mixer=new T.AnimationMixer(g.scene);for(const name of ['Gear_Retract','Gear_Deploy','Ramp_Open','Ramp_Close','Heavy_Fire']){const clip=g.animations.find(c=>c.name===name),a=mixer.clipAction(clip);a.setLoop(T.LoopOnce,1);a.clampWhenFinished=true;a.play();for(let i=0;i<=10;i++){a.time=clip.duration*i/10;mixer.update(0);g.scene.updateMatrixWorld(true);}mixer.stopAllAction();}
const fire=g.animations.find(c=>c.name==='Heavy_Fire'),action=mixer.clipAction(fire);action.play();action.time=.08;mixer.update(0);assert(node('GUN_HEAVY_RECOIL').position.z<-.30&&node('GUN_HEAVY_RECOIL').position.z>-.39,'heavy recoil displacement');mixer.stopAllAction();
const retract=mixer.clipAction(g.animations.find(c=>c.name==='Gear_Retract'));retract.setLoop(T.LoopOnce,1);retract.clampWhenFinished=true;retract.play();retract.time=2;mixer.update(0);assert(Math.abs(node('GEAR_NOSE').rotation.x+Math.PI/2)<.005,'gear retraction angle');mixer.stopAllAction();}
console.log('PASS',e.id,e.triangles,'triangles',report.issues.numWarnings,'warnings');}
