import * as T from 'three';import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';import {OrbitControls} from 'three/addons/controls/OrbitControls.js';import {profiles,phases,sample,position,ignitionStart} from './flight.mjs';
const $=id=>document.getElementById(id),stage=$('stage'),scene=new T.Scene();scene.background=new T.Color('#101b22');scene.fog=new T.Fog('#101b22',60,150);
const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.toneMapping=T.ACESFilmicToneMapping;stage.prepend(renderer.domElement);
const camera=new T.PerspectiveCamera(42,1,.02,250),orbit=new OrbitControls(camera,renderer.domElement);orbit.enableDamping=true;
scene.add(new T.HemisphereLight(0xb7e5ef,0x34413a,2.8));const key=new T.DirectionalLight(0xffead8,3);key.position.set(10,20,8);scene.add(key);const fill=new T.DirectionalLight(0x67caef,2);fill.position.set(-8,4,-8);scene.add(fill);
const grid=new T.GridHelper(100,100,0x45616a,0x233c45);scene.add(grid);
const origin=new T.Vector3(0,1.2,0),axis=new T.Vector3(0,0,1),loader=new GLTFLoader();let assets=[],current=null,u=0,playing=true,hold=0,serial=0,path=null;
const socket=new T.Mesh(new T.TorusGeometry(.24,.014,6,24),new T.MeshBasicMaterial({color:0x7799a3}));socket.position.copy(origin);scene.add(socket);
const target=new T.Mesh(new T.RingGeometry(.4,.48,32),new T.MeshBasicMaterial({color:0xe2ac62,side:T.DoubleSide}));target.rotation.x=-Math.PI/2;scene.add(target);
const trailGeometry=new T.BufferGeometry();trailGeometry.setAttribute('position',new T.BufferAttribute(new Float32Array(32*3),3));
const trail=new T.Line(trailGeometry,new T.LineBasicMaterial({color:0x81e8da}));scene.add(trail);
const impact=new T.Mesh(new T.RingGeometry(.2,.3,24),new T.MeshBasicMaterial({color:0xffbb71,transparent:true,side:T.DoubleSide}));impact.rotation.x=-Math.PI/2;scene.add(impact);
for(const [name]of phases){const span=document.createElement('span');span.textContent=name;$('phases').append(span);}
function flightPath(){if(path){scene.remove(path);path.geometry.dispose();path.material.dispose();}const points=Array.from({length:181},(_,i)=>new T.Vector3(...position(i/180,$('profile').value)).add(origin));path=new T.Line(new T.BufferGeometry().setFromPoints(points),new T.LineDashedMaterial({color:0x466570,dashSize:.22,gapSize:.2}));path.computeLineDistances();scene.add(path);target.position.copy(points.at(-1));impact.position.copy(target.position);impact.position.y+=.02;}
function view(){const mode=$('view').value;if(mode==='inspect'){playing=false;camera.position.set(2.2,1.2,2.5);orbit.target.set(0,0,0);}else if(mode==='wide'){camera.position.set(32,20,-7);orbit.target.set(0,6,13);}else{camera.position.copy(new T.Vector3(3,2,-4).add(origin));orbit.target.copy(origin);}orbit.update();$('play').textContent=playing?'Pause':'Play';}
function dispose(g){const gs=new Set(),ms=new Set();g.traverse(o=>{if(o.geometry)gs.add(o.geometry);if(o.material)ms.add(o.material)});gs.forEach(g=>g.dispose());ms.forEach(m=>m.dispose());scene.remove(g);}
async function load(){const ticket=++serial;window.missileReady=false;const e=assets.find(a=>a.id===$('variant').value);try{const gltf=await loader.loadAsync('../assets/missile-kit/'+e.file);if(ticket!==serial){dispose(gltf.scene);return;}if(current)dispose(current.group);current={group:gltf.scene,motion:gltf.scene.getObjectByName('MISSILE_MOTION'),fx:gltf.scene.getObjectByName('EXHAUST_FX'),entry:e,gltf};scene.add(current.group);$('stats').textContent=`${e.triangles.toLocaleString()} triangles · ${e.draw_calls} batches · ${e.role}`;$('download').href='../assets/missile-kit/'+e.file;$('loading').textContent='Ready';window.missileReady=true;}catch(error){$('loading').textContent=error.message;console.error(error)}}
function replay(){u=0;hold=0;playing=true;if($('view').value==='inspect'){$('view').value='wide';view();}$('play').textContent='Pause';}
$('variant').onchange=load;$('profile').onchange=()=>{flightPath();replay();};$('view').onchange=view;$('play').onclick=()=>{if($('view').value==='inspect'){$('view').value='wide';view();}playing=!playing;$('play').textContent=playing?'Pause':'Play';};$('replay').onclick=replay;$('scrub').oninput=()=>{u=+$('scrub').value;playing=false;hold=0;$('play').textContent='Play';};
new ResizeObserver(()=>{camera.aspect=stage.clientWidth/stage.clientHeight;camera.updateProjectionMatrix();renderer.setSize(stage.clientWidth,stage.clientHeight)}).observe(stage);
const clock=new T.Clock();renderer.setAnimationLoop(()=>{const dt=Math.min(clock.getDelta(),.05),profile=$('profile').value,p=profiles[profile],inspect=$('view').value==='inspect';if(playing&&!inspect&&current){if(u>=1){hold+=dt;if($('loop').checked&&hold>.65){u=0;hold=0;}else if(!$('loop').checked){playing=false;$('play').textContent='Play';}}else u=Math.min(1,u+dt*+$('speed').value/p.duration);}
const state=sample(u,profile),pos=new T.Vector3(...state.position).add(origin);if(current){current.motion.position.copy(inspect?new T.Vector3():pos);current.motion.quaternion.setFromUnitVectors(axis,inspect?axis:new T.Vector3(...state.direction));current.fx.scale.setScalar(state.ignition&&!inspect?1:.001);current.group.visible=inspect||u<1;
if($('view').value==='follow'){const delta=pos.clone().sub(orbit.target);camera.position.add(delta);orbit.target.copy(pos);}}
grid.visible=!inspect;if(path)path.visible=$('guide').checked&&!inspect;socket.visible=target.visible=!inspect;trail.visible=!inspect&&u>ignitionStart&&u<1;for(let i=0;i<32;i++){const point=new T.Vector3(...position(Math.max(ignitionStart,u-i*.004),profile)).add(origin);trail.geometry.attributes.position.setXYZ(i,point.x,point.y,point.z);}trail.geometry.attributes.position.needsUpdate=true;trail.geometry.computeBoundingSphere();
impact.visible=u>=1&&!inspect;impact.scale.setScalar(1+Math.min(hold,.65)*6);impact.material.opacity=Math.max(0,1-hold/.65);
$('phase').textContent=inspect?current?.entry.name||'Inspect':u>=1?'Arrival':state.phase;$('detail').textContent=inspect?'1.49 m projectile · +Z forward':`${p.name} · ${state.ignition?'Rocket active':'Soft launch / no thrust'}`;$('scrub').value=u;$('time').textContent=`${(u*p.duration).toFixed(2)} / ${p.duration.toFixed(2)} s`;[...$('phases').children].forEach(e=>e.classList.toggle('active',e.textContent===state.phase));orbit.update();renderer.render(scene,camera);});
window.missile={get current(){return current},get progress(){return u},sample,replay};
try{const r=await fetch('../assets/missile-kit/manifest.json');if(!r.ok)throw Error('Manifest unavailable');assets=(await r.json()).assets;for(const a of assets){const o=document.createElement('option');o.value=a.id;o.textContent=a.name;$('variant').append(o);}$('variant').value='talon';flightPath();view();await load();}catch(e){$('loading').textContent=e.message;console.error(e)}
